Repository woowacourse-teams/2024-bang-ggood, pull requests merged in 2024-11, with the labels that each got.

#937 [FE] Amplitude 트래킹 플로우를 추가한다.
  frontend/src/App.tsx
  frontend/src/components/ArticleList/ArticleCard.tsx
  frontend/src/components/Landing/FirstSection.tsx
  frontend/src/components/_common/LoginButton/KakaoLoginButton.tsx
  frontend/src/hooks/query/useAddOAuthUserQuery.ts
  frontend/src/hooks/useAutoLogin.ts
  frontend/src/hooks/useOAuthLogin.ts
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/ChecklistQuestionSelectPage.tsx
  frontend/src/pages/SignInPage.tsx
  frontend/src/service/amplitude/AmplitudeInitializer.tsx
  frontend/src/service/amplitude/amplitudeInitializer.tsx
  frontend/src/service/amplitude/trackEvent.ts
Labels: 🔑 FE, 😊 Feature

#941 [BE] Spring Actuator 관련 설정을 추가한다.
  backend/bang-ggood/build.gradle
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/MonitoringConfig.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/repository/MonitoringChecklistRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/repository/MonitoringUserRepository.java
Labels: 🔒 BE, 😊 Feature, 🌏 Infra

#943 [BE/FE] 구현 사항을 PROD 서버에 배포한다.
  backend/bang-ggood/build.gradle
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/MonitoringConfig.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/repository/MonitoringChecklistRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/repository/MonitoringUserRepository.java
Labels: 🔒 BE, 🔑 FE, 🌏 Infra

#944 [BE] Spring Actuator 관련 설정을 추가한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/MonitoringConfig.java
Labels: 🔒 BE, 😊 Feature, 🌏 Infra

#948 [FE] 탭 이동 버튼과 드래그 이동을 구현한다.
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestionTemplate.tsx
  frontend/src/components/NewChecklist/ChecklistTab/NewChecklistTab.tsx
  frontend/src/components/NewChecklist/MoveNextButton.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomInfoTemplate.tsx
  frontend/src/components/NewChecklist/Option/OptionTemplate.tsx
  frontend/src/hooks/useMouseDrag.ts
  frontend/src/pages/NewChecklistPage.tsx
Labels: 🔑 FE, 😊 Feature

#950 [FE] 비밀번호 변경 기능을 구현한다
  frontend/playwright/tests/mock/signIn.spec.ts
  frontend/src/apis/url.ts
  frontend/src/apis/user.ts
  frontend/src/components/ResetPassword/EnterVerificationCodeStep.tsx
  frontend/src/components/ResetPassword/ResetPasswordStep.tsx
  frontend/src/components/ResetPassword/SendVerificationEmailStep.tsx
  frontend/src/components/ResetPassword/style.ts
  frontend/src/components/_common/Button/Button.tsx
  frontend/src/components/_common/FlexBox/FlexBox.tsx
  frontend/src/constants/messages/apiErrorMessage.ts
  frontend/src/constants/messages/message.ts
  frontend/src/constants/routePath.ts
  frontend/src/hooks/query/usePostResetPassword.ts
  frontend/src/hooks/query/usePostResetPasswordCode.ts
  frontend/src/hooks/query/usePostResetPasswordMail.ts
  frontend/src/hooks/useChangePassword.ts
  frontend/src/mocks/handlers/user.ts
  frontend/src/pages/ResetPasswordPage.tsx
  frontend/src/pages/SignInPage.tsx
  frontend/src/routers/router.tsx
  frontend/src/types/user.ts
Labels: 🔑 FE, 😊 Feature, 🧪 Test

#951 [FE] 최종 데모데이 이후 발견된 버그들을 수정한다.
  frontend/src/apis/checklist.ts
  frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
  frontend/src/components/Main/ArticlePreviewCard.tsx
  frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/IncludedMaintenances.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomFloor.tsx
  frontend/src/components/_common/Dropdown/Dropdown.tsx
  frontend/src/components/_common/Input/Input.tsx
  frontend/src/hooks/useMutateChecklist.ts
  frontend/src/hooks/useResetChecklist.ts
  frontend/src/mocks/fixtures/article.ts
  frontend/src/mocks/fixtures/articleList.ts
  frontend/src/mocks/fixtures/category.ts
  frontend/src/mocks/fixtures/checklistAllQuestions.ts
  frontend/src/mocks/fixtures/checklistDetail.ts
  frontend/src/mocks/fixtures/checklistList.ts
  frontend/src/mocks/fixtures/dummyChecklist.ts
  frontend/src/mocks/handlers/category.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/pages/EditChecklistPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/types/checklist.ts
Labels: 🐛 Bug, 🔑 FE

#843 [BE] 비밀번호 재설정 기능을 구현한다.
  backend/bang-ggood/build.gradle
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/domain/PasswordResetCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/request/ConfirmPasswordResetCodeRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/request/ForgotPasswordRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/request/ResetPasswordRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/repository/PasswordResetCodeRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/MailSender.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/PasswordResetService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/MailConfig.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/TimeConfig.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ClientExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/cookie/LoginMockE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/repository/PasswordResetCodeRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/MailSenderTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/PasswordResetServiceTest.java
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE, 😊 Feature

#959 [FE] swipe 기능을 ref를 받아 쓰도록 개선한다
  frontend/src/apis/user.ts
  frontend/src/components/EditChecklist/ChecklistContent/EditChecklistContent.tsx
  frontend/src/components/EditChecklist/ChecklistContent/EditChecklistQuestionTemplate.tsx
  frontend/src/components/NewChecklist/ChecklistContent.tsx
  frontend/src/components/NewChecklist/ChecklistTab/NewChecklistTab.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/DepositAndRent.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/MaintenanceFee.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/OccupancyMonth.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomContractTerm.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomFloor.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomSize.tsx
  frontend/src/components/ResetPassword/SendVerificationEmailStep.tsx
  frontend/src/components/_common/Tabs/TabContext.tsx
  frontend/src/constants/tabs.ts
  frontend/src/hooks/useMouseDrag.ts
Labels: 🐛 Bug, 🔑 FE, 😊 Feature, 🔧 Refactor

#957 [BE] 방 위치 정보(x, y축 정보)를 저장한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/global/DefaultChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/domain/Room.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/request/RoomRequest.java
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/room/RoomFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/domain/RoomTest.java
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE, 😊 Feature

#960 [BE] 체크리스트 삭제 로직에 반영 안 된 로직들을 추가한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/service/ChecklistStationService.java
Labels: 🔒 BE, 😊 Feature

#966 [BE] 쿠키 설정정보를 변경한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/cookie/CookieProvider.java
Labels: 🔒 BE, 😊 Feature

#968 [BE] 쿠키 sameSite를 None으로 변경한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/cookie/CookieProvider.java
Labels: 🔒 BE, 🔧 Refactor

#971 [BE] DEV와 DEV-BE를 머지한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/cookie/CookieProvider.java
Labels: 🔒 BE

#964 [FE] 아티클 마크다운 세팅을 변경한다.
  frontend/src/apis/user.ts
  frontend/src/components/ArticleDetail/ArticleContent.tsx
Labels: 🔑 FE, 🎨 UI

#977 [BE] DEV와 DEV-BE를 병합한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/cookie/CookieProvider.java
Labels: 🔒 BE

#982 [BE] 로컬 캐시를 적용한다.
  backend/bang-ggood/build.gradle
  backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/cache/CacheConfig.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/cache/CacheName.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/IntegrationTestSupport.java
  backend/bang-ggood/src/test/java/com/bang_ggood/JpaAuditingTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/global/cache/CacheTest.java
Labels: 🔒 BE, 😊 Feature

#983 [BE] 캐시 적용 코드를 포함하여 DEV와 DEV-BE를 머지한다.
  backend/bang-ggood/build.gradle
  backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/PasswordResetService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/cache/CacheConfig.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/cache/CacheName.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/controller/QuestionController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/ChecklistQuestion.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/ChecklistQuestions.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/ComparisonCategorizedQuestionsResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/CategoryRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/ChecklistQuestionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/IntegrationTestSupport.java
  backend/bang-ggood/src/test/java/com/bang_ggood/JpaAuditingTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/global/cache/CacheTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/ChecklistQuestionFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/domain/ChecklistQuestionTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/ChecklistQuestionRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/ChecklistQuestionServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/QuestionManageServiceTest.java
Labels: 🔒 BE, 😊 Feature

#988 [BE] 로그 포맷과 방식을 수정한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/global/logging/LoggingAspect.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/logging/dto/BaseLog.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/logging/dto/InfoLog.java
Labels: 🔒 BE, 😊 Feature

#979 [BE] 체크리스트 방 비교 기능을 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Checklist.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistCompareResponseV1.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistCompareResponsesV1.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ClientExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/like/repository/ChecklistLikeRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/Highlight.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CategoryScoreResponseV1.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CategoryScoreResponsesV1.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/QuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/ChecklistQuestionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/domain/Room.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/request/RoomRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/ChecklistQuestionFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/CustomChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/CategoryRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/ChecklistQuestionRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/ChecklistQuestionServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/RoomFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/repository/UserRepositoryTest.java
Labels: 🔒 BE, 😊 Feature

#986 [FE] 탭 이동 버튼 디자인을 수정한다.
  frontend/src/components/NewChecklist/MoveNextButton.tsx
Labels: 🔑 FE, 🎨 UI

#995 [BE] 캐시 TTL 시간을 변경한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/cache/CacheConfig.java
Labels: 🔒 BE, 😊 Feature

#997 [BE] 체크리스트 방 비교 기능을 추가 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/ChecklistQuestions.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/QuestionsScoreCalculator.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/ChecklistQuestionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/domain/QuestionsScoreCalculatorTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/ChecklistQuestionRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/ChecklistQuestionServiceTest.java
Labels: 🔒 BE, 😊 Feature

#1002 [BE] dev cd 파일을 업데이트 한다.
  .github/workflows/backend-dev-cd.yml
Labels: 🔒 BE, ⚙ Chore

#1005 [BE] 유저 정보 조회 시 userType을 같이 반환한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/user/dto/UserResponse.java
Labels: 🔒 BE, 😊 Feature

#1008 [BE] 로그레벨별로 파일 분리
  .github/workflows/backend-dev-cd.yml
  backend/bang-ggood/src/main/resources/console-error-appender.xml
  backend/bang-ggood/src/main/resources/console-info-appender.xml
  backend/bang-ggood/src/main/resources/console-warn-appender.xml
  backend/bang-ggood/src/main/resources/file-error-appender.xml
  backend/bang-ggood/src/main/resources/file-info-appender.xml
  backend/bang-ggood/src/main/resources/file-warn-appender.xml
  backend/bang-ggood/src/main/resources/logback.xml
Labels: 🔒 BE, 🌏 Infra

#973 [FE] 새 방 비교 페이지를 완성하고 방 선택 페이지를 만들어 연결한다.
  frontend/src/apis/room.ts
  frontend/src/apis/url.ts
  frontend/src/components/ChecklistDetail/CategoryAccordion.tsx
  frontend/src/components/ChecklistDetail/ChecklistAnswerSection.tsx
  frontend/src/components/ChecklistList/CustomBanner.tsx
  frontend/src/components/EditChecklist/ChecklistContent/EditChecklistQuestionTemplate.tsx
  frontend/src/components/Main/ChecklistPreviewCard.tsx
  frontend/src/components/MyPage/UserFeature.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestionAnswers.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestionTemplate.tsx
  frontend/src/components/NewChecklist/MemoModal/MemoButton.tsx
  frontend/src/components/RoomCompare/CategoryDetailModal.tsx
  frontend/src/components/RoomCompare/CategoryScore.tsx
  frontend/src/components/RoomCompare/CompareCard.tsx
  frontend/src/components/RoomCompare/CompareSelectCard.tsx
  frontend/src/components/RoomCompare/CompareSelectCardList.tsx
  frontend/src/components/RoomCompare/OptionDetailModal.tsx
  frontend/src/components/RoomCompare/RoomMarker.tsx
  frontend/src/components/_common/Accordion/AccordionBody.tsx
  frontend/src/components/_common/Accordion/AccordionHeader.tsx
  frontend/src/components/_common/Button/Button.tsx
  frontend/src/components/_common/FloatingButton/FloatingButton.tsx
  frontend/src/components/_common/Highlight/HighlightText.tsx
  frontend/src/components/_common/Map/AddressMap.tsx
  frontend/src/components/_common/Map/RoomCompareMap.tsx
  frontend/src/components/_common/Marker/Marker.stories.tsx
  frontend/src/components/_common/Marker/Marker.tsx
  frontend/src/components/_common/Modal/Modal.tsx
  frontend/src/components/_common/Subway/SubwayLineIcon/SubwayLineIcon.stories.tsx
  frontend/src/components/_common/Subway/SubwayLineIcon/SubwayLineIcon.tsx
  frontend/src/components/_common/Subway/SubwayStationItem.tsx
  frontend/src/components/_common/Subway/SubwayStations.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/routePath.ts
  frontend/src/hooks/query/useGetCompareRoomsQuery.ts
  frontend/src/hooks/query/useGetRoomCategoryDetail.ts
  frontend/src/mocks/fixtures/checklistList.ts
  frontend/src/mocks/fixtures/roomCategoryDetail.ts
  frontend/src/mocks/fixtures/roomCompare.ts
  frontend/src/mocks/handlers/roomCompare.ts
  frontend/src/pages/CategoryChoosePage.tsx
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/RoomComparePage.tsx
  frontend/src/pages/RoomCompareSelectPage.tsx
  frontend/src/routers/router.tsx
  frontend/src/types/RoomCompare.ts
  frontend/src/types/checklistCompare.ts
  frontend/src/utils/loadScript.ts
  frontend/tsconfig.json
Labels: 🔑 FE, 😊 Feature

#992 [FE] 체크리스트의 geolocaiton을 RoomInfo 내부로 이동한다
  frontend/src/components/_common/Map/RealTimeMap.tsx
  frontend/src/hooks/useMutateChecklist.ts
  frontend/src/hooks/useRoomInfoValidated.ts
  frontend/src/store/roomInfoStore.ts
  frontend/src/types/checklist.ts
  frontend/src/types/room.ts
Labels: 🔑 FE

#993 [FE] 아티클 에디터 페이지를 제작한다.
  frontend/package.json
  frontend/src/apis/article.ts
  frontend/src/components/ArticleDetail/ArticleContent.tsx
  frontend/src/components/_common/Button/Button.tsx
  frontend/src/components/_common/layout/DesktopLayout.tsx
  frontend/src/components/_common/layout/MobileLayout.tsx
  frontend/src/constants/routePath.ts
  frontend/src/hooks/query/usePostArticleQuery.ts
  frontend/src/mocks/handlers/article.ts
  frontend/src/pages/AdminPage.tsx
  frontend/src/pages/ArticleEditorPage.tsx
  frontend/src/routers/router.tsx
  frontend/src/styles/global.ts
  frontend/src/types/article.ts
  frontend/yarn.lock
Labels: 🔑 FE, 😊 Feature
