Repository woowacourse-teams/2024-bang-ggood, pull requests merged in 2024-07, with the labels that each got.

#3 프론트엔드 개발 환경을 세팅한다
  frontend/.eslintcache
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.husky/common.sh
  frontend/.husky/pre-commit
  frontend/.husky/pre-push
  frontend/.prettierrc
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/.stylelintrc.json
  frontend/.vscode/settings.json
  frontend/README.md
  frontend/index.html
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/components/Basic.tsx
  frontend/src/components/Box.tsx
  frontend/src/index.tsx
  frontend/tsconfig.json
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 🔑 FE

#7 체크리스트 페이지를 추가한다.
  frontend/.eslintrc.json
  frontend/.husky/pre-commit
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/Router.tsx
  frontend/src/_mock/checklist.json
  frontend/src/apis/checklist.ts
  frontend/src/apis/config.ts
  frontend/src/apis/fetcher.ts
  frontend/src/apis/url.ts
  frontend/src/assets/arrow-back.svg
  frontend/src/assets/arrow-down-small.svg
  frontend/src/assets/arrow-up-small.svg
  frontend/src/assets/assets.tsx
  frontend/src/assets/bang-ggood-icon.svg
  frontend/src/assets/face-icon/face-icon-bad-gray.svg
  frontend/src/assets/face-icon/face-icon-bad.svg
  frontend/src/assets/face-icon/face-icon-good-gray.svg
  frontend/src/assets/face-icon/face-icon-good.svg
  frontend/src/assets/face-icon/face-icon-soso-gray.svg
  frontend/src/assets/face-icon/face-icon-soso.svg
  frontend/src/assets/logo.svg
  frontend/src/assets/question-dot.svg
  frontend/src/components/Basic.tsx
  frontend/src/components/Box.tsx
  frontend/src/components/Check.tsx
  frontend/src/components/FaceMark/FaceIcon.tsx
  frontend/src/components/FaceMark/FaceMark.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/HeaderWithLogo.tsx
  frontend/src/components/Tab.tsx
  frontend/src/components/checklist/CheckListAnswer.tsx
  frontend/src/components/checklist/ChecklistCategory.tsx
  frontend/src/components/checklist/ChecklistQuestion.tsx
  frontend/src/index.tsx
  frontend/src/pages/ChecklistPage.tsx
  frontend/src/pages/ChecklistPreviewPage.tsx
  frontend/src/pages/SaveCheckListPage.tsx
  frontend/src/styles/common.ts
  frontend/src/styles/reset.ts
  frontend/src/styles/theme.ts
  frontend/src/types/checklist.ts
  frontend/src/types/custom.d.ts
  frontend/src/types/emotion.d.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 🔑 FE, 😊 Feature

#11 design: 마진 및 라인 하이트 수정
  frontend/src/components/checklist/CheckListAnswer.tsx
  frontend/src/components/checklist/ChecklistCategory.tsx
  frontend/src/components/checklist/ChecklistQuestion.tsx
  frontend/src/pages/SaveCheckListPage.tsx
Labels: 🔑 FE, 🎨 UI

#14 디자인 시스템을 설정한다.
  frontend/src/App.tsx
  frontend/src/Router.tsx
  frontend/src/components/Check.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/HeaderWithLogo.tsx
  frontend/src/components/checklist/CheckListAnswer.tsx
  frontend/src/components/checklist/ChecklistCategory.tsx
  frontend/src/components/checklist/ChecklistQuestion.tsx
  frontend/src/pages/ChecklistPage.tsx
  frontend/src/pages/SaveCheckListPage.tsx
  frontend/src/styles/reset.ts
  frontend/src/styles/theme.ts
Labels: 🔑 FE, ⚙ Chore, 🎨 UI

#17 공용 버튼 컴포넌트를 제작한다.
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/src/components/button/Button.stories.tsx
  frontend/src/components/button/Button.tsx
  frontend/src/styles/common.ts
  frontend/src/styles/theme.ts
Labels: 🔑 FE, 😊 Feature

#18 stylelint 자동 완성 설정 추가
  frontend/.stylelintrc.json
  frontend/.vscode/settings.json
  frontend/package-lock.json
  frontend/package.json
  frontend/yarn.lock
Labels: 🔑 FE, 🎨 UI

#26 storybook 기본 global 스타일링을 설정한다
  frontend/.storybook/global.ts
  frontend/.storybook/preview.tsx
  frontend/src/styles/theme.ts
Labels: 🔑 FE, ⚙ Chore

#28 공용 헤더, 푸터, FaceMark 컴포넌트를 제작한다.
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/package.json
  frontend/src/assets/assets.tsx
  frontend/src/assets/logos/checklist-logo-active.svg
  frontend/src/assets/logos/checklist-logo.svg
  frontend/src/assets/logos/home-logo-active.svg
  frontend/src/assets/logos/home-logo.svg
  frontend/src/assets/logos/location-logo-active.svg
  frontend/src/assets/logos/location-logo.svg
  frontend/src/assets/logos/my-page-logo-active.svg
  frontend/src/assets/logos/my-page-logo.svg
  frontend/src/components/FaceMark/FaceIcon.stories.tsx
  frontend/src/components/FaceMark/FaceIcon.tsx
  frontend/src/components/FaceMark/FaceMark.stories.tsx
  frontend/src/components/FaceMark/FaceMark.tsx
  frontend/src/components/Footer/Footer.stories.tsx
  frontend/src/components/Footer/Footer.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/Header/Header.stories.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/HeaderWithLogo.tsx
  frontend/src/components/checklist/CheckListAnswer.tsx
  frontend/src/components/checklist/ChecklistQuestion.tsx
  frontend/src/pages/ChecklistPage.tsx
  frontend/src/pages/ChecklistPreviewPage.tsx
  frontend/src/pages/SaveCheckListPage.tsx
  frontend/src/types/custom.d.ts
  frontend/yarn.lock
Labels: 🔑 FE, ⚙ Chore, 🎨 UI

#23 배지 공용 컴포넌트를 추가한다.
  frontend/src/components/badge/Badge.stories.tsx
  frontend/src/components/badge/Badge.tsx
  frontend/src/components/button/Button.tsx
Labels: 🔑 FE, 😊 Feature, 🧪 Test

#36 FaceIcon, FaceMark 사용처도 변경하여 에러를 해결한다
  frontend/.eslintcache
  frontend/package-lock.json
  frontend/src/components/FaceMark/FaceIcon.stories.tsx
  frontend/src/components/FaceMark/FaceIcon.tsx
  frontend/src/components/FaceMark/FaceMark.stories.tsx
  frontend/src/components/Footer/Footer.stories.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/accordion/AccodionHeader.tsx
  frontend/src/components/accordion/Accordion.stories.tsx
  frontend/src/components/accordion/Accordion.tsx
  frontend/src/components/accordion/AccordionBody.tsx
  frontend/src/components/button/Button.stories.tsx
  frontend/src/components/checklist/CheckListAnswer.tsx
  frontend/src/components/checklist/ChecklistCategory.tsx
  frontend/src/components/checklist/ChecklistQuestion.tsx
  frontend/src/pages/ChecklistPage.tsx
  frontend/src/pages/ChecklistPreviewPage.tsx
  frontend/src/pages/SaveCheckListPage.tsx
  frontend/yarn.lock
Labels: 🐛 Bug, 🔑 FE, 🎨 UI

#21 백엔드 CI/CD 설정을 추가한다.
  .github/workflows/backend-cd.yml
  .github/workflows/backend-ci.yml
Labels: 🔒 BE, ⚙ Chore, 🌏 Infra

#22 백엔드 초기 환경 설정을 한다.
  .idea/.gitignore
  .idea/2024-bang-ggood.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  backend/bang-ggood/.gitignore
  backend/bang-ggood/build.gradle
  backend/bang-ggood/gradle/wrapper/gradle-wrapper.jar
  backend/bang-ggood/gradle/wrapper/gradle-wrapper.properties
  backend/bang-ggood/gradlew
  backend/bang-ggood/gradlew.bat
  backend/bang-ggood/settings.gradle
  backend/bang-ggood/src/main/java/com/bang_ggood/Application.java
  backend/bang-ggood/src/main/java/com/bang_ggood/BaseEntity.java
  backend/bang-ggood/src/main/java/com/bang_ggood/config/SwaggerConfig.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/BangggoodException.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/GlobalExceptionHandler.java
  backend/bang-ggood/src/test/java/com/bang_ggood/JpaAuditingTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/TestRepository.java
Labels: 🔒 BE, ⚙ Chore

#33 스토리북 크로마틱 배포를 진행한다.
  .github/workflows/storybook.yml
  frontend/.storybook/global.ts
  frontend/.storybook/preview.tsx
  frontend/package.json
  frontend/yarn.lock
Labels: 🔑 FE, 🧪 Test

#31 공용 플로팅 버튼을 제작한다.
  frontend/.storybook/main.ts
  frontend/src/assets/assets.tsx
  frontend/src/assets/plus.svg
  frontend/src/components/Badge/Badge.stories.tsx
  frontend/src/components/Badge/Badge.tsx
  frontend/src/components/Button/Button.stories.tsx
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Button/FloatingButton.stories.tsx
  frontend/src/components/Button/FloatingButton.tsx
  frontend/src/components/Checklist/CheckListAnswer.tsx
  frontend/src/components/Checklist/ChecklistCategory.tsx
  frontend/src/components/Checklist/ChecklistQuestion.tsx
  frontend/src/components/button/FloatingButton.stories.tsx
  frontend/src/components/button/FloatingButton.tsx
  frontend/yarn.lock
Labels: 🔑 FE, 😊 Feature, 🧪 Test

#43 백엔드 CD 설정 오류를 수정한다.
  .github/workflows/backend-cd.yml
Labels: 🐛 Bug, 🔒 BE, ⚙ Chore, 🌏 Infra

#44 스토리북 CICD 작업 브랜치 수정
  .github/workflows/storybook.yml
Labels: 🔑 FE, 🧪 Test

#45 dev 브랜치와 dev-be 브랜치의 코드 상태를 병합시킨다.
  .github/workflows/backend-cd.yml
  .github/workflows/backend-ci.yml
  .idea/.gitignore
  .idea/2024-bang-ggood.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  backend/bang-ggood/.gitignore
  backend/bang-ggood/build.gradle
  backend/bang-ggood/gradle/wrapper/gradle-wrapper.jar
  backend/bang-ggood/gradle/wrapper/gradle-wrapper.properties
  backend/bang-ggood/gradlew
  backend/bang-ggood/gradlew.bat
  backend/bang-ggood/settings.gradle
  backend/bang-ggood/src/main/java/com/bang_ggood/Application.java
  backend/bang-ggood/src/main/java/com/bang_ggood/BaseEntity.java
  backend/bang-ggood/src/main/java/com/bang_ggood/config/SwaggerConfig.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/BangggoodException.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/GlobalExceptionHandler.java
  backend/bang-ggood/src/test/java/com/bang_ggood/JpaAuditingTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/TestRepository.java
Labels: 🔒 BE, ⚙ Chore

#39 공용 Input 컴포넌트를 구현한다.
  frontend/src/components/Input/Input.stories.tsx
  frontend/src/components/Input/Input.tsx
Labels: 🔑 FE, 😊 Feature, 🎨 UI

#41 공용 체크박스 컴포넌트를 구현한다.
  frontend/.storybook/main.ts
  frontend/package.json
  frontend/src/components/Checkbox/Checkbox.stories.tsx
  frontend/src/components/Checkbox/Checkbox.tsx
  frontend/yarn.lock
Labels: 🔑 FE, 😊 Feature, 🎨 UI

#48 카테고리 조회 기능을 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/category/controller/CategoryController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/CategoriesReadResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/CategoryReadResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/service/CategoryService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/category/service/CategoryServiceTest.java
Labels: 🔒 BE, 😊 Feature

#61 msw의 초기 세팅을 한다.
  frontend/package.json
  frontend/src/_mock/checklist.json
  frontend/src/apis/checklist.ts
  frontend/src/components/Checklist/CheckListAnswer.tsx
  frontend/src/components/Checklist/ChecklistQuestion.tsx
  frontend/src/components/common/Accordion/Accordion.tsx
  frontend/src/components/common/Accordion/AccordionBody.tsx
  frontend/src/index.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/fixtures/checklistQuestions.ts
  frontend/src/mocks/handlers/checklist.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/pages/ChecklistPage.tsx
  frontend/src/pages/ChecklistPreviewPage.tsx
  frontend/src/types/checklist.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: 🔑 FE, ⚙ Chore

#66 레이아웃 컴포넌트 제작한다.
  frontend/src/components/common/layout/Layout.tsx
  frontend/src/styles/global.ts
Labels: 🔑 FE, 😊 Feature

#73 chromatic comment on PR을 설정한다
  .github/workflows/storybook.yml
Labels: 🔑 FE, 🌏 Infra

#65 카테고리 우선순위 저장 기능을 구현한다.
  backend/bang-ggood/.gitignore
  backend/bang-ggood/src/main/java/com/bang_ggood/category/controller/CategoryController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/CategoryPriority.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/CategoryPriorityCreateRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/repository/CategoryPriorityRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/service/CategoryService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/User.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
  backend/bang-ggood/src/main/resources/data.sql
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/IntegrationTestSupport.java
  backend/bang-ggood/src/test/java/com/bang_ggood/JpaAuditingTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/category/service/CategoryServiceTest.java
  backend/bang-ggood/src/test/resources/data-test.sql
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE, 😊 Feature

#71 Cors 설정파일을 추가한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/config/CorsConfig.java
Labels: 🔒 BE, ⚙ Chore, 😊 Feature

#74 체크리스트 리스트 페이지를 추가한다.
  frontend/.storybook/common.tsx
  frontend/src/Router.tsx
  frontend/src/assets/arrow-right-green.svg
  frontend/src/assets/assets.tsx
  frontend/src/assets/bang-ggood-icon.svg
  frontend/src/assets/icons/arrow-right-yellow.svg
  frontend/src/assets/icons/bang-bang-icon.svg
  frontend/src/assets/icons/location-lined.svg
  frontend/src/components/ChecklistList/ChecklistPreviewCard.stories.tsx
  frontend/src/components/ChecklistList/ChecklistPreviewCard.tsx
  frontend/src/components/ChecklistList/CompareBanner.stories.tsx
  frontend/src/components/ChecklistList/CompareBanner.tsx
  frontend/src/components/NewChecklist/CheckListAnswer.tsx
  frontend/src/components/NewChecklist/ChecklistCategory.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion.tsx
  frontend/src/components/common/Badge/Badge.tsx
  frontend/src/components/common/Button/FloatingButton.tsx
  frontend/src/components/common/Footer/Footer.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/constants/system.ts
  frontend/src/mocks/fixtures/checklistList.ts
  frontend/src/mocks/handlers/checklist.ts
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/ChecklistPage.tsx
  frontend/src/pages/ChecklistPreviewPage.tsx
  frontend/src/pages/SaveCheckListPage.tsx
  frontend/src/styles/common.ts
  frontend/src/styles/global.ts
  frontend/src/styles/reset.ts
  frontend/src/types/Badge.ts
  frontend/src/types/checklist.ts
  frontend/src/utils/formattedDate.ts
Labels: 🔑 FE, 😊 Feature, 🧪 Test

#81 뱃지 도메인을 추가한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Badge.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
Labels: 🔒 BE, 😊 Feature

#83 체크리스트 질문 조회 API를 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/CategoryQuestionsResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Questionlist.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/ChecklistQuestionsResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/QuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/QuestionlistTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE, 😊 Feature

#91 새 체크리스트 작성페이지의 FaceIcon을 FaceMark로 수정한다.
  frontend/src/components/NewChecklist/ChecklistCategory.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion.tsx
  frontend/src/components/common/FaceMark/FaceMark.tsx
Labels: 🐛 Bug, 🔑 FE, 🎨 UI

#87 체크리스트 기본정보 페이지를 제작한다
  frontend/.eslintcache
  frontend/.eslintrc.json
  frontend/.storybook/main.ts
  frontend/.vscode/settings.json
  frontend/package.json
  frontend/src/Router.tsx
  frontend/src/assets/assets.tsx
  frontend/src/assets/input-required-dot.svg
  frontend/src/components/NewChecklist/ChecklistCategory.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/FaceMark/FaceMark.tsx
  frontend/src/components/common/FormField/FormField.stories.tsx
  frontend/src/components/common/FormField/FormField.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/Input/Input.stories.tsx
  frontend/src/components/common/Input/Input.tsx
  frontend/src/pages/NewChecklistBasicInfoPage.tsx
  frontend/src/styles/common.ts
  frontend/src/styles/reset.ts
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 🔑 FE, 😊 Feature, 🎨 UI

#97 새 체크리스트 기본정보 페이지를 리팩터링한다.
  frontend/src/Router.tsx
  frontend/src/components/common/FormField/FormField.stories.tsx
  frontend/src/components/common/FormField/FormField.tsx
  frontend/src/components/common/Input/Input.tsx
  frontend/src/hooks/useInput.ts
  frontend/src/pages/NewChecklistBasicInfoTemplate.tsx
  frontend/src/types/room.ts
Labels: 🔑 FE, 🔧 Refactor, 🎨 UI

#96 테스트 환경을 세팅한다.
  frontend/jest.config.js
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/components/NewChecklist/ChecklistCategory.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.test.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/NewChecklist/OptionModal/OptionModal.tsx
  frontend/src/components/common/OptionButton/OptionButton.tsx
  frontend/src/components/common/Tabs/BasicTabs.tsx
  frontend/src/mocks/svg.ts
  frontend/src/types/checklist.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: 🔑 FE, ⚙ Chore, 🧪 Test

#100 방 비교 결과 조회 API를 만든다.
  backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Badge.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Checklist.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Grade.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/BadgeResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/CategoryScoreReadResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/ChecklistComparisonReadResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/ChecklistsComparisonReadResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/UserChecklistPreviewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/UserChecklistsPreviewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistOptionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/GlobalExceptionHandler.java
  backend/bang-ggood/src/test/java/com/bang_ggood/category/domain/CategoryTest.java
Labels: 🔒 BE, 😊 Feature

#98 방 비교 페이지를 제작한다.
  frontend/src/Router.tsx
  frontend/src/apis/checklist.ts
  frontend/src/apis/url.ts
  frontend/src/components/ChecklistList/CompareBanner.tsx
  frontend/src/components/RoomCompare/CompareCard.tsx
  frontend/src/components/RoomCompare/CompareItem.tsx
  frontend/src/mocks/fixtures/roomsForCompare.ts
  frontend/src/mocks/handlers/checklist.ts
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/NewChecklistInfoTemplate.tsx
  frontend/src/pages/RoomComparePage.tsx
  frontend/src/styles/global.ts
  frontend/src/types/badge.ts
  frontend/src/types/category.ts
  frontend/src/types/checklist.ts
  frontend/src/types/room.ts
  frontend/src/utils/calcEmotions.ts
Labels: 🔑 FE, 😊 Feature

#101 작성한 체크리스트를 조회하는 API를 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/CategoryQuestionsResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/WrittenCategoryQuestionsResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Checklist.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/WrittenChecklistResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/WrittenQuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistOptionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistQuestionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/GlobalExceptionHandler.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/WrittenRoomResponse.java
Labels: 🔒 BE, 😊 Feature

#112 Lazy Initialization 예외를 해결한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Grade.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
Labels: 🐛 Bug, 🔒 BE

#114 새로운 체크리스트 작성 페이지의 데이터를 통합하고 보내는 로직을 작성한다.
  frontend/src/Router.tsx
  frontend/src/apis/checklist.ts
  frontend/src/assets/arrow-down-small.svg
  frontend/src/assets/arrow-up-small.svg
  frontend/src/assets/options/airconditioner-unfilled.svg
  frontend/src/assets/options/bed-unfilled.svg
  frontend/src/assets/options/closet-unfilled.svg
  frontend/src/assets/options/desk-unfilled.svg
  frontend/src/assets/options/dryer-unfilled.svg
  frontend/src/assets/options/elevator-unfilled.svg
  frontend/src/assets/options/gasrange-unfilled.svg
  frontend/src/assets/options/internet-unfilled.svg
  frontend/src/assets/options/microwave-unfilled.svg
  frontend/src/assets/options/refrigerator-unfillled.svg
  frontend/src/assets/options/shoescloset-unfilled.svg
  frontend/src/assets/options/sink-unfilled.svg
  frontend/src/assets/options/tv-unfilled.svg
  frontend/src/assets/options/washingmachine-unfilled.svg
  frontend/src/components/NewChecklist/ChecklistCategory.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/NewChecklist/OptionModal/OptionModal.tsx
  frontend/src/components/common/Accordion/Accordion.tsx
  frontend/src/components/common/Checkbox/Checkbox.tsx
  frontend/src/components/common/Tabs/BasicTabs.tsx
  frontend/src/components/common/Tabs/Tabs.stories.tsx
  frontend/src/components/common/Tabs/Tabs.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistInfoTemplate.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistPage.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistTemplate.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/checklist.ts
  frontend/src/types/room.ts
Labels: 🔑 FE, 😊 Feature, 🎨 UI

#119 배포 서버의 로그가 기록되지 않는 문제를 해결한다.
  .github/workflows/backend-cd.yml
Labels: 🐛 Bug, 🔒 BE, ⚙ Chore, 🌏 Infra

#118 Footer와 Header 공통 컴포넌트의 icon에 Link, navigator를 추가한다.
  frontend/src/components/common/Footer/Footer.tsx
  frontend/src/components/common/Header/Header.tsx
Labels: 🔑 FE, 😊 Feature, 🎨 UI

#120 1차 스프린트 API 연결한다.
  frontend/index.html
  frontend/src/apis/category.ts
  frontend/src/apis/checklist.ts
  frontend/src/apis/config.ts
  frontend/src/components/ChecklistList/ChecklistPreviewCard.tsx
  frontend/src/components/RoomCompare/CompareCard.tsx
  frontend/src/components/RoomCompare/CompareItem.tsx
  frontend/src/components/common/Footer/Footer.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/index.tsx
  frontend/src/mocks/fixtures/checklistList.ts
  frontend/src/pages/CategoryChoosePage.tsx
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/RoomComparePage.tsx
  frontend/src/styles/global.ts
  frontend/src/types/badge.ts
  frontend/src/types/checklist.ts
Labels: 🔑 FE, 😊 Feature

#125 build 시 에러가 발생하는 문제를 해결한다.
  frontend/package.json
  frontend/src/pages/CategoryChoosePage.tsx
  frontend/webpack.config.js
Labels: 🐛 Bug, 🔑 FE, ⚙ Chore, 😊 Feature

#129 체크리스트 선택지 저장 못했던 에러 수정하고 체크리스트 답변에 대한 훅으로 리팩토링한다.
  frontend/src/components/ChecklistList/CompareBanner.tsx
  frontend/src/components/NewChecklist/ChecklistCategory.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.test.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/hooks/useChecklistAnswer.ts
  frontend/src/pages/NewChecklistPage/NewChecklistPage.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistTemplate.tsx
  frontend/webpack.config.js
Labels: 🐛 Bug, 🔑 FE, 🎨 UI

#131 1차 스프린트 페이지내에 에러를 수정한다.
  frontend/src/Router.tsx
  frontend/src/components/ChecklistList/ChecklistPreviewCard.tsx
  frontend/src/components/RoomCompare/CompareCard.tsx
  frontend/src/components/RoomCompare/CompareItem.tsx
  frontend/src/components/common/Button/FloatingButton.tsx
  frontend/src/components/common/Footer/Footer.stories.tsx
  frontend/src/components/common/Footer/Footer.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/layout/Layout.tsx
  frontend/src/mocks/fixtures/checklistList.ts
  frontend/src/mocks/fixtures/roomsForCompare.ts
  frontend/src/pages/CategoryChoosePage.tsx
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistInfoTemplate.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistPage.tsx
  frontend/src/pages/NotFound.tsx
  frontend/src/types/room.ts
  frontend/src/utils/calcEmotions.ts
Labels: 🐛 Bug, 🔑 FE

#133 roomName 이슈를 해결한다.
  frontend/src/pages/NewChecklistPage/NewChecklistInfoTemplate.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistPage.tsx
  frontend/src/types/room.ts
Labels: 🐛 Bug, 🔑 FE

#135 질문 목록 조회 시 질문 순서, 목록이 잘못 조회되는 문제를 해결한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
Labels: 🐛 Bug, 🔒 BE

#137 체크리스트 조회 페이지를 제작한다.
  frontend/src/Router.tsx
  frontend/src/apis/checklist.ts
  frontend/src/apis/url.ts
  frontend/src/components/ChecklistList/ChecklistPreviewCard.tsx
  frontend/src/components/NewChecklist/CheckListAnswer.tsx
  frontend/src/components/NewChecklist/ChecklistCategory.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/common/Accordion/Accordion.tsx
  frontend/src/components/common/Accordion/AccordionBody.tsx
  frontend/src/components/common/layout/Layout.tsx
  frontend/src/hooks/useChecklistAnswer.ts
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/ChecklistPreviewPage.tsx
  frontend/src/pages/ChecklistSummaryPage.tsx
  frontend/src/types/checklist.ts
Labels: 🔑 FE, 😊 Feature

#138 토스트 메세지 컴포넌트를 만든다.
  frontend/.storybook/preview-body.html
  frontend/index.html
  frontend/src/components/NewChecklist/ChecklistCategory.tsx
  frontend/src/components/common/Toast/Toast.stories.tsx
  frontend/src/components/common/Toast/Toast.tsx
  frontend/src/hooks/useToast.ts
  frontend/src/pages/NewChecklistPage/NewChecklistPage.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistTemplate.tsx
Labels: 🔑 FE, 😊 Feature

#140 useChecklistAnswer 훅 테스트를 추가한다
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion_UI.test.tsx
  frontend/src/components/common/Footer/Footer.stories.tsx
  frontend/src/components/common/Footer/Footer.tsx
  frontend/src/constants/routePath.ts
  frontend/src/hooks/useChecklistAnswer.test.ts
  frontend/src/pages/ChecklistSummaryPage.tsx
Labels: 🔑 FE, 🧪 Test

#142 asset의 폴더 구조를 정리하고 파일 이름을 수정한다.
  frontend/src/Router.tsx
  frontend/src/assets/assets.tsx
  frontend/src/assets/icons/arrow/arrow-back.svg
  frontend/src/assets/icons/arrow/arrow-down-small.svg
  frontend/src/assets/icons/arrow/arrow-right-green.svg
  frontend/src/assets/icons/arrow/arrow-right-yellow.svg
  frontend/src/assets/icons/arrow/arrow-up-small.svg
  frontend/src/assets/icons/check.svg
  frontend/src/assets/icons/delete.svg
  frontend/src/assets/icons/face-icon/face-icon-bad-gray.svg
  frontend/src/assets/icons/face-icon/face-icon-bad.svg
  frontend/src/assets/icons/face-icon/face-icon-good-gray.svg
  frontend/src/assets/icons/face-icon/face-icon-good.svg
  frontend/src/assets/icons/face-icon/face-icon-soso-gray.svg
  frontend/src/assets/icons/face-icon/face-icon-soso.svg
  frontend/src/assets/icons/footer-icon/checklist-logo-active.svg
  frontend/src/assets/icons/footer-icon/checklist-logo.svg
  frontend/src/assets/icons/footer-icon/home-logo-active.svg
  frontend/src/assets/icons/footer-icon/home-logo.svg
  frontend/src/assets/icons/footer-icon/location-logo-active.svg
  frontend/src/assets/icons/footer-icon/location-logo.svg
  frontend/src/assets/icons/footer-icon/my-page-logo-active.svg
  frontend/src/assets/icons/footer-icon/my-page-logo.svg
  frontend/src/assets/icons/input-required-dot.svg
  frontend/src/assets/icons/logo.svg
  frontend/src/assets/icons/options/airconditioner-filled.svg
  frontend/src/assets/icons/options/airconditioner-unfilled.svg
  frontend/src/assets/icons/options/bed-filled.svg
  frontend/src/assets/icons/options/bed-unfilled.svg
  frontend/src/assets/icons/options/closet-filled.svg
  frontend/src/assets/icons/options/closet-unfilled.svg
  frontend/src/assets/icons/options/desk-filled.svg
  frontend/src/assets/icons/options/desk-unfilled.svg
  frontend/src/assets/icons/options/dryer-filled.svg
  frontend/src/assets/icons/options/dryer-unfilled.svg
  frontend/src/assets/icons/options/elevator-filled.svg
  frontend/src/assets/icons/options/elevator-unfilled.svg
  frontend/src/assets/icons/options/gasrange-filled.svg
  frontend/src/assets/icons/options/gasrange-unfilled.svg
  frontend/src/assets/icons/options/internet-filled.svg
  frontend/src/assets/icons/options/internet-unfilled.svg
  frontend/src/assets/icons/options/microwave-filled.svg
  frontend/src/assets/icons/options/microwave-unfilled.svg
  frontend/src/assets/icons/options/refrigerator-filled.svg
  frontend/src/assets/icons/options/refrigerator-unfillled.svg
  frontend/src/assets/icons/options/shoescloset-filled.svg
  frontend/src/assets/icons/options/shoescloset-unfilled.svg
  frontend/src/assets/icons/options/sink-filled.svg
  frontend/src/assets/icons/options/sink-unfilled.svg
  frontend/src/assets/icons/options/tv-filled.svg
  frontend/src/assets/icons/options/tv-unfilled.svg
  frontend/src/assets/icons/options/washingmachine-filled.svg
  frontend/src/assets/icons/options/washingmachine-unfilled.svg
  frontend/src/assets/icons/plus.svg
  frontend/src/assets/icons/question-dot.svg
  frontend/src/components/common/Accordion/AccordionBody.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/OptionButton/OptionIcon.tsx
  frontend/src/pages/ChecklistSummaryPage.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistInfoTemplate.tsx
Labels: 🔑 FE, 🔧 Refactor

#147 fix: 체크리스트 저장 버그 수정
  frontend/src/hooks/useChecklistAnswer.ts
  frontend/src/pages/NewChecklistPage/NewChecklistPage.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistTemplate.tsx
Labels: 🐛 Bug, 🔑 FE

#155 토스트 컴포넌트를 전역으로 수정하고, zIndex를 테마 상수화 시킨다.
  frontend/index.html
  frontend/src/App.tsx
  frontend/src/components/common/Button/FloatingButton.tsx
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/Toast/Toast.stories.tsx
  frontend/src/components/common/Toast/Toast.tsx
  frontend/src/components/common/Toast/ToastContext.tsx
  frontend/src/hooks/useToast.ts
  frontend/src/index.tsx
  frontend/src/pages/CategoryChoosePage.tsx
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistPage.tsx
  frontend/src/pages/NotFound.tsx
  frontend/src/styles/theme.ts
Labels: 🔑 FE, 😊 Feature

#160 백앤드 1차 스프린트 리팩토링을 진행한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/ChecklistQuestion.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Question.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/category/domain/CategoryTest.java
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE, 🔧 Refactor

#163 [FE] 반복사용되는 footerDefault를 더쉽게 사용한다.
  frontend/src/components/FooterDefault.tsx
  frontend/src/pages/ChecklistListPage.tsx
Labels: 🔑 FE, 🎨 UI

#172 [FE] 탭을 변경된 디자인으로 리팩토링한다.
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/NewChecklist/OptionModal/OptionModal.tsx
  frontend/src/components/NewChecklist/OptionModal/OptionModalInfoBox.tsx
  frontend/src/components/common/Checkbox/Checkbox.tsx
  frontend/src/components/common/Tabs/TabContext.tsx
  frontend/src/components/common/Tabs/Tabs.stories.tsx
  frontend/src/components/common/Tabs/Tabs.tsx
  frontend/src/constants/tabs.ts
  frontend/src/hooks/useAllSelect.ts
  frontend/src/hooks/useChecklistAnswer.ts
  frontend/src/pages/NewChecklistPage/NewChecklistBody.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistInfoTemplate.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistPage.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistTemplate.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/tab.ts
Labels: 🔑 FE, 😊 Feature, 🎨 UI

#175 [FE] 체크리스트 리스트 페이지 내 코드 리팩토링 및 시간 포맷팅을 추가한다.
  frontend/src/components/ChecklistList/ChecklistPreviewCard.tsx
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/utils/formattedDate.ts
Labels: 🔑 FE, 😊 Feature

#177 [FE] 전역 상태 라이브러리인 zustand, react-query를 세팅한다.
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/NewChecklist/ChecklistCategory.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion_UI.test.tsx
  frontend/src/components/common/Toast/ToastContext.tsx
  frontend/src/hooks/useChecklistAnswer.ts
  frontend/src/pages/NewChecklistPage/NewChecklistBody.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistPage.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistTemplate.tsx
  frontend/src/store/useChecklist.test.ts
  frontend/src/store/useChecklist.ts
  frontend/yarn.lock
Labels: 🔑 FE, ⚙ Chore, 🔧 Refactor

#180 토스트를 zustand를 사용한 전역 변수로 리팩토링 후 테스트를 작성한다.
  frontend/.storybook/preview-body.html
  frontend/index.html
  frontend/src/App.tsx
  frontend/src/components/common/Tabs/Tab.tsx
  frontend/src/components/common/Tabs/Tabs.tsx
  frontend/src/components/common/Toast/Toast.stories.tsx
  frontend/src/components/common/Toast/Toast.tsx
  frontend/src/components/common/Toast/ToastContext.tsx
  frontend/src/hooks/useToast.test.tsx
  frontend/src/hooks/useToast.ts
  frontend/src/pages/CategoryChoosePage.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistBody.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistInfoTemplate.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistPage.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistTemplate.tsx
  frontend/src/store/useChecklist.test.tsx
  frontend/src/store/useToastState.ts
  frontend/src/styles/theme.ts
Labels: 🔑 FE, 🔧 Refactor, 🧪 Test

#186 [FE] 체크리스트 기본정보 작성페이지를 업데이트한다
  frontend/src/components/common/FormField/FormField.tsx
  frontend/src/components/common/Input/Input.tsx
  frontend/src/components/common/RadioGroup/RadioContext.ts
  frontend/src/components/common/RadioGroup/RadioGroup.stories.tsx
  frontend/src/components/common/RadioGroup/RadioGroup.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistInfoTemplate.tsx
  frontend/src/styles/reset.ts
Labels: 🔑 FE, 😊 Feature, 🎨 UI
