Repository woowacourse-teams/2024-bang-ggood, pull requests merged in 2024-09, with the labels that each got.

#564 [FE] 지도의 에러를 고치고, 링크 기능을 추가한다.
  frontend/src/assets/icons/map/kakaomap.webp
  frontend/src/assets/icons/map/navermap.webp
  frontend/src/components/ChecklistList/NoChecklistTemplate.tsx
  frontend/src/components/_common/LoadingSpinner/LoadingSpinner.tsx
  frontend/src/components/_common/Map/AddressMap.tsx
  frontend/src/components/_common/Map/RealTimeMap.tsx
  frontend/src/index.css
  frontend/src/types/svg.d.ts
  frontend/src/utils/makeMap.ts
  frontend/webpack.config.js
Labels: 🔑 FE, 😊 Feature, 🔧 Refactor

#568 [FE] 폼 입력시 모든 인풋 컴포넌트가 재랜더되는 것을 막는다.
  frontend/src/components/NewChecklist/SummaryModal/SummaryModal.tsx
  frontend/src/hooks/useMutateChecklist.ts
  frontend/src/pages/EditChecklistPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/types/checklist.ts
Labels: 🐛 Bug, 🔑 FE, 🔧 Refactor

#571 [FE] 페이지의 행간, 자간 레이아웃을 변경한다.
  frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
  frontend/src/pages/ArticleDetailPage.tsx
Labels: 🔑 FE, 🔧 Refactor, 🎨 UI

#569 [BE] 테스트 패키지 구조를 변경한다.
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/OptionTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/contract/domain/OccupancyMonthTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/contract/domain/OccupancyPeriodTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/maintenance/domain/MaintenanceItemTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/maintenance/repository/ChecklistMaintenanceRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/option/domain/OptionTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/option/repository/ChecklistOptionRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/CustomChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/domain/ChecklistQuestionTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/domain/QuestionTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/ChecklistQuestionRepositoryTest.java
Labels: 🔒 BE, ⚙ Chore

#573 [BE] 체크리스트 작성 API를 리팩토링한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Checklist.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/logging/LoggingAspect.java
  backend/bang-ggood/src/main/java/com/bang_ggood/like/repository/ChecklistLikeRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/maintenance/repository/ChecklistMaintenanceRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/maintenance/service/ChecklistMaintenanceService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/option/repository/ChecklistOptionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/option/service/ChecklistOptionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/ChecklistQuestion.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/ChecklistQuestionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/response/SelectedRoomResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/service/RoomService.java
  backend/bang-ggood/src/main/resources/data.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/maintenance/ChecklistMaintenanceFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/maintenance/repository/ChecklistMaintenanceRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/maintenance/service/ChecklistMaintenanceServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/option/ChecklistOptionFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/option/repository/ChecklistOptionRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/option/service/ChecklistOptionServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/ChecklistQuestionFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/ChecklistQuestionRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/ChecklistQuestionServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/service/RoomServiceTest.java
Labels: 🔒 BE, 🔧 Refactor

#580 [BE] 커스텀 체크리스트 서비스를 분리한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/controller/QuestionController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CategoryCustomChecklistQuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CategoryCustomChecklistQuestionsResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/ChecklistQuestionsResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CustomChecklistQuestionsResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/CustomChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/controller/QuestionE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/ChecklistQuestionServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/QuestionManageServiceTest.java
Labels: 🔒 BE, 🔧 Refactor

#582 [BE] 체크리스트 조회 API를 수정한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/SelectedChecklistResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/maintenance/service/ChecklistMaintenanceService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/option/domain/Option.java
  backend/bang-ggood/src/main/java/com/bang_ggood/option/dto/response/SelectedOptionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/option/service/ChecklistOptionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/Question.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
Labels: 🔒 BE, 🔧 Refactor

#579 [FE] 새 체크리스트 부분적 에러 수정 및 수정사항을 모두 반영한다.
  frontend/src/App.tsx
  frontend/src/components/Answer/AnswerIcon.tsx
  frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
  frontend/src/components/NewChecklist/AddressModal/RealTimeAddressModal.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomFloor.tsx
  frontend/src/components/NewChecklist/Option/OptionAllSelectBox.tsx
  frontend/src/components/NewChecklist/Option/OptionButton/OptionButton.tsx
  frontend/src/components/NewChecklist/SummaryModal/SummaryModal.tsx
  frontend/src/components/_common/Dropdown/Dropdown.tsx
  frontend/src/constants/system.ts
  frontend/src/hooks/useChecklistAnswer.test.ts
  frontend/src/hooks/useInitialChecklist.ts
  frontend/src/hooks/useModalOpen.ts
  frontend/src/mocks/handlers/checklist.ts
  frontend/src/pages/ChecklistDetailPage.tsx
  frontend/src/pages/EditChecklistPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/src/store/useChecklistStore.ts
  frontend/src/store/useOptionStore.ts
Labels: 🐛 Bug, 🔑 FE, 😊 Feature, 🔧 Refactor

#583 [FE] 질문 개행 오류를 수정하고 포인터 커서를 적용한다.
  frontend/src/components/ArticleList/ArticleCard.tsx
  frontend/src/components/ChecklistList/ChecklistCard.tsx
  frontend/src/components/ChecklistList/CustomBanner.tsx
  frontend/src/components/Landing/style.ts
  frontend/src/components/Main/ArticlePreviewCard.tsx
  frontend/src/components/Main/ArticleSection.tsx
  frontend/src/components/Main/ChecklistPreviewCard.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/NewChecklist/Option/OptionButton/OptionButton.tsx
  frontend/src/components/_common/Accordion/AccordionHeader.tsx
  frontend/src/components/_common/Dropdown/Dropdown.tsx
  frontend/src/components/_common/Highlight/HighlightText.tsx
  frontend/src/components/_common/Modal/AlertModal/AlertModal.tsx
  frontend/src/mocks/handlers/checklist.ts
  frontend/src/pages/ChecklistDetailPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/routers/router.tsx
Labels: 🔑 FE, 🔧 Refactor, 🎨 UI

#586 [FE] 주소 찾기와 지하철 찾기 기능을 연결하고 관련 버그를 고친다.
  frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
  frontend/src/components/NewChecklist/AddressModal/RealTimeAddressModal.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/Address.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/NearTransportation.tsx
  frontend/src/components/_common/Button/Button.tsx
  frontend/src/components/_common/FlexBox/FlexBox.tsx
  frontend/src/components/_common/FormField/FormField.tsx
  frontend/src/components/_common/Map/RealTimeMap.tsx
  frontend/src/hooks/useFindNearSubway.ts
  frontend/src/hooks/useModal.ts
  frontend/src/hooks/useMutateChecklist.ts
  frontend/src/pages/ChecklistDetailPage.tsx
  frontend/src/pages/EditChecklistPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/routers/router.tsx
  frontend/src/store/checklistAddressStore.ts
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/src/styles/global.ts
  frontend/src/utils/validation.ts
Labels: 🐛 Bug, 🔑 FE, 🔧 Refactor

#592 [BE] 테스트 Fixture에 id가 고정되는 문제를 해결한다.
  backend/bang-ggood/src/test/java/com/bang_ggood/AcceptanceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/ArticleFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/repository/ArticleRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/JwtTokenProviderTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/ChecklistTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/maintenance/ChecklistMaintenanceFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/maintenance/repository/ChecklistMaintenanceRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/maintenance/service/ChecklistMaintenanceServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/option/ChecklistOptionFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/option/repository/ChecklistOptionRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/option/service/ChecklistOptionServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/ChecklistQuestionFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/CustomChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/controller/QuestionE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/domain/ChecklistQuestionTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/ChecklistQuestionRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/ChecklistQuestionServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/QuestionManageServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/RoomFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/repository/RoomRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/service/RoomServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/UserFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/controller/UserE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/repository/UserRepositoryTest.java
Labels: 🐛 Bug, 🔒 BE, 🧪 Test

#594 [FE] roomInfoStore에서 인자를 응집성있게 받아 사용한다
  frontend/src/components/NewChecklist/NewRoomInfoForm/IncludedMaintenances.tsx
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/src/store/createFormStore.ts
  frontend/webpack.config.js
Labels: 🔑 FE, ⚙ Chore, 🔧 Refactor

#596 [FE] 환경 변수를 분리하고 모드를 스크립트 명령어로 쓸 수 있도록 수정한다.
  frontend/.gitignore
  frontend/package.json
  frontend/src/apis/config.ts
  frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/NearTransportation.tsx
  frontend/src/constants/oAuth.ts
  frontend/src/index.tsx
  frontend/src/mocks/fixtures/subway.ts
  frontend/src/mocks/handlers/subway.ts
  frontend/src/routers/router.tsx
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 🔑 FE, ⚙ Chore, 🔧 Refactor

#597 [FE] 편집 페이지의 버그들을 수정하고 리팩토링한다.
  frontend/src/components/NewChecklist/NewRoomInfoForm/IncludedMaintenances.tsx
  frontend/src/components/NewChecklist/SubmitModalWithSummary/SubmitModalWithSummary.tsx
  frontend/src/constants/message.ts
  frontend/src/constants/system.ts
  frontend/src/hooks/useMutateChecklist.ts
  frontend/src/pages/CategoryChoosePage.tsx
  frontend/src/pages/EditChecklistPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/store/checklistIncludedMaintenancesStore.ts
Labels: 🐛 Bug, 🔑 FE

#600 [FE] 개발의존성은 devDependency로 옮긴다. 라우터단에만 우선 React.lazy 적용한다.
  frontend/package.json
  frontend/src/components/NewChecklist/NewRoomInfoForm/styled.tsx
  frontend/src/routers/router.tsx
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 🔑 FE, ⚙ Chore, 🔧 Refactor

#604 [FE] 주소 관련 외부 스크립트 사용처에서 불러오도록 리팩토링한다.
  frontend/public/index.html
  frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
  frontend/src/components/NewChecklist/AddressModal/RealTimeAddressModal.tsx
  frontend/src/components/_common/Map/AddressMap.tsx
  frontend/src/components/_common/Map/RealTimeMap.tsx
  frontend/src/index.css
  frontend/src/utils/createKakaoMapElements.ts
  frontend/src/utils/loadScript.ts
  frontend/src/utils/makeMap.ts
Labels: 🔑 FE, 🔧 Refactor

#605 [FE] 메모 커서가 앞으로가는 버그를 수정한다.
  frontend/src/components/NewChecklist/MemoModal/MemoModal.tsx
  frontend/src/components/_common/Textarea/Textarea.tsx
Labels: 🐛 Bug, 🔑 FE

#608 [FE] 관리비 포함 항목 스토어를 기존 스토어와 병합 및 스토어 리팩토링을 진행한다.
  frontend/src/components/NewChecklist/NewChecklistInfoTemplate.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/IncludedMaintenances.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/MaintenanceFee.tsx
  frontend/src/hooks/useMutateChecklist.ts
  frontend/src/pages/EditChecklistPage.tsx
  frontend/src/store/checklistIncludedMaintenancesStore.ts
  frontend/src/store/checklistRoomInfoStore.test.ts
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/src/store/createFormStore.ts
Labels: 🔑 FE, 🔧 Refactor, 🧪 Test

#611 [BE] Repository 메서드 타입 Long으로 변경
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
Labels: 🐛 Bug, 🔒 BE

#607 [BE] 체크리스트 좋아요 서비스 구조를 분리한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistPreviewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistsPreviewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/UserChecklistsPreviewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/like/controller/ChecklistLikeController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/like/repository/ChecklistLikeRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/like/service/ChecklistLikeManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/like/service/ChecklistLikeService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/like/controller/ChecklistLikeE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/like/service/ChecklistLikeManageServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/like/service/ChecklistLikeServiceTest.java
Labels: 🔒 BE, 🔧 Refactor

#616 [FE] 옵션, 주소 검색 등의 UI 를 변경하고 옵션 버튼의 렌더링을 최적화한다.
  frontend/src/assets/assets.tsx
  frontend/src/assets/icons/map/location.svg
  frontend/src/assets/icons/map/search.svg
  frontend/src/assets/icons/plusMinus/plus-white.svg
  frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
  frontend/src/components/NewChecklist/AddressModal/RealTimeAddressModal.tsx
  frontend/src/components/NewChecklist/MemoModal/MemoButton.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/NearTransportation.tsx
  frontend/src/components/NewChecklist/Option/OptionAllSelectBox.tsx
  frontend/src/components/NewChecklist/Option/OptionButton/OptionButton.stories.tsx
  frontend/src/components/NewChecklist/Option/OptionButton/OptionButton.tsx
  frontend/src/components/NewChecklist/Option/OptionList.tsx
  frontend/src/components/_common/Button/Button.tsx
  frontend/src/components/_common/Checkbox/Checkbox.tsx
  frontend/src/components/_common/FormField/FormField.tsx
  frontend/src/components/_common/Map/RealTimeMap.tsx
  frontend/src/components/_common/Modal/AlertModal/AlertModal.tsx
  frontend/src/components/_common/Modal/Modal.tsx
  frontend/src/hooks/useMutateChecklist.ts
  frontend/src/pages/EditChecklistPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/store/createFormStore.ts
  frontend/src/store/useSelectedOptionStore.ts
  frontend/src/styles/global.ts
  frontend/src/utils/createKakaoMapElements.ts
Labels: 🔑 FE, 🎨 UI

#624 [FE] 성능 개선을 위한 이미지 최적화를 진행한다.
  frontend/public/image/checkScreenShot.png
  frontend/public/image/customScreenShot.png
  frontend/public/image/home.png
  frontend/public/image/mainScreenShot.png
  frontend/public/image/outdoor.png
  frontend/public/image/security.png
  frontend/public/image/toilet.png
  frontend/public/image/window.png
  frontend/src/assets/images/category-icon-sprite.png
  frontend/src/assets/images/checkingPageScreen.webp
  frontend/src/assets/images/customPageScreen.webp
  frontend/src/assets/images/mainPageScreen.webp
  frontend/src/components/ChecklistCustom/CustomTabs.tsx
  frontend/src/components/Landing/FourthSection.tsx
  frontend/src/components/Landing/SecondSection.tsx
  frontend/src/components/Landing/ThirdSection.tsx
  frontend/src/components/_common/Tabs/Tab.tsx
  frontend/src/components/_common/Tabs/Tabs.tsx
  frontend/src/constants/category.ts
  frontend/src/hooks/useNewChecklistTabs.ts
  frontend/src/pages/LandingPage.tsx
  frontend/src/styles/category-sprite-image.css
  frontend/src/types/image.d.ts
Labels: 🔑 FE, 🔧 Refactor

#626 [FE] 성능 개선을 위한 이미지 최적화 추가 작업을 진행한다.
  frontend/src/assets/assets.tsx
  frontend/src/assets/images/category-sprite.webp
  frontend/src/components/Landing/FourthSection.tsx
  frontend/src/components/Landing/SecondSection.tsx
  frontend/src/components/Landing/ThirdSection.tsx
  frontend/src/components/_common/Tabs/Tab.tsx
  frontend/src/styles/category-sprite-image.css
Labels: 🔑 FE, 🔧 Refactor

#635 [FE] 토스트 에러 메세지에 UX 라이팅을 접목하여 리팩토링한다.
  frontend/src/apis/fetcher.ts
  frontend/src/constants/httpErrorMessage.ts
  frontend/src/constants/message.ts
  frontend/src/pages/ChecklistCustomPage.tsx
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/routers/router.tsx
Labels: 🔑 FE, 🔧 Refactor

#575 [BE] 가까운 지하철 역을 2개 보여준다.
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/controller/SubwayStationController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/domain/SubwayStation.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/dto/SubwayStationResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/station/SubwayStationServiceTest.java
Labels: 🔒 BE, 😊 Feature

#637 [FE] 커스텀 질문 페이지에서 0개 선택 후 저장시 생기는 버그를 수정한다.
  frontend/src/constants/message.ts
  frontend/src/constants/system.ts
  frontend/src/hooks/query/usePutCustomChecklist.ts
  frontend/src/mocks/handlers/checklist.ts
  frontend/src/pages/ChecklistCustomPage.tsx
Labels: 🐛 Bug, 🔑 FE, 😊 Feature

#612 [BE] 아티클에 대표이미지를 추가한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/domain/Article.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/request/ArticleCreateRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticleCardViewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticleDetailPreviewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticleListViewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticlePreviewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticlesCardViewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticlesDetailPreviewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticlesListViewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticlesPreviewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/repository/ArticleRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
  backend/bang-ggood/src/main/resources/data.sql
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/article/ArticleFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/repository/ArticleRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE, 😊 Feature

#638 [FE] 편집페이지의 기능이 모두 정상 동작하게 만든다
  frontend/src/components/ChecklistDetail/CategoryAccordion.tsx
  frontend/src/components/ChecklistDetail/CheckListAnswer.tsx
  frontend/src/components/ChecklistDetail/ChecklistAnswerSection.tsx
  frontend/src/components/NewChecklist/NewChecklistTemplate.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/OccupancyMonth.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomFloor.tsx
  frontend/src/constants/roomInfo.ts
  frontend/src/hooks/query/useGetChecklistQuestionQuery.ts
  frontend/src/hooks/useChecklistAnswer.test.ts
  frontend/src/hooks/useChecklistAnswer.ts
  frontend/src/hooks/useInitialChecklist.ts
  frontend/src/hooks/useMutateChecklist.ts
  frontend/src/hooks/useNewChecklistTabs.ts
  frontend/src/mocks/fixtures/checklistDetail.ts
  frontend/src/mocks/fixtures/checklistQuestions.ts
  frontend/src/pages/ChecklistDetailPage.tsx
  frontend/src/pages/EditChecklistPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/src/store/useChecklistCustomStore.ts
  frontend/src/store/useChecklistStore.ts
  frontend/src/types/checklist.ts
  frontend/src/types/room.ts
  frontend/webpack.config.js
Labels: 🐛 Bug, 🔑 FE, 😊 Feature

#620 [BE] 새로운 질문을 추가한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/Question.java
Labels: 🔒 BE, 😊 Feature

#618 [BE] 체크리스트 리스트 조회 API를 리팩토링한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistsPreviewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/like/service/ChecklistLikeService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
Labels: 🔒 BE, 🔧 Refactor

#645 [BE] load balancer를 위한 health-check controller를 생성한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/global/controller/HealthCheckController.java
  backend/bang-ggood/src/main/resources/data.sql
Labels: 🔒 BE, 😊 Feature, 🌏 Infra

#648 [BE] Mysql 문법에 맞게 sql을 고친다.
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🐛 Bug, 🔒 BE

#639 [FE] 폰트를 최적화하는 코드를 추가한다.
  frontend/public/index.html
  frontend/src/components/NewChecklist/Option/OptionButton/OptionButton.tsx
  frontend/src/components/NewChecklist/Option/OptionList.tsx
Labels: 🔑 FE, 🔧 Refactor

#625 [BE] 로그인하지 않은 사용자도 특정 페이지에 접근할 수 있도록 권한을 허용한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AuthRequiredPrincipal.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AuthRequiredPrincipalArgumentResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/CookieResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/UserPrincipal.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/UserPrincipalArgumentResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/OauthInfoApiResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/JwtTokenProvider.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/DBInitializer.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/DefaultChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/WebMvcConfig.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/like/controller/ChecklistLikeController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/controller/QuestionController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/controller/UserController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/User.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/UserType.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/service/UserService.java
  backend/bang-ggood/src/main/resources/data.sql
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/AcceptanceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/ArgumentResolverTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/CookieResolverTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/TestController.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/controller/QuestionE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/UserFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/repository/UserRepositoryTest.java
  backend/bang-ggood/src/test/resources/data-test.sql
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE, 😊 Feature

#658 [BE] prod cd 스크립트를 변경한다.
  .github/workflows/backend-prod-cd.yml
Labels: 🔒 BE, 🌏 Infra

#650 [FE] 불필요한 모듈을 번들에 포함시키지 않는다
  frontend/package.json
  frontend/public/index.html
  frontend/src/assets/fonts/SUITE-Variable.woff2
  frontend/src/index.css
  frontend/src/pages/ArticleDetailPage.tsx
  frontend/webpack.common.js
  frontend/webpack.prod.js
Labels: 🔑 FE, ⚙ Chore, 🔧 Refactor

#631 [BE] 체크리스트 수정 API를 리팩토링한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/maintenance/service/ChecklistMaintenanceService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/option/service/ChecklistOptionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CategoryCustomChecklistQuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CategoryCustomChecklistQuestionsResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/service/RoomService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/maintenance/ChecklistMaintenanceFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/maintenance/service/ChecklistMaintenanceServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/option/ChecklistOptionFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/option/service/ChecklistOptionServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/ChecklistQuestionFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/ChecklistQuestionServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/RoomFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/service/RoomServiceTest.java
Labels: 🔒 BE, 🔧 Refactor

#664 [BE] dev-be 브랜치와 dev를 머지한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AuthRequiredPrincipal.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AuthRequiredPrincipalArgumentResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/CookieResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/UserPrincipal.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/UserPrincipalArgumentResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/OauthInfoApiResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/DBInitializer.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/DefaultChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/WebMvcConfig.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/like/controller/ChecklistLikeController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/maintenance/service/ChecklistMaintenanceService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/option/service/ChecklistOptionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/controller/QuestionController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CategoryCustomChecklistQuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CategoryCustomChecklistQuestionsResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/service/RoomService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/controller/UserController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/User.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/UserType.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/service/UserService.java
  backend/bang-ggood/src/main/resources/data.sql
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/AcceptanceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/ArgumentResolverTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/CookieResolverTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/TestController.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/maintenance/ChecklistMaintenanceFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/maintenance/service/ChecklistMaintenanceServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/option/ChecklistOptionFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/option/service/ChecklistOptionServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/ChecklistQuestionFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/controller/QuestionE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/ChecklistQuestionServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/RoomFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/service/RoomServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/UserFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/repository/UserRepositoryTest.java
  backend/bang-ggood/src/test/resources/data-test.sql
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE

#651 [FE] 지하철 노선을 업데이트하여 보여주고 roomInfonValidatedStore를 만들어 적용한다.
  frontend/.storybook/preview.tsx
  frontend/src/components/Landing/style.ts
  frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
  frontend/src/components/NewChecklist/AddressModal/RealTimeAddressModal.tsx
  frontend/src/components/NewChecklist/MemoModal/MemoModal.tsx
  frontend/src/components/NewChecklist/NewChecklistFormField.tsx
  frontend/src/components/NewChecklist/NewChecklistInfoTemplate.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/Address.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/DepositAndRent.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/IncludedMaintenances.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/MaintenanceFee.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/NearSubwayStations.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/NearTransportation.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/OccupancyMonth.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RealEstate.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomContractTerm.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomFloor.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomName.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomSize.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomStructure.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/useDefaultRoomName.ts
  frontend/src/components/NewChecklist/SubmitModalWithSummary/SubmitModalWithSummary.tsx
  frontend/src/components/_common/FormField/FormField.tsx
  frontend/src/components/_common/LoadingSpinner/LoadingSpinner.tsx
  frontend/src/components/_common/Map/AddressMap.tsx
  frontend/src/components/_common/Map/RealTimeMap.tsx
  frontend/src/components/_common/Modal/AlertModal/AlertModal.tsx
  frontend/src/components/_common/SubwayStation/NearSubwayStationItem.tsx
  frontend/src/components/_common/SubwayStation/SubwayLineIcon/SubwayLineIcon.stories.tsx
  frontend/src/components/_common/SubwayStation/SubwayLineIcon/SubwayLineIcon.tsx
  frontend/src/components/_common/Tabs/Tab.tsx
  frontend/src/components/_common/TopButton/TopButton.tsx
  frontend/src/hooks/useFindNearSubway.ts
  frontend/src/hooks/useMutateChecklist.ts
  frontend/src/hooks/useRoomInfoUnvalidatedStore.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/src/store/roomInfoUnvalidatedStore.ts
  frontend/src/styles/reset.ts
  frontend/src/styles/subway.ts
  frontend/src/types/subway.ts
Labels: 🔑 FE, 🔧 Refactor, 🎨 UI

#666 [BE] 아티클 응답을 수정한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticleCardViewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticleListViewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticleResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticlesCardViewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticlesListViewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticlesResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticlesResponses.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/repository/ArticleRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/repository/ArticleRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
Labels: 🔒 BE, 🔧 Refactor

#640 [BE] 체크리스트 삭제 API를 리팩토링한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/maintenance/service/ChecklistMaintenanceService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/option/service/ChecklistOptionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/ChecklistQuestionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/service/RoomService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/maintenance/service/ChecklistMaintenanceServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/option/service/ChecklistOptionServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/ChecklistQuestionServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/service/RoomServiceTest.java
Labels: 🔒 BE, 🔧 Refactor

#653 [BE] 체크리스트 조회시 좋아요 여부를 전달하도록 수정한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
Labels: 🔒 BE, 🔧 Refactor

#662 [BE] 지하철 데이터를 업데이트한다
  backend/bang-ggood/src/main/java/com/bang_ggood/station/SubwayReader.java
  backend/bang-ggood/src/main/resources/seoul_stations_240925.csv
  backend/bang-ggood/src/test/java/com/bang_ggood/station/SubwayStationServiceTest.java
  backend/bang-ggood/src/test/resources/seoul_stations_240925.csv
Labels: 🔒 BE, 😊 Feature

#660 [FE] 아티클 대표 이미지 요소를 추가한다.
  frontend/src/components/_common/Header/Header.stories.tsx
  frontend/src/components/_common/Header/Header.tsx
  frontend/src/components/skeleton/Article/SKArticleDetail.tsx
  frontend/src/components/skeleton/Article/SkArticleList.tsx
  frontend/src/mocks/fixtures/article.ts
  frontend/src/pages/ArticleDetailPage.tsx
  frontend/src/types/article.ts
Labels: 🔑 FE, 😊 Feature, 🧪 Test

#670 [FE] 폰트 폴더경로변경 한군데 빠졌던 것 반영한다
  frontend/src/index.css
Labels: 🐛 Bug, 🔑 FE

#654 [BE] 리프레시 토큰 기능을 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AuthRequiredPrincipalArgumentResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/CookieResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/UserPrincipalArgumentResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/CookieProvider.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/CookieResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/AuthTokenResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/OauthTokenApiResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/OauthTokenResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/JwtTokenProperties.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/JwtTokenProvider.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/OauthClient.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/TokenType.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/WebMvcConfig.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
  backend/bang-ggood/src/test/java/com/bang_ggood/AcceptanceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/JwtTokenProviderFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/ArgumentResolverTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/CookieResolverTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/CookieResolverTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/LoginMockE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/JwtTokenProviderTest.java
Labels: 🔒 BE, 😊 Feature

#673 [BE] dev와 dev-be 브랜치를 병합한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AuthRequiredPrincipalArgumentResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/CookieResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/UserPrincipalArgumentResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/CookieProvider.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/CookieResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/AuthTokenResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/OauthTokenApiResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/OauthTokenResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/JwtTokenProperties.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/JwtTokenProvider.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/OauthClient.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/TokenType.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/WebMvcConfig.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
  backend/bang-ggood/src/test/java/com/bang_ggood/AcceptanceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/JwtTokenProviderFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/ArgumentResolverTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/CookieResolverTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/CookieResolverTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/LoginMockE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/JwtTokenProviderTest.java
Labels: 🔒 BE

#676 [BE] read/write 관련 ci/cd 스크립트를 수정한다.
  .github/workflows/backend-ci.yml
  .github/workflows/backend-dev-cd.yml
  .github/workflows/backend-prod-cd.yml
Labels: 🔒 BE, 🌏 Infra

#674 [BE] read/write db 분리
  backend/bang-ggood/.gitignore
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/datasource/DataSourceConfig.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/datasource/DataSourceRouter.java
  backend/bang-ggood/src/test/java/com/bang_ggood/global/datasource/DataSourceTest.java
Labels: 🔒 BE, 🌏 Infra

#681 [BE] respository id 타입을 long에서 Long으로 바꾼다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistRepositoryTest.java
Labels: 🐛 Bug, 🔒 BE, 😊 Feature

#682 [BE] dev와 dev-be를 합친다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistRepositoryTest.java
Labels: 🔒 BE

#683 [BE] prod로 배포를 진행한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistRepositoryTest.java
Labels: 🔒 BE, 🌏 Infra

#679 [FE] 지하철 format 이 바뀌기 전, 편집 페이지에서 unValidatedStore 를 쓰도록 작업을 한다.
  frontend/src/components/Answer/AnswerIcon.tsx
  frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
  frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/NewChecklist/NewChecklistTemplate.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/NearSubwayStations.tsx
  frontend/src/components/_common/Highlight/HighlightText.tsx
  frontend/src/components/_common/Subway/SubwayLineIcon/SubwayLineIcon.stories.tsx
  frontend/src/components/_common/Subway/SubwayLineIcon/SubwayLineIcon.tsx
  frontend/src/components/_common/Subway/SubwayStationItem.tsx
  frontend/src/components/_common/Subway/SubwayStations.tsx
  frontend/src/hooks/useRoomInfoUnvalidatedStore.ts
  frontend/src/mocks/fixtures/subway.ts
  frontend/src/pages/ChecklistDetailPage.tsx
  frontend/src/pages/EditChecklistPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
Labels: 🔑 FE, 😊 Feature

#686 [BE] checklistQuestion dirty checking가 안 되는 문제를 해결한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/ChecklistQuestion.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/ChecklistQuestionServiceTest.java
Labels: 🐛 Bug, 🔒 BE, 😊 Feature

#689 [FE] 체크리스트 렌더링 성능을 최적화한다.
  frontend/src/components/Answer/AnswerIcon.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestionAnswers.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomName.tsx
  frontend/src/components/_common/Highlight/HighlightText.tsx
  frontend/src/components/_common/Tabs/Tab.tsx
  frontend/src/components/_common/Tabs/Tabs.tsx
  frontend/src/hooks/useChecklistAnswer.ts
  frontend/src/hooks/useInitialChecklist.ts
Labels: 🔑 FE, 🔧 Refactor

#695 [FE] 입주가능월이 0이라서 발생하는 요청에러를 해결한다.
  frontend/src/store/checklistRoomInfoStore.ts
Labels: 🐛 Bug, 🔑 FE

#700 [FE] 방구조 버그를 해결한다.
  frontend/src/hooks/useMutateChecklist.ts
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/src/styles/reset.ts
  frontend/src/types/room.ts
Labels: 🐛 Bug, 🔑 FE

#706 [FE] 비회원이 체크리스트 작성 이후 로그인을 진행시, 로그인 성공 이후 작성된 체크리스트 자동 저장되게 한다.
  frontend/src/hooks/useLogin.ts
  frontend/src/pages/LoginPage.tsx
  frontend/src/routers/router.tsx
Labels: 🔑 FE
