Repository woowacourse-teams/2024-bang-ggood, pull requests merged in 2024-08, with the labels that each got.

#187 [FE] 방 비교 페이지 옵션 모달 추가 및 카테고리 점수 리스트 기능을 수정한다.
  frontend/src/apis/checklist.ts
  frontend/src/apis/url.ts
  frontend/src/assets/assets.tsx
  frontend/src/assets/icons/delete.svg
  frontend/src/components/ChecklistList/ChecklistPreviewCard.stories.tsx
  frontend/src/components/RoomCompare/CompareCard.tsx
  frontend/src/components/common/Button/FloatingButton.tsx
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/mocks/fixtures/checklistList.ts
  frontend/src/mocks/fixtures/roomsForCompare.ts
  frontend/src/mocks/handlers/category.ts
  frontend/src/mocks/handlers/checklist.ts
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/RoomComparePage.tsx
  frontend/src/types/category.ts
  frontend/src/types/checklist.ts
  frontend/src/types/room.ts
  frontend/src/utils/calcEmotions.ts
Labels: 🐛 Bug, 🔑 FE, 😊 Feature

#189 [BE] 체크리스트 방 정보 작성 API에 기능을 추가 구현한다
  backend/bang-ggood/src/main/java/com/bang_ggood/BaseEntity.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/controller/CategoryController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Badge.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/WrittenCategoryQuestionsResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/service/CategoryService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Checklist.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/ChecklistQuestion.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/ChecklistScore.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Question.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/request/QuestionCreateRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistWithScoreReadResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/UserChecklistPreviewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/UserChecklistsPreviewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistQuestionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/config/CorsConfig.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/GlobalExceptionHandler.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/domain/FloorLevel.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/domain/Room.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/domain/Structure.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/domain/Type.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/request/RoomCreateRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/User.java
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/JpaAuditingTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/category/domain/CategoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/category/service/CategoryServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/OptionTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/QuestionTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/option/OptionTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/RoomFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/domain/FloorLevelTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/domain/RoomTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/domain/StructureTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/domain/TypeTest.java
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE, 😊 Feature

#194 [FE] 수정된 api 타입을 적용하기 위해 체크리스트 내부의 타입을 수정하고 적용하고 전역 상태를 활용해 리팩토링한다.
  frontend/src/components/NewChecklist/CheckListAnswer.tsx
  frontend/src/components/NewChecklist/ChecklistCategory.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion_UI.test.tsx
  frontend/src/components/NewChecklist/OptionModal/OptionModal.tsx
  frontend/src/components/NewChecklist/OptionModal/OptionModalInfoBox.tsx
  frontend/src/components/common/FaceMark/FaceIcon.tsx
  frontend/src/components/common/FormField/FormField.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/OptionButton/OptionButton.stories.tsx
  frontend/src/components/common/OptionButton/OptionButton.tsx
  frontend/src/components/common/OptionButton/OptionIcon.tsx
  frontend/src/components/common/Tabs/Tab.tsx
  frontend/src/components/common/Tabs/Tabs.tsx
  frontend/src/components/common/Toast/ToastContext.tsx
  frontend/src/hooks/useAllSelect.ts
  frontend/src/hooks/useToast.ts
  frontend/src/pages/CategoryChoosePage.tsx
  frontend/src/pages/ChecklistSummaryPage.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistBody.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistInfoTemplate.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistPage.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistTab.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistTemplate.tsx
  frontend/src/store/useChecklist.test.tsx
  frontend/src/store/useChecklist.ts
  frontend/src/store/useChecklistStore.test.tsx
  frontend/src/store/useChecklistStore.ts
  frontend/src/store/useOptionStore.ts
  frontend/src/store/useToastStore.ts
  frontend/src/styles/theme.ts
  frontend/src/types/checklist.ts
  frontend/src/types/emotionAnswer.ts
  frontend/src/types/room.ts
Labels: 🔑 FE, ⚙ Chore, 🔧 Refactor

#192 [BE] 체크리스트 조회 API에 기능을 추가 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/CategoryQuestionsResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/WrittenCategoryQuestionsResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/response/SelectedCategoryQuestionsResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/response/WrittenCategoryQuestionsResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/ChecklistQuestion.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Option.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/SelectedChecklistResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/SelectedOptionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/SelectedQuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/WrittenChecklistResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/WrittenQuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/domain/FloorLevel.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/domain/Structure.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/domain/Type.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/response/SelectedRoomResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/response/WrittenRoomResponse.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/option/OptionTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/RoomFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/domain/FloorLevelTest.java
Labels: 🔒 BE, 😊 Feature

#191 [BE] 커스텀 체크리스트 수정 기능을 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/BaseEntity.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/CustomChecklistQuestion.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/request/CustomChecklistUpdateRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/CustomChecklistQuestionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/User.java
  backend/bang-ggood/src/main/resources/data.sql
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/CustomChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
  backend/bang-ggood/src/test/resources/data-test.sql
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE, 😊 Feature

#198 [BE] 카카오 서버로부터 사용자 정보를 가져온다.
  backend/bang-ggood/src/main/java/com/bang_ggood/config/OauthClientConfig.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/OauthException.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/dto/ExceptionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/dto/OauthExceptionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/handler/GlobalExceptionHandler.java
  backend/bang-ggood/src/main/java/com/bang_ggood/handler/OauthClientExceptionHandler.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/controller/UserController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/dto/request/OauthLoginRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/dto/request/OauthTokenRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/dto/response/KakaoAccountResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/dto/response/OauthInfoResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/dto/response/OauthTokenResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/dto/response/ProfileResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/service/OauthClient.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/service/UserService.java
Labels: 🔒 BE, 😊 Feature

#206 [FE] 폰트 디자인을 설정한다.
  frontend/src/assets/fonts/SUIT-Bold.woff2
  frontend/src/assets/fonts/SUIT-Regular.woff2
  frontend/src/styles/font.ts
  frontend/src/styles/global.ts
  frontend/webpack.config.js
Labels: 🔑 FE, 🎨 UI

#210 [FE] 질문별 메모 기능을 추가하고 유효한 탭만 보여주도록 리팩토링한다.
  frontend/src/assets/assets.tsx
  frontend/src/assets/icons/memo-empty.svg
  frontend/src/assets/icons/memo-filled.svg
  frontend/src/components/ChecklistDetail/CheckListAnswer.tsx
  frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/QuestionMemo.tsx
  frontend/src/components/NewChecklist/OptionModal/OptionModalInfoBox.tsx
  frontend/src/components/RoomCompare/CompareSelectCard.tsx
  frontend/src/components/common/Accordion/AccodionHeader.tsx
  frontend/src/components/common/Accordion/Accordion.stories.tsx
  frontend/src/components/common/Accordion/Accordion.tsx
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/common/Checkbox/Checkbox.stories.tsx
  frontend/src/components/common/Checkbox/Checkbox.tsx
  frontend/src/components/common/FaceMark/FaceIcon.tsx
  frontend/src/components/common/Modal/ModalHeader.tsx
  frontend/src/components/common/Tabs/TabContext.tsx
  frontend/src/components/common/Textarea/Textarea.tsx
  frontend/src/constants/category.ts
  frontend/src/constants/emotion.ts
  frontend/src/hooks/useChecklistAnswer.test.ts
  frontend/src/hooks/useChecklistAnswer.ts
  frontend/src/hooks/useInput.ts
  frontend/src/hooks/useInputs.ts
  frontend/src/mocks/fixtures/checklistDetail.ts
  frontend/src/mocks/fixtures/checklistQuestions.ts
  frontend/src/pages/NewChecklistPage/NewChecklistBody.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistContent.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistInfoTemplate.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistPage.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistTab.tsx
  frontend/src/pages/NewChecklistPage/NewChecklistTemplate.tsx
  frontend/src/store/useChecklistStore.test.ts
  frontend/src/store/useChecklistStore.ts
  frontend/src/store/useOptionStore.ts
  frontend/src/styles/reset.ts
  frontend/src/types/checklist.ts
  frontend/src/types/emotionAnswer.ts
Labels: 🔑 FE, 😊 Feature, 🔧 Refactor, 🎨 UI

#223 [FE] svgr의 width, height를 바로 사용할수있게 한다
  frontend/.storybook/main.ts
  frontend/webpack.config.js
Labels: 🔑 FE, ⚙ Chore

#221 [FE] 카카오 로그인 페이지를 구현한다.
  frontend/src/apis/login.ts
  frontend/src/apis/url.ts
  frontend/src/assets/assets.tsx
  frontend/src/assets/icons/kakao-logo.svg
  frontend/src/constants/OAuth.ts
  frontend/src/constants/routePath.ts
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/router.tsx
  frontend/src/styles/theme.ts
Labels: 🔑 FE, 😊 Feature, 🎨 UI

#216 [BE] 뱃지 아이디를 추가한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Badge.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/BadgeResponse.java
Labels: 🔒 BE, 😊 Feature

#204 [BE] 체크리스트 삭제 API를 구현한다
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Grade.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/QuestionTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
Labels: 🔒 BE, 😊 Feature

#213 [BE] 체크리스트 수정 API를 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Checklist.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/ChecklistQuestion.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/request/ChecklistRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/request/QuestionCreateRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/request/QuestionRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistOptionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/domain/Room.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/request/RoomRequest.java
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/ChecklistQuestionTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/QuestionTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistOptionRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/RoomFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/UserFixture.java
Labels: 🔒 BE, 😊 Feature

#215 [BE] 방 비교 결과 조회 API에 기능을 추가 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/category/controller/CategoryController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/CategoryQuestionsResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/dto/response/WrittenCategoryQuestionsResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/service/CategoryService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Checklist.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/ChecklistRank.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Grade.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistWithScoreReadResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/UserChecklistPreviewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/WrittenChecklistResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/WrittenQuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/handler/GlobalExceptionHandler.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/response/SelectedRoomResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/response/WrittenRoomResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/service/OauthClient.java
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/ChecklistRankTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/option/OptionTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/UserFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/service/UserServiceTest.java
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE, 😊 Feature

#219 [BE] 체크리스트 조회 API에 기능을 추가 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Checklist.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Question.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/SelectedChecklistResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistOptionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistQuestionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/response/SelectedRoomResponse.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
Labels: 🔒 BE, 😊 Feature

#218 [BE] 인증 로직을 추가한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AuthPrincipal.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AuthPrincipalArgumentResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/CookieProvider.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/request/OauthLoginRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/request/OauthTokenRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/KakaoAccountResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/OauthInfoApiResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/OauthTokenResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/ProfileResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthUser.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/JwtTokenProvider.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/OauthClient.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/controller/CategoryController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/service/CategoryService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistOptionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/config/WebMvcConfig.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/service/UserService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/AcceptanceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/LoginMockE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/JwtTokenProviderTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/category/service/CategoryServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistOptionRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/UserFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/controller/UserE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/repository/UserRepositoryTest.java
Labels: 🔒 BE, 😊 Feature

#236 [BE] API에 인증 로직을 추가한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/BaseEntity.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
Labels: 🔒 BE, 😊 Feature

#238 [BE] 회원가입시 디폴트 체크리스트 질문들을 추가한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Question.java
  backend/bang-ggood/src/test/java/com/bang_ggood/category/service/CategoryServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/repository/UserRepositoryTest.java
Labels: 🔒 BE, 😊 Feature

#232 [FE] 주소 검색 카카오 API 를 연결한다.
  frontend/.eslintrc.json
  frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
  frontend/src/components/NewChecklist/AddressModal/loadPostcode.ts
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/common/Modal/ModalBody.tsx
  frontend/src/types/address.ts
Labels: 🔑 FE, 😊 Feature, 🎨 UI

#231 [FE] FaceIcon, 배너 등 변경된 디자인을 적용하고 일부 공용 컴포넌트를 수정한다.
  frontend/.stylelintrc.json
  frontend/src/apis/checklist.ts
  frontend/src/apis/url.ts
  frontend/src/assets/assets.tsx
  frontend/src/assets/icons/bang-bang-icon.svg
  frontend/src/assets/icons/face-icon/face-icon-bad-gray.svg
  frontend/src/assets/icons/face-icon/face-icon-bad.svg
  frontend/src/assets/icons/face-icon/face-icon-good-gray.svg
  frontend/src/assets/icons/face-icon/face-icon-good.svg
  frontend/src/assets/icons/face-icon/face-icon-none.svg
  frontend/src/assets/icons/face-icon/face-icon-soso-gray.svg
  frontend/src/assets/icons/face-icon/face-icon-soso.svg
  frontend/src/assets/icons/options/refrigerator-filled.svg
  frontend/src/assets/icons/options/refrigerator-unfillled.svg
  frontend/src/components/ChecklistDetail/CheckListAnswer.tsx
  frontend/src/components/ChecklistDetail/ChecklistAnswerSection.tsx
  frontend/src/components/ChecklistList/CompareBanner.tsx
  frontend/src/components/ChecklistList/EditBanner.tsx
  frontend/src/components/ChecklistList/NoChecklistTemplate.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/NewChecklist/NewChecklistContent.tsx
  frontend/src/components/NewChecklist/NewChecklistInfoTemplate.tsx
  frontend/src/components/NewChecklist/NewChecklistTemplate.tsx
  frontend/src/components/NewChecklist/OptionModal/OptionModal.tsx
  frontend/src/components/common/Accordion/AccodionHeader.tsx
  frontend/src/components/common/Accordion/Accordion.stories.tsx
  frontend/src/components/common/Accordion/Accordion.tsx
  frontend/src/components/common/Button/FloatingButton.tsx
  frontend/src/components/common/FaceMark/FaceIcon.tsx
  frontend/src/components/common/Tabs/Tab.tsx
  frontend/src/components/common/layout/Layout.tsx
  frontend/src/constants/emotion.ts
  frontend/src/constants/routePath.ts
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/router.tsx
  frontend/src/styles/theme.ts
  frontend/webpack.config.js
Labels: 🔑 FE, 🎨 UI

#247 카카오 로그인 API 연동중 발생한 오류를 해결한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/User.java
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🐛 Bug, 🔒 BE

#252 [BE] 쿠키설정을 추가한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/CookieProvider.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
Labels: 🐛 Bug, 🔒 BE

#249 [FE] 모달과 옵션 모달의 내용을 리팩토링한다.
  frontend/src/assets/icons/options/refrigerator-unfillled.svg
  frontend/src/components/ChecklistDetail/CategoryAccordion.tsx
  frontend/src/components/DeleteModal.tsx
  frontend/src/components/NewChecklist/NewChecklistInfoTemplate.tsx
  frontend/src/components/NewChecklist/OptionModal/OptionModal.tsx
  frontend/src/components/NewChecklist/OptionModal/OptionModalInfoBox.tsx
  frontend/src/components/_common/Modal/Modal.stories.tsx
  frontend/src/components/_common/Modal/Modal.tsx
  frontend/src/components/_common/OptionButton/OptionButton.stories.tsx
  frontend/src/components/_common/OptionButton/OptionButton.tsx
  frontend/src/constants/options.ts
  frontend/src/pages/ChecklistCustomPage.tsx
  frontend/src/store/useChecklistStore.ts
  frontend/src/store/useOptionStore.ts
  frontend/src/types/option.ts
Labels: 🔑 FE, 🎨 UI

#257 [BE] 쿠키 설정 정보를 변경한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/CookieProvider.java
Labels: 🐛 Bug, 🔒 BE

#259 [FE] Oauth 쿠키 설정을 진행하고 로그인 api 연결을 확인한다.
  frontend/src/apis/fetcher.ts
  frontend/src/apis/login.ts
  frontend/src/apis/url.ts
  frontend/src/components/ChecklistDetail/CheckListAnswer.tsx
  frontend/src/components/ChecklistDetail/ChecklistAnswerSection.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/constants/emotion.ts
  frontend/src/constants/routePath.ts
  frontend/src/hooks/useChecklistAnswer.test.ts
  frontend/src/hooks/useChecklistAnswer.ts
  frontend/src/index.tsx
  frontend/src/mocks/fixtures/checklistDetail.ts
  frontend/src/pages/ChecklistDetailPage.tsx
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/store/useChecklistStore.ts
  frontend/src/styles/font.ts
  frontend/src/styles/global.ts
  frontend/src/types/checklist.ts
Labels: 🔑 FE, 😊 Feature, 🔧 Refactor

#260 [FE] 메모의 자동완성 기능을 추가하고, 체크리스트 관련 네이밍을 수정한다.
  frontend/src/components/ChecklistCustom/QuestionCardList/QuestionCardList.stories.tsx
  frontend/src/components/ChecklistCustom/QuestionCardList/QuestionCardList.tsx
  frontend/src/components/ChecklistCustom/QuestionSelectCard/QuestionSelectCard.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/QuestionMemo.tsx
  frontend/src/hooks/useChecklistGrade.test.ts
  frontend/src/hooks/useChecklistGrade.ts
  frontend/src/hooks/useChecklistQuestionUpdate.ts
  frontend/src/mocks/fixtures/checklistAllQuestions.ts
  frontend/src/store/useChecklistCustomStore.ts
  frontend/src/types/checklist.ts
Labels: 🔑 FE, 😊 Feature, 🔧 Refactor

#264 [FE] 기본정보 페이지 상태연결을 완료한다.
  frontend/src/components/NewChecklist/NewChecklistContent.tsx
  frontend/src/components/NewChecklist/NewChecklistInfoTemplate.tsx
  frontend/src/components/RoomCompare/CompareCard.tsx
  frontend/src/components/_common/Badge/Badge.stories.tsx
  frontend/src/components/_common/Badge/Badge.tsx
  frontend/src/hooks/useInputs.ts
  frontend/src/mocks/fixtures/checklistDetail.ts
  frontend/src/pages/CategoryChoosePage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/types/room.ts
Labels: 🔑 FE, 😊 Feature

#262 [BE] 커스텀 체크리스트 질문을 전체 조회한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Question.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/CategoryCustomChecklistQuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/CategoryCustomChecklistQuestionsResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/CustomChecklistQuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
Labels: 🔒 BE, 😊 Feature

#267 [BE] 유저를 저장하는 과정에서 발생하는 에러를 해결한다.
  backend/bang-ggood/src/main/resources/data.sql
Labels: 🐛 Bug, 🔒 BE

#272 [BE] 로깅 레벨에 따른 로그를 남긴다.
  backend/bang-ggood/build.gradle
  backend/bang-ggood/src/main/java/com/bang_ggood/Application.java
  backend/bang-ggood/src/main/java/com/bang_ggood/handler/GlobalExceptionHandler.java
  backend/bang-ggood/src/main/java/com/bang_ggood/logging/LoggingAspect.java
  backend/bang-ggood/src/main/java/com/bang_ggood/logging/dto/BaseLog.java
  backend/bang-ggood/src/main/java/com/bang_ggood/logging/dto/ErrorLog.java
  backend/bang-ggood/src/main/java/com/bang_ggood/logging/dto/InfoLog.java
  backend/bang-ggood/src/main/java/com/bang_ggood/logging/dto/WarnLog.java
  backend/bang-ggood/src/main/resources/logback.xml
Labels: 🔒 BE, ⚙ Chore

#277 [FE] 페이지 라우트를 정리하고 방 비교 페이지 API 를 확인한다.
  frontend/.gitignore
  frontend/src/apis/url.ts
  frontend/src/components/RoomCompare/CompareCard.tsx
  frontend/src/components/_common/layout/Layout.tsx
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/RoomComparePage.tsx
  frontend/src/pages/RoomCompareSelectPage.tsx
  frontend/src/router.tsx
  frontend/src/store/useRoomCompareStore.test.ts
  frontend/src/store/useRoomCompareStore.ts
  frontend/src/types/checklist.ts
  frontend/webpack.config.js
Labels: 🔑 FE, 😊 Feature

#278 [BE] 배포 환경에서 MySQL DB를 연결한다.
  backend/bang-ggood/build.gradle
  backend/bang-ggood/src/main/resources/schema.sql
Labels: 🔒 BE, 😊 Feature

#281 [FE] Google Analytics를 적용한다.
  frontend/index.html
Labels: 🔑 FE, 🌏 Infra

#282 [BE] 코드 스타일을 정리한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/ChecklistQuestion.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistQuestionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/CustomChecklistQuestionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/config/WebMvcConfig.java
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/LoginMockE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/JwtTokenProviderTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/ChecklistQuestionTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/ChecklistRankTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/UserFixture.java
Labels: 🔒 BE, ⚙ Chore

#288 [FE] 로그인 안되어있을 때 로그인 페이지로 리다이렉트하게 하기
  frontend/src/RootLayout.tsx
  frontend/src/components/ChecklistList/NoChecklistTemplate.tsx
  frontend/src/index.tsx
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/LoginPage.tsx
Labels: 🔑 FE, 😊 Feature

#292 [FE] 3차 데모데이 배포 사이트의 버그를 수정한다.
  frontend/src/apis/checklist.ts
  frontend/src/pages/NewChecklistPage.tsx
Labels: 🐛 Bug, 😊 Feature

#295 [FE] 커스텀 체크리스트의 api 연결을 확인하고 dev일 때 쿠키를 자동 저장한다.
  frontend/src/apis/checklist.ts
  frontend/src/apis/fetcher.ts
  frontend/src/components/ChecklistDetail/ChecklistAnswerSection.tsx
  frontend/src/components/_common/Accordion/AccodionHeader.tsx
  frontend/src/components/_common/Accordion/AccordionBody.tsx
  frontend/src/components/_common/Toast/Toast.tsx
  frontend/src/constants/system.ts
  frontend/src/index.tsx
  frontend/src/pages/CategoryChoosePage.tsx
  frontend/src/pages/ChecklistCustomPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
Labels: 🔑 FE, ⚙ Chore

#297 [BE] 체크리스트 좋아요 도메인을 추가한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/ChecklistLike.java
Labels: 🔒 BE, 😊 Feature

#300 [FE] 옵션 모달을 탭으로 리팩토링한다.
  frontend/src/assets/icons/options/doorLock-filled.svg
  frontend/src/assets/icons/options/doorLock-unfilled.svg
  frontend/src/assets/icons/options/doorlock-filled.svg
  frontend/src/assets/icons/options/doorlock-unfilled.svg
  frontend/src/components/NewChecklist/NewChecklistContent.tsx
  frontend/src/components/NewChecklist/NewChecklistInfoTemplate.tsx
  frontend/src/components/NewChecklist/NewChecklistTab.tsx
  frontend/src/components/NewChecklist/Option/OptionChecklistTemplate.tsx
  frontend/src/components/NewChecklist/Option/OptionModalInfoBox.tsx
  frontend/src/components/NewChecklist/OptionModal/OptionModal.tsx
  frontend/src/components/_common/OptionButton/OptionButton.tsx
  frontend/src/components/_common/OptionButton/optionData.json
  frontend/src/components/_common/SelectionCounter/SelectionCounter.tsx
  frontend/src/constants/options.ts
  frontend/src/pages/ChecklistCustomPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/store/useOptionStore.ts
Labels: 🔑 FE, 🔧 Refactor

#304 [FE] 체크리스트 작성 옵션을 이모션에서 OX로 변경한다
  frontend/src/apis/checklist.ts
  frontend/src/assets/assets.tsx
  frontend/src/assets/icons/answer/no-isSelected.svg
  frontend/src/assets/icons/answer/no.svg
  frontend/src/assets/icons/answer/none.svg
  frontend/src/assets/icons/answer/yes-isSelected.svg
  frontend/src/assets/icons/answer/yes.svg
  frontend/src/assets/icons/face-icon/face-icon-bad-gray.svg
  frontend/src/assets/icons/face-icon/face-icon-bad.svg
  frontend/src/assets/icons/face-icon/face-icon-good-gray.svg
  frontend/src/assets/icons/face-icon/face-icon-good.svg
  frontend/src/assets/icons/face-icon/face-icon-none.svg
  frontend/src/assets/icons/face-icon/face-icon-soso-gray.svg
  frontend/src/assets/icons/face-icon/face-icon-soso.svg
  frontend/src/components/Answer/AnswerIcon.stories.tsx
  frontend/src/components/Answer/AnswerIcon.tsx
  frontend/src/components/ChecklistDetail/CheckListAnswer.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/QuestionMemo.tsx
  frontend/src/components/NewChecklist/NewChecklistContent.tsx
  frontend/src/components/NewChecklist/NewChecklistTemplate.tsx
  frontend/src/components/RoomCompare/CompareCard.tsx
  frontend/src/components/_common/FaceMark/FaceIcon.stories.tsx
  frontend/src/components/_common/FaceMark/FaceIcon.tsx
  frontend/src/components/_common/FaceMark/FaceMark.stories.tsx
  frontend/src/components/_common/FaceMark/FaceMark.tsx
  frontend/src/components/_common/Header/Header.tsx
  frontend/src/constants/answer.ts
  frontend/src/constants/emotion.ts
  frontend/src/hooks/useChecklistAnswer.test.ts
  frontend/src/hooks/useChecklistAnswer.ts
  frontend/src/hooks/useChecklistGrade.test.ts
  frontend/src/hooks/useChecklistGrade.ts
  frontend/src/index.tsx
  frontend/src/mocks/fixtures/checklistDetail.ts
  frontend/src/mocks/fixtures/checklistQuestions.ts
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/store/useChecklistStore.ts
  frontend/src/styles/theme.ts
  frontend/src/types/answer.ts
  frontend/src/types/checklist.ts
  frontend/src/types/emotionAnswer.ts
  frontend/src/types/room.ts
  frontend/src/utils/calcEmotions.ts
Labels: 🔑 FE, 😊 Feature, 🔧 Refactor, 🎨 UI

#303 [BE] 체크리스트 좋아요를 추가한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Checklist.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistLikeRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE, 😊 Feature

#312 [FE] 카카오 맵 api를 사용하여 실시간 위치를 기반으로 위치를 데이터화 한다.
  frontend/index.html
  frontend/package.json
  frontend/src/components/NewChecklist/NewChecklistTab.tsx
  frontend/src/components/NewChecklist/Option/OptionChecklistTemplate.tsx
  frontend/src/components/_common/Map/Map.tsx
  frontend/src/components/_common/OptionButton/OptionButton.tsx
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/mocks/fixtures/checklistQuestions.ts
  frontend/src/router.tsx
  frontend/yarn.lock
Labels: 🔑 FE, 😊 Feature

#315 [FE] 리스트 상태 관리를 react-query 를 사용하여 전역으로 관리한다.
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/system.ts
  frontend/src/hooks/query/useAddChecklistQuery.ts
  frontend/src/hooks/query/useDeleteChecklistQuery.ts
  frontend/src/hooks/query/useGetChecklistListQuery.ts
  frontend/src/hooks/query/useRefetchGetChecklistList.ts
  frontend/src/pages/ChecklistDetailPage.tsx
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
Labels: 🔑 FE, 🔧 Refactor

#307 [BE] 체크리스트 질문조회 API를 수정한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/JwtTokenProvider.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Question.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
  backend/bang-ggood/src/main/resources/data.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/JwtTokenProviderTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/CustomChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/QuestionTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
  backend/bang-ggood/src/test/resources/data-test.sql
Labels: 🔒 BE, 😊 Feature

#311 [BE] 체크리스트 좋아요를 삭제한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistLikeRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/ChecklistTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/UserFixture.java
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE, 😊 Feature

#322 [BE] 체크리스트 리스트 API를 수정한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/UserChecklistPreviewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
Labels: 🔒 BE, 😊 Feature

#328 [FE] 체크리스트 리스트 페이지 UI 를 수정한다.
  frontend/package.json
  frontend/src/apis/like.ts
  frontend/src/apis/url.ts
  frontend/src/assets/assets.tsx
  frontend/src/assets/icons/heart/heart-empty.svg
  frontend/src/assets/icons/heart/heart.svg
  frontend/src/assets/icons/smile-message-icon.svg
  frontend/src/components/ChecklistList/ChecklistPreviewCard.tsx
  frontend/src/components/ChecklistList/CustomBanner.tsx
  frontend/src/components/ChecklistList/HeartIcon.tsx
  frontend/src/hooks/query/useToggleLikeQuery.ts
  frontend/src/mocks/fixtures/checklistList.ts
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/types/checklist.ts
  frontend/yarn.lock
Labels: 🔑 FE, 😊 Feature, 🎨 UI

#329 [FE] 새 체크리스트 기본정보 검증 로직을 구현하고 상태관리한다
  frontend/src/components/NewChecklist/NewChecklistContent.tsx
  frontend/src/components/NewChecklist/NewChecklistInfoTemplate.tsx
  frontend/src/components/_common/FormField/FormField.stories.tsx
  frontend/src/components/_common/FormField/FormField.tsx
  frontend/src/constants/roomInfo.ts
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/store/checklistRoomInfoStore.test.ts
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/src/utils/validators.ts
Labels: 🔑 FE, 😊 Feature

#327 [BE] 질문 목록 순서를 카테고리 순으로 정렬한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
Labels: 🐛 Bug, 🔒 BE

#324 [BE] 아티클 조회 API를 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/domain/Article.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/ArticleResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/repository/ArticleRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
  backend/bang-ggood/src/main/resources/data.sql
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE, 😊 Feature

#331 [FE] 인풋 컴포넌트 UI 를 변경 및 주소 검색 모달을 연결한다.
  frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
  frontend/src/components/NewChecklist/NewChecklistInfoTemplate.tsx
  frontend/src/components/_common/FormField/FormField.stories.tsx
  frontend/src/components/_common/FormField/FormField.tsx
  frontend/src/components/_common/Input/Input.tsx
  frontend/src/components/_common/Modal/Modal.tsx
  frontend/src/components/_common/RadioGroup/RadioContext.ts
  frontend/src/components/_common/RadioGroup/RadioGroup.tsx
  frontend/src/hooks/useInputs.ts
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/src/styles/theme.ts
  frontend/src/types/event.ts
Labels: 🔑 FE, 😊 Feature, 🔧 Refactor, 🎨 UI

#319 [FE] 옵션 탭에 팁박스를 추가하고 미디어쿼리를 세분화한다.
  frontend/public/mockServiceWorker.js
  frontend/src/RootLayout.tsx
  frontend/src/components/NewChecklist/NewChecklistTab.tsx
  frontend/src/components/NewChecklist/Option/OptionChecklistTemplate.tsx
  frontend/src/components/_common/OptionButton/OptionButton.tsx
  frontend/src/components/_common/Tabs/Tab.tsx
  frontend/src/components/_common/Tabs/Tabs.tsx
  frontend/src/constants/localStorage.ts
  frontend/src/hooks/useNewChecklistTabs.ts
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/store/useChecklistStore.ts
Labels: 🔑 FE, 🎨 UI

#335 [BE] 체크리스트 작성 시 메모에 관해 NPE 뜨는 오류를 수정한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Checklist.java
Labels: 🐛 Bug, 🔒 BE, 😊 Feature

#336 [FE] 메모를 모달로 리팩토링한다.
  frontend/src/components/NewChecklist/ChecklistQuestion/QuestionMemo.tsx
  frontend/src/components/NewChecklist/MemoModal/MemoModal.tsx
  frontend/src/components/NewChecklist/NewChecklistContent.tsx
  frontend/src/components/NewChecklist/NewChecklistTemplate.tsx
  frontend/src/components/_common/Button/Button.tsx
  frontend/src/components/_common/Textarea/Textarea.tsx
  frontend/src/hooks/useInput.ts
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/src/types/room.ts
Labels: 🔑 FE, 🎨 UI

#337 [FE] 체크리스트 리스트 API 및 작성 API 연결을 확인한다.
  frontend/index.html
  frontend/src/components/ChecklistList/ChecklistPreviewCard.tsx
  frontend/src/components/NewChecklist/Option/OptionBox.tsx
  frontend/src/components/NewChecklist/Option/OptionChecklistTemplate.tsx
  frontend/src/components/_common/Input/Input.tsx
  frontend/src/constants/routePath.ts
  frontend/src/index.tsx
  frontend/src/router.tsx
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/src/types/checklist.ts
  frontend/src/types/room.ts
  frontend/src/utils/formattedDate.ts
Labels: 🔑 FE, 😊 Feature

#340 [FE] 깨지고 정리안된 UI 리팩토링 작업을 한다.
  frontend/src/assets/assets.tsx
  frontend/src/assets/icons/plus/plus-black.svg
  frontend/src/assets/icons/plus/plus-white.svg
  frontend/src/components/ChecklistDetail/CheckListAnswer.tsx
  frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
  frontend/src/components/_common/Button/FloatingButton.stories.tsx
  frontend/src/components/_common/Button/FloatingButton.tsx
  frontend/src/components/_common/Header/Header.tsx
  frontend/src/pages/ChecklistCustomPage.tsx
  frontend/src/pages/ChecklistDetailPage.tsx
  frontend/src/pages/ChecklistListPage.tsx
Labels: 🔑 FE, 🔧 Refactor, 🎨 UI

#341 [FE] 맨 아래의 두 폼에서 에러메시지가 표출되는 현상을 해결한다
  frontend/src/components/NewChecklist/NewChecklistInfoTemplate.tsx
Labels: 🔑 FE

#350 [FE] 한줄평 기능을 추가한다.
  frontend/src/components/NewChecklist/NewChecklistContent.tsx
  frontend/src/components/NewChecklist/SummaryModal/SummaryModal.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/store/checklistRoomInfoStore.test.ts
  frontend/src/store/checklistRoomInfoStore.ts
Labels: 🔑 FE, 😊 Feature

#351 [FE] 모달을 리팩토링한다.
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/assets/assets.tsx
  frontend/src/assets/icons/memo.svg
  frontend/src/components/NewChecklist/MemoModal/MemoModal.tsx
  frontend/src/components/NewChecklist/NewChecklistContent.tsx
  frontend/src/components/NewChecklist/NewChecklistInfoTemplate.tsx
  frontend/src/components/NewChecklist/NewChecklistTemplate.tsx
  frontend/src/components/_common/Badge/Badge.tsx
  frontend/src/components/_common/FloatingButton/FloatingButton.stories.tsx
  frontend/src/components/_common/FloatingButton/FloatingButton.tsx
  frontend/src/components/_common/Input/Input.tsx
  frontend/src/components/_common/Modal/Modal.tsx
  frontend/src/components/_common/Modal/ModalHeader.tsx
  frontend/src/components/_common/Tabs/Tab.tsx
  frontend/src/components/_common/Textarea/Textarea.tsx
  frontend/src/pages/ChecklistListPage.tsx
  frontend/yarn.lock
Labels: 🔑 FE

#353 [FE] 사용자가 처음 방끗을 사용할 때 디폴트 체크리스트를 보여준다.
  frontend/src/apis/checklist.ts
  frontend/src/mocks/fixtures/dummyChecklist.ts
  frontend/src/pages/LoginPage.tsx
  frontend/src/store/checklistRoomInfoStore.ts
Labels: 🔑 FE, 😊 Feature

#359 [FE] 기본정보 폼의 에러메시지를 모두 잘 띄운다.
  frontend/src/components/NewChecklist/MemoModal/MemoModal.tsx
  frontend/src/components/NewChecklist/NewChecklistInfoTemplate.tsx
  frontend/src/components/NewChecklist/SummaryModal/SummaryModal.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/store/checklistRoomInfoStore.test.ts
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/src/utils/utilityTypes.ts
  frontend/src/utils/validators.ts
Labels: 🔑 FE, 😊 Feature

#360 [BE] 체크리스트 조회 API를 수정한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Checklist.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/SelectedChecklistResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/response/SelectedRoomResponse.java
Labels: 🔒 BE, 😊 Feature

#357 [BE] 아티클 리스트 조회 API를 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/ArticlePreviewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/ArticlesPreviewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
Labels: 🔒 BE, 😊 Feature

#362 [BE] 체크리스트 질문 조회 API를 수정한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
Labels: 🔒 BE, 😊 Feature

#364 [BE] 체크리스트 수정 API를 추가 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Checklist.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/domain/Room.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
Labels: 🔒 BE, 😊 Feature

#371 [BE] 체크리스트 삭제 API를 추가 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
Labels: 🔒 BE, 😊 Feature

#374 [BE] 수정된 옵션 항목을 반영한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Option.java
Labels: 🔒 BE, 😊 Feature

#375 [FE] 팁박스를 여러개 사용할 수 있게 수정하고 메모 및 answer를 리팩토링한다.
  frontend/src/assets/assets.tsx
  frontend/src/assets/icons/answer/no-isSelected.svg
  frontend/src/assets/icons/answer/no.svg
  frontend/src/assets/icons/answer/none.svg
  frontend/src/assets/icons/answer/yes-isSelected.svg
  frontend/src/assets/icons/answer/yes.svg
  frontend/src/assets/icons/options/eletronic-stove-filled.svg
  frontend/src/assets/icons/options/eletronic-stove-unfilled.svg
  frontend/src/assets/icons/plusMinus/plus-black.svg
  frontend/src/assets/icons/plusMinus/plus-small.svg
  frontend/src/assets/icons/plusMinus/plus-white.svg
  frontend/src/components/Answer/AnswerIcon.tsx
  frontend/src/components/ChecklistCustom/QuestionCardList/QuestionCardList.tsx
  frontend/src/components/ChecklistCustom/QuestionListTemplate/QuestionListTemplate.tsx
  frontend/src/components/ChecklistCustom/QuestionSelectCard/QuestionSelectCard.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/NewChecklist/MemoModal/MemoModal.tsx
  frontend/src/components/NewChecklist/Option/OptionBox.tsx
  frontend/src/components/NewChecklist/Option/OptionChecklistTemplate.tsx
  frontend/src/components/_common/Checkbox/Checkbox.tsx
  frontend/src/components/_common/LengthCounter/LengthCounter.stories.tsx
  frontend/src/components/_common/LengthCounter/LengthCounter.tsx
  frontend/src/components/_common/Modal/Modal.tsx
  frontend/src/components/_common/Textarea/Textarea.tsx
  frontend/src/components/_common/TipBox/TipBox.stories.tsx
  frontend/src/components/_common/TipBox/TipBox.tsx
  frontend/src/constants/message.ts
  frontend/src/constants/options.ts
  frontend/src/hooks/useHandleTipBox.ts
  frontend/src/mocks/fixtures/checklistAllQuestions.ts
  frontend/src/mocks/handlers/checklist.ts
  frontend/src/pages/ChecklistCustomPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/utils/animation.ts
Labels: 🔑 FE, 🔧 Refactor, 🎨 UI

#379 [BE] 회원가입시 디폴트 체크리스트를 추가한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Option.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
Labels: 🔒 BE, 😊 Feature

#380 [FE] 체크리스트 디테일 페이지를 바뀐 디자인으로 구현한다.
  frontend/src/assets/assets.tsx
  frontend/src/assets/fonts/SUIT-Bold.woff2
  frontend/src/assets/fonts/SUIT-Regular.woff2
  frontend/src/assets/fonts/SUITE-Variable.woff2
  frontend/src/assets/icons/heart/heart-empty.svg
  frontend/src/assets/icons/heart/heart.svg
  frontend/src/assets/icons/like/Like.tsx
  frontend/src/assets/icons/room/building.svg
  frontend/src/assets/icons/room/calendar.svg
  frontend/src/assets/icons/room/house.svg
  frontend/src/assets/icons/room/stairs.svg
  frontend/src/assets/icons/room/subway.svg
  frontend/src/components/ChecklistDetail/CheckListAnswer.tsx
  frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
  frontend/src/components/ChecklistList/ChecklistPreviewCard.tsx
  frontend/src/components/ChecklistList/HeartIcon.tsx
  frontend/src/components/RoomCompare/CompareSelectCard.tsx
  frontend/src/components/_common/Accordion/AccodionHeader.tsx
  frontend/src/components/_common/Accordion/AccordionBody.tsx
  frontend/src/components/_common/Like/LikeButton.tsx
  frontend/src/mocks/fixtures/checklistDetail.ts
  frontend/src/pages/ChecklistDetailPage.tsx
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/src/styles/font.ts
  frontend/src/styles/global.ts
  frontend/src/types/checklist.ts
  frontend/src/types/option.ts
  frontend/src/types/room.ts
  frontend/src/types/svg.d.ts
  frontend/src/utils/formattedUndefined.ts
Labels: 🔑 FE, 😊 Feature, 🎨 UI

#370 [BE] 체크리스트 좋아요 필터링 기능을 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
Labels: 🔒 BE, 😊 Feature

#386 [BE] dev, prod, local 설정 파일 분리한다.
  .github/workflows/backend-ci.yml
  .github/workflows/backend-dev-cd.yml
  backend/bang-ggood/.gitignore
Labels: 🔒 BE, 🌏 Infra

#390 [BE] dev-be 브랜치와 dev를 병합한다.
  .github/workflows/backend-ci.yml
  .github/workflows/backend-dev-cd.yml
  backend/bang-ggood/.gitignore
  backend/bang-ggood/hs_err_pid6379.jfr
  backend/bang-ggood/hs_err_pid6379.log
  backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/ArticlePreviewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/ArticlesPreviewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/category/domain/Category.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Checklist.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Option.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/SelectedChecklistResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/domain/Room.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/response/SelectedRoomResponse.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
Labels: 🔒 BE, 🌏 Infra

#393 [FE] 체크리스트 수정페이지를 구현한다.
  frontend/src/apis/checklist.ts
  frontend/src/components/Answer/AnswerIcon.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/NewChecklist/NewChecklistTemplate.tsx
  frontend/src/constants/routePath.ts
  frontend/src/hooks/query/useGetChecklistDetailQuery.ts
  frontend/src/hooks/useNewChecklistTabs.ts
  frontend/src/pages/EditChecklistPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/router.tsx
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/src/store/useChecklistStore.ts
  frontend/src/utils/typeFunctions.ts
Labels: 🔑 FE, 😊 Feature

#395 [FE] 방끗 메인 페이지를 제작한다.
  frontend/src/apis/article.ts
  frontend/src/apis/url.ts
  frontend/src/assets/icons/arrow/ArrowRight.tsx
  frontend/src/assets/icons/common/HomeCircle.tsx
  frontend/src/assets/icons/footer/Article.tsx
  frontend/src/assets/icons/footer/Checklist.tsx
  frontend/src/assets/icons/footer/Home.tsx
  frontend/src/assets/icons/footer/Profile.tsx
  frontend/src/components/Article/ArticleCard.tsx
  frontend/src/components/ChecklistList/ChecklistMiniCard.tsx
  frontend/src/components/FooterDefault.tsx
  frontend/src/components/Section/ArticleSection.tsx
  frontend/src/components/Section/ChecklistSection.tsx
  frontend/src/components/_common/Footer/Footer.stories.tsx
  frontend/src/components/_common/Footer/Footer.tsx
  frontend/src/components/_common/Footer/FooterButton.tsx
  frontend/src/components/_common/Footer/FooterDefault.tsx
  frontend/src/components/_common/Header/Header.tsx
  frontend/src/constants/oAuth.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/routePath.ts
  frontend/src/hooks/query/useGetArticleQuery.ts
  frontend/src/mocks/fixtures/articleList.ts
  frontend/src/mocks/fixtures/checklistList.ts
  frontend/src/mocks/handlers/article.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/router.tsx
  frontend/src/styles/common.ts
  frontend/src/styles/theme.ts
  frontend/src/types/article.ts
  frontend/src/utils/getSeqColor.ts
Labels: 🔑 FE, 😊 Feature, 🎨 UI

#394 [FE] 지도 기능을 통합하고 전역 상태로 관리한다.
  frontend/src/assets/icons/options/eletronic-stove-filled.svg
  frontend/src/assets/icons/options/eletronic-stove-unfilled.svg
  frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
  frontend/src/components/ChecklistList/ChecklistPreviewCard.stories.tsx
  frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
  frontend/src/components/NewChecklist/AddressModal/RealTimeAddressModal.tsx
  frontend/src/components/NewChecklist/MemoModal/MemoButton.tsx
  frontend/src/components/NewChecklist/NewChecklistInfoTemplate.tsx
  frontend/src/components/NewChecklist/NewChecklistTemplate.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/Address.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/IncludedUtilities.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/MaintenanceFee.tsx
  frontend/src/components/NewChecklist/Option/OptionChecklistTemplate.tsx
  frontend/src/components/RoomCompare/CompareCard.tsx
  frontend/src/components/_common/Button/Button.tsx
  frontend/src/components/_common/Input/Input.tsx
  frontend/src/components/_common/Map/AddressMap.tsx
  frontend/src/components/_common/Map/RealTimeMap.tsx
  frontend/src/components/_common/Modal/ModalBody.tsx
  frontend/src/components/_common/Modal/ModalHeader.tsx
  frontend/src/constants/map.ts
  frontend/src/mocks/fixtures/checklistDetail.ts
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/router.tsx
  frontend/src/store/checklistAddressStore.ts
  frontend/src/styles/global.ts
  frontend/src/types/checklist.ts
  frontend/src/types/room.ts
Labels: 🔑 FE, 😊 Feature

#388 [BE] 옵션 목록을 수정한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Option.java
Labels: 🔒 BE, 😊 Feature

#402 [FE] HTTP status에 따른 커스텀 에러 핸들링 로직을 추가한다.
  frontend/src/App.tsx
  frontend/src/apis/error/HttpError.ts
  frontend/src/apis/error/constants.ts
  frontend/src/apis/fetcher.ts
  frontend/src/assets/icons/bang-bang-cry-icon.svg
  frontend/src/components/_common/DeleteModal/DeleteModal.tsx
  frontend/src/components/_common/Map/AddressMap.tsx
  frontend/src/components/_common/Toast/Toast.stories.tsx
  frontend/src/components/_common/Toast/Toast.tsx
  frontend/src/hooks/useToast.test.ts
  frontend/src/hooks/useToast.ts
  frontend/src/mocks/handlers/checklist.ts
  frontend/src/pages/CategoryChoosePage.tsx
  frontend/src/pages/ChecklistCustomPage.tsx
  frontend/src/pages/ChecklistDetailPage.tsx
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/EditChecklistPage.tsx
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/store/useToastStore.ts
Labels: 🔑 FE, 😊 Feature

#403 [FE] 로딩 시 스켈레톤 UI를 추가한다.
  frontend/package.json
  frontend/src/apis/error/constants.ts
  frontend/src/assets/icons/smile-message-icon.svg
  frontend/src/components/ChecklistList/ChecklistCard.tsx
  frontend/src/components/ChecklistList/CustomBanner.tsx
  frontend/src/components/Main/ArticleSection.tsx
  frontend/src/components/Main/ChecklistSection.tsx
  frontend/src/components/_common/FlexBox/FlexBox.tsx
  frontend/src/components/_common/layout/FooterLayout.tsx
  frontend/src/components/skeleton/Article/SkArticleList.tsx
  frontend/src/components/skeleton/ChecklistDetail/SkChecklistAnswer.tsx
  frontend/src/components/skeleton/ChecklistDetail/SkChecklistDetail.tsx
  frontend/src/components/skeleton/ChecklistDetail/SkRoomInfoSection.tsx
  frontend/src/components/skeleton/ChecklistList/SkChecklistLst.tsx
  frontend/src/components/skeleton/Main/SkArticleSection.tsx
  frontend/src/components/skeleton/Main/SkChecklistSection.tsx
  frontend/src/mocks/fixtures/checklistList.ts
  frontend/src/pages/ArticleListPage.tsx
  frontend/src/pages/ChecklistDetailPage.tsx
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/router.tsx
  frontend/src/styles/common.ts
Labels: 🔑 FE, 🎨 UI

#404 [FE] 아티클 디테일 페이지를 제작한다.
  frontend/package.json
  frontend/src/apis/article.ts
  frontend/src/components/Article/ArticleCard.tsx
  frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
  frontend/src/components/ChecklistList/ChecklistCard.tsx
  frontend/src/components/Main/ArticleSection.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/routePath.ts
  frontend/src/constants/system.ts
  frontend/src/hooks/query/useGetArticleListQuery.ts
  frontend/src/hooks/query/useGetArticleQuery.ts
  frontend/src/hooks/query/useGetChecklistDetailQuery.ts
  frontend/src/mocks/fixtures/article.ts
  frontend/src/mocks/handlers/article.ts
  frontend/src/pages/ArticleDetailPage.tsx
  frontend/src/pages/ArticleListPage.tsx
  frontend/src/pages/ChecklistDetailPage.tsx
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/router.tsx
  frontend/src/styles/theme.ts
  frontend/yarn.lock
Labels: 🔑 FE, 😊 Feature, 🎨 UI

#407 [BE] 파일을 yml 파일로 수정한다.
  .github/workflows/backend-prod-cd.yml
Labels: 🐛 Bug, 🔒 BE, ⚙ Chore, 🌏 Infra

#414 [BE] drop 명령어 순서를 변경한다.
  backend/bang-ggood/hs_err_pid6379.jfr
  backend/bang-ggood/src/main/resources/schema.sql
Labels: 🐛 Bug, 🔒 BE, ⚙ Chore, 🌏 Infra

#410 [FE] 마이페이지를 구현한다.
  frontend/src/apis/login.ts
  frontend/src/apis/url.ts
  frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
  frontend/src/components/MyPage/MyPageModal.tsx
  frontend/src/constants/routePath.ts
  frontend/src/hooks/query/useUserQuery.ts
  frontend/src/mocks/fixtures/user.ts
  frontend/src/mocks/handlers/index.ts
  frontend/src/mocks/handlers/user.ts
  frontend/src/pages/ChecklistDetailPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/router.tsx
  frontend/src/types/user.ts
Labels: 🔑 FE, 😊 Feature

#417 [FE] 로그인 되지 않았을 경우 OAuth로그인페이지로 route한다.
  frontend/src/components/Auth/AuthGuard.tsx
  frontend/src/components/ChecklistList/ChecklistCard.tsx
  frontend/src/components/Main/ArticleSection.tsx
  frontend/src/components/Main/ChecklistPreviewCard.tsx
  frontend/src/components/Main/ChecklistSection.tsx
  frontend/src/components/NewChecklist/NewChecklistContent.tsx
  frontend/src/components/NewChecklist/NewChecklistInfoTemplate.tsx
  frontend/src/components/NewChecklist/NewChecklistTemplate.tsx
  frontend/src/components/NewChecklist/Option/OptionChecklistTemplate.tsx
  frontend/src/components/_common/Tabs/Tab.tsx
  frontend/src/components/_common/Tabs/Tabs.tsx
  frontend/src/components/_common/layout/Layout.tsx
  frontend/src/components/skeleton/Article/SkArticleList.tsx
  frontend/src/components/skeleton/ChecklistList/SkChecklistLst.tsx
  frontend/src/constants/style.ts
  frontend/src/constants/system.ts
  frontend/src/hooks/query/useGetArticleListQuery.ts
  frontend/src/hooks/query/useGetArticleQuery.ts
  frontend/src/hooks/query/useGetChecklistDetailQuery.ts
  frontend/src/hooks/query/useGetChecklistListQuery.ts
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/router.tsx
  frontend/src/styles/global.ts
Labels: 🔑 FE, 😊 Feature

#423 [BE] 체크리스트 조회 API를 수정한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/SelectedQuestionResponse.java
Labels: 🔒 BE, 😊 Feature

#424 [BE] dev-be 브랜치와 dev 브랜치를 병합한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/SelectedQuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/controller/UserController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/dto/UserResponse.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/controller/UserE2ETest.java
Labels: 🔒 BE

#426 스키마를 수정한다.
  backend/bang-ggood/src/main/resources/schema.sql
Labels: 🐛 Bug, 🔒 BE

#429 [BE] dev-be를 dev 브랜치로 병합한다.
  backend/bang-ggood/src/main/resources/data.sql
  backend/bang-ggood/src/main/resources/schema.sql
Labels: 🔒 BE

#427 [FE] 드롭다운 제어컴포넌트를 구현한다.
  frontend/src/assets/assets.tsx
  frontend/src/assets/icons/dropdown/dropdown-mark.svg
  frontend/src/components/NewChecklist/NewRoomInfoForm/OccupancyMonth.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomFloor.tsx
  frontend/src/components/_common/Dropdown/Dropdown.stories.tsx
  frontend/src/components/_common/Dropdown/Dropdown.tsx
  frontend/src/styles/theme.ts
Labels: 🔑 FE, 😊 Feature

#430 [BE] 유저 정보 조회 데이터 형식을 수정한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/user/dto/UserResponse.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/controller/UserE2ETest.java
Labels: 🔒 BE, 😊 Feature

#434 [BE] 유저 정보 조회 데이터 형식을 수정한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/user/dto/UserResponse.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/controller/UserE2ETest.java
Labels: 🔒 BE, 😊 Feature

#433 [FE] 백엔드 API 와 연결하며 QA를 진행한다.
  frontend/.vscode/settings.json
  frontend/src/apis/error/HttpError.ts
  frontend/src/apis/fetcher.ts
  frontend/src/apis/url.ts
  frontend/src/components/Article/ArticleCard.tsx
  frontend/src/components/Auth/AuthGuard.tsx
  frontend/src/components/ChecklistCustom/QuestionListTemplate/QuestionListTemplate.tsx
  frontend/src/components/ChecklistCustom/QuestionSelectCard/QuestionSelectCard.tsx
  frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
  frontend/src/components/Main/ChecklistPreviewCard.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/NewChecklist/MemoModal/MemoModal.tsx
  frontend/src/components/NewChecklist/NewChecklistInfoTemplate.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/MaintenanceFee.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/NearTransportation.tsx
  frontend/src/components/RoomCompare/CompareCard.tsx
  frontend/src/components/_common/CounterBox/CounterBox.tsx
  frontend/src/components/_common/Input/Input.tsx
  frontend/src/components/_common/TipBox/TipBox.tsx
  frontend/src/constants/httpErrorMessage.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/routePath.ts
  frontend/src/hooks/query/useUserQuery.ts
  frontend/src/mocks/fixtures/article.ts
  frontend/src/mocks/fixtures/articleList.ts
  frontend/src/mocks/fixtures/checklistDetail.ts
  frontend/src/mocks/fixtures/roomsForCompare.ts
  frontend/src/mocks/fixtures/user.ts
  frontend/src/pages/ArticleDetailPage.tsx
  frontend/src/pages/ArticleListPage.tsx
  frontend/src/pages/ChecklistCustomPage.tsx
  frontend/src/pages/ChecklistDetailPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/router.tsx
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/src/types/article.ts
  frontend/src/types/category.ts
  frontend/src/types/checklist.ts
  frontend/src/types/user.ts
  frontend/src/utils/formattedDate.ts
  frontend/src/utils/validators.ts
Labels: 🐛 Bug, 🔑 FE

#439 [BE] 유저 정보 조회 데이터 명을 수정한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/OauthInfoApiResponse.java
Labels: 🐛 Bug, 🔒 BE, 😊 Feature

#442 [BE] 아티클 content 길이를 늘린다.
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🐛 Bug, 🔒 BE

#445 [BE] AcceptanceMockTestSupport 파일 ActiveProfiles에 test를 추가한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/config/CorsConfig.java
  backend/bang-ggood/src/test/java/com/bang_ggood/AcceptanceMockTestSupport.java
Labels: 🐛 Bug, 🔒 BE

#446 [BE] dev-be와 dev를 병합한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/OauthInfoApiResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/config/CorsConfig.java
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/AcceptanceMockTestSupport.java
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE

#448 [BE] 아티클 내용 길이를 수정한다.
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🐛 Bug, 🔒 BE

#421 [BE] 현재 위치에서 가까운 지하철 역을 조회한다.
  backend/bang-ggood/build.gradle
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/SubwayReader.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/controller/SubwayStationController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/domain/SubwayStation.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/dto/SubwayStationResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
  backend/bang-ggood/src/main/resources/seoul_stations_240819.csv
  backend/bang-ggood/src/test/java/com/bang_ggood/station/SubwayStationServiceTest.java
  backend/bang-ggood/src/test/resources/seoul_stations_240819.csv
Labels: 🔒 BE, 😊 Feature

#449 [BE] dev-be 브랜치와 dev 브랜치를 병합한다.
  backend/bang-ggood/build.gradle
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/SubwayReader.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/controller/SubwayStationController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/domain/SubwayStation.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/dto/SubwayStationResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/main/resources/seoul_stations_240819.csv
  backend/bang-ggood/src/test/java/com/bang_ggood/station/SubwayStationServiceTest.java
  backend/bang-ggood/src/test/resources/schema-test.sql
  backend/bang-ggood/src/test/resources/seoul_stations_240819.csv
Labels: 🔒 BE, 😊 Feature

#450 아티클 내용 컬럼 타입을 변경한다.
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🐛 Bug, 🔒 BE

#451 [BE] dev-be 브랜치와 dev 브랜치를 병합한다.
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🐛 Bug, 🔒 BE

#443 [FE] 관리비 포함 항목을 상태 연결하고 POST가 동작하게 한다.
  frontend/src/components/NewChecklist/NewRoomInfoForm/Address.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/IncludedUtilities.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/roomInfo.ts
  frontend/src/hooks/query/useGetChecklistQuestionQuery.ts
  frontend/src/hooks/useChecklistPost.ts
  frontend/src/hooks/useInitialChecklist.ts
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/store/checklistAddressStore.ts
  frontend/src/store/checklistIncludedUtilitesStore.ts
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/src/types/room.ts
Labels: 🔑 FE, 😊 Feature, 🔧 Refactor

#452 [BE] CORS 설정시 dev, prod를 분리한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/config/CorsConfig.java
  backend/bang-ggood/src/test/java/com/bang_ggood/config/CorsConfigTest.java
Labels: 🔒 BE, 🔧 Refactor

#453 [BE] dev-be와 dev 브랜치를 병합한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/config/CorsConfig.java
  backend/bang-ggood/src/test/java/com/bang_ggood/config/CorsConfigTest.java
Labels: 🔒 BE

#456 [BE] dev와 dev-be 브랜치를 병합한다.
  backend/bang-ggood/src/test/java/com/bang_ggood/config/CorsConfigTest.java
Labels: 🔒 BE

#459 [BE] 유저 정보 조회 시 userName을 반환한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/user/dto/UserResponse.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/controller/UserE2ETest.java
Labels: 🔒 BE, 😊 Feature

#447 [FE] 랜딩 페이지를 제작한다.
  frontend/public/image/checkScreenShot.png
  frontend/public/image/home.png
  frontend/public/image/mainScreenShot.png
  frontend/public/image/outdoor.png
  frontend/public/image/security.png
  frontend/public/image/toilet.png
  frontend/public/image/window.png
  frontend/src/App.tsx
  frontend/src/assets/assets.tsx
  frontend/src/assets/icons/small-check.svg
  frontend/src/components/Landing/FifthSection.tsx
  frontend/src/components/Landing/FirstSection.tsx
  frontend/src/components/Landing/FourthSection.tsx
  frontend/src/components/Landing/SecondSection.tsx
  frontend/src/components/Landing/ThirdSection.tsx
  frontend/src/components/Landing/style.ts
  frontend/src/components/_common/TopButton/TopButton.tsx
  frontend/src/constants/routePath.ts
  frontend/src/constants/system.ts
  frontend/src/hooks/useIntersection.ts
  frontend/src/mocks/fixtures/checklistQuestions.ts
  frontend/src/pages/LandingPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/routers/AuthGuard.tsx
  frontend/src/routers/router.tsx
  frontend/src/styles/animation.ts
  frontend/webpack.config.js
Labels: 🔑 FE, 🎨 UI

#464 [FE] roomInfoStore를 리팩토링한다.
  frontend/src/components/NewChecklist/NewRoomInfoForm/Address.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomStructure.tsx
  frontend/src/components/_common/Dropdown/Dropdown.tsx
  frontend/src/hooks/useChecklistPost.ts
  frontend/src/pages/EditChecklistPage.tsx
  frontend/src/store/checklistRoomInfoStore.test.ts
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/src/store/createFormStore.ts
  frontend/src/types/room.ts
  frontend/src/utils/validation.ts
Labels: 🔑 FE, 🔧 Refactor

#463 [FE] 체크리스트 작성 질문의 키워드를 하이라이팅한다.
  frontend/src/components/ChecklistCustom/QuestionCardList/QuestionCardList.stories.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/_common/Highlight/HighlightText.tsx
  frontend/src/constants/routePath.ts
  frontend/src/mocks/fixtures/checklistDetail.ts
  frontend/src/mocks/fixtures/checklistQuestions.ts
  frontend/src/pages/LandingPage.tsx
  frontend/src/routers/AuthGuard.tsx
  frontend/src/routers/router.tsx
  frontend/src/types/checklist.ts
Labels: 🔑 FE, 😊 Feature, 🎨 UI

#457 [BE] 로그아웃 기능을 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AuthPrincipalArgumentResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/CookieProvider.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
Labels: 🔒 BE, 😊 Feature

#467 [BE] 질문 조회시 하이라이트를 함께 전달한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Question.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/CustomChecklistQuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/QuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/SelectedQuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
Labels: 🔒 BE, 😊 Feature

#469 [FE] N번째 방을 기본입력으로 구현한다
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomName.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/useDefaultRoomName.ts
  frontend/src/mocks/fixtures/checklistList.ts
  frontend/src/store/checklistRoomInfoStore.ts
Labels: 🔑 FE, 😊 Feature

#471 [FE] 폰트 적용 안되는 오류를 수정한다.
  frontend/index.html
  frontend/src/assets/fonts/SUITE-Variable.woff2
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/styles/font.ts
  frontend/src/styles/global.ts
Labels: 🐛 Bug, 🔑 FE

#470 [BE] 체크리스트 작성, 수정, 삭제 API에 변경된 데이터를 반영한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/article/domain/Article.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/request/ArticleCreateRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticleDetailPreviewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticleResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Checklist.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/ChecklistMaintenance.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/MaintenanceItem.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Question.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/request/ChecklistRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistMaintenanceRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistOptionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistQuestionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/domain/Room.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/domain/Type.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/request/RoomRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/response/SelectedRoomResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/repository/RoomRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
  backend/bang-ggood/src/main/resources/data.sql
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/article/repository/ArticleRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/ChecklistTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/domain/MaintenanceItemTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistMaintenanceRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistQuestionRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/RoomFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/domain/RoomTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/domain/TypeTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/repository/RoomRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/station/SubwayStationServiceTest.java
  backend/bang-ggood/src/test/resources/data-test.sql
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE, 😊 Feature

#474 [FE] 기초적인 번들 코드스플리팅을 적용해서 warning을 해결한다.
  frontend/package.json
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: 🔑 FE

#475 [FE] 리액트 쿼리로 변경되지 않은 코드 및 자잘한 수정사항을 진행한다.
  frontend/src/components/Landing/FourthSection.tsx
  frontend/src/constants/system.ts
  frontend/src/hooks/query/useAddUserQuery.ts
  frontend/src/pages/ChecklistDetailPage.tsx
  frontend/src/pages/EditChecklistPage.tsx
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/LandingPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/pages/SaveCheckListPage.tsx
Labels: 🐛 Bug, 🔑 FE

#480 [FE] includedMaintenances 바뀐 api spec을 적용한다.
  frontend/src/components/NewChecklist/NewRoomInfoForm/IncludedMaintenances.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/IncludedUtilities.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/MaintenanceFee.tsx
  frontend/src/constants/includedMaintenances.ts
  frontend/src/constants/roomInfo.ts
  frontend/src/hooks/useChecklistPost.ts
  frontend/src/store/checklistIncludedMaintenancesStore.ts
  frontend/src/store/checklistIncludedUtilitesStore.ts
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/src/types/room.ts
Labels: 🔑 FE, 😊 Feature

#481 [FE] 카테고리에 이모지를 추가한다.
  frontend/src/App.tsx
  frontend/src/components/ChecklistList/ChecklistCard.tsx
  frontend/src/components/_common/Tabs/Tab.tsx
  frontend/src/components/_common/Tabs/Tabs.tsx
  frontend/src/components/skeleton/ChecklistList/SkChecklistLst.tsx
  frontend/src/constants/category.ts
  frontend/src/hooks/useNewChecklistTabs.ts
  frontend/src/mocks/fixtures/category.ts
  frontend/src/mocks/fixtures/checklistQuestions.ts
  frontend/src/pages/LandingPage.tsx
  frontend/src/types/category.ts
Labels: 🔑 FE, 🎨 UI

#486 커스텀 질문 조회 response를 수정한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/CustomChecklistQuestionResponse.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
Labels: 🐛 Bug, 🔒 BE

#487 [FE] 바뀐 주소타입으로 변경한다.
  frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
  frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
  frontend/src/components/_common/Map/RealTimeMap.tsx
  frontend/src/hooks/useChecklistPost.ts
  frontend/src/mocks/fixtures/checklistDetail.ts
  frontend/src/store/checklistAddressStore.ts
  frontend/src/types/room.ts
Labels: 🔑 FE, 🔧 Refactor

#491 [BE] 체크리스트 리스트 API를 수정한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/UserChecklistPreviewResponse.java
Labels: 🔒 BE, 😊 Feature

#492 [BE] dev-be와 dev 브랜치를 병합한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/UserChecklistPreviewResponse.java
Labels: 🔒 BE

#493 [BE] 아티클을 추가한다.
  backend/bang-ggood/src/main/resources/data.sql
Labels: 🔒 BE, 😊 Feature

#494 [FE] QA에서나온 자잘한 수정사항을 반영한다.
  frontend/src/assets/assets.tsx
  frontend/src/assets/icons/room/pencil.svg
  frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomName.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/useDefaultRoomName.ts
  frontend/src/hooks/useInitialChecklist.ts
  frontend/src/mocks/fixtures/checklistDetail.ts
  frontend/src/pages/EditChecklistPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/webpack.config.js
Labels: 🐛 Bug, 🔑 FE, 😊 Feature, 🎨 UI

#503 [BE] 아티클 취소선을 제거한다.
  backend/bang-ggood/src/main/resources/data.sql
Labels: 🐛 Bug, 🔒 BE

#511 [BE] 로그아웃이 안되는 문제를 해결한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/exception/ExceptionCode.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
Labels: 🔒 BE, 😊 Feature

#509 [BE] 체크리스트를 최신순으로 조회한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistRepositoryTest.java
Labels: 🔒 BE, 😊 Feature

#514 [FE] QA - 로그아웃 기능 버그를 수정한다.
  frontend/src/components/Landing/FirstSection.tsx
  frontend/src/components/MyPage/LogoutModal.tsx
  frontend/src/hooks/query/useLogoutQuery.ts
  frontend/src/pages/ChecklistDetailPage.tsx
Labels: 🔑 FE

#515 [FE] png 이미지가 엑스박스 뜨는 버그를 해결한다.
  frontend/src/components/Landing/FourthSection.tsx
  frontend/src/components/Landing/SecondSection.tsx
  frontend/src/components/Landing/ThirdSection.tsx
  frontend/src/constants/category.ts
Labels: 🐛 Bug, 🔑 FE

#521 [BE] 로그아웃이 안되는 문제를 해결한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
Labels: 🔒 BE, 😊 Feature

#522 [FE] 디폴트 방 이름 날짜 버그를 수정한다.
  frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
  frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/useDefaultRoomName.ts
  frontend/src/constants/options.ts
  frontend/src/utils/typeFunctions.ts
Labels: 🐛 Bug, 🔑 FE

#523 [FE] 스크린샷을 수정한다.
  frontend/.gitignore
  frontend/public/image/customScreenShot.png
  frontend/src/components/ChecklistCustom/CustomTabs.tsx
  frontend/src/components/Landing/FourthSection.tsx
  frontend/src/components/_common/TipBox/TipBox.tsx
  frontend/src/mocks/fixtures/checklistAllQuestions.ts
Labels: 🔑 FE, 🎨 UI

#524 [BE] 로그아웃이 정상적으로 되지 않는 문제를 해결한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
Labels: 🐛 Bug, 🔒 BE

#528 [FE] html 내부에서 <%= => 템플릿 구문을 작동하게한다.
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/src/store/createFormStore.ts
  frontend/webpack.config.js
Labels: 🐛 Bug, 🔑 FE, ⚙ Chore

#530 [FE] QA - 모바일에서 UI 깨지거나 부족한 부분, 스켈레톤이 없는 부분을 고친다.
  frontend/src/apis/checklist.ts
  frontend/src/components/ChecklistList/NoChecklistTemplate.tsx
  frontend/src/components/Main/ArticleSection.tsx
  frontend/src/components/Main/ChecklistSection.tsx
  frontend/src/components/NewChecklist/NewChecklistTemplate.tsx
  frontend/src/components/NewChecklist/Option/OptionChecklistTemplate.tsx
  frontend/src/components/_common/Footer/Footer.tsx
  frontend/src/components/_common/FormField/FormField.tsx
  frontend/src/components/_common/Header/Header.tsx
  frontend/src/components/_common/Modal/Modal.tsx
  frontend/src/components/_common/layout/Layout.tsx
  frontend/src/components/skeleton/Article/SKArticleDetail.tsx
  frontend/src/components/skeleton/MyPage/SKMyPage.tsx
  frontend/src/constants/routePath.ts
  frontend/src/constants/style.ts
  frontend/src/hooks/query/usePutCheclistQuery.ts
  frontend/src/hooks/useInitialChecklist.ts
  frontend/src/mocks/fixtures/checklistList.ts
  frontend/src/mocks/fixtures/dummyChecklist.ts
  frontend/src/mocks/fixtures/roomsForCompare.ts
  frontend/src/pages/ArticleDetailPage.tsx
  frontend/src/pages/ArticleListPage.tsx
  frontend/src/pages/CategoryChoosePage.tsx
  frontend/src/pages/ChecklistDetailPage.tsx
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/EditChecklistPage.tsx
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/pages/NotFound.tsx
  frontend/src/routers/router.tsx
  frontend/src/styles/global.ts
Labels: 🔑 FE, 😊 Feature, 🎨 UI

#533 [FE] 지도가 첫 렌더링 될 때 상태가 반영되도록 수정한다.
  frontend/src/components/_common/Map/RealTimeMap.tsx
  frontend/src/index.tsx
  frontend/src/routers/router.tsx
  frontend/src/styles/animation.ts
Labels: 🔑 FE

#540 [FE] 체크리스트 수정페이지에서 post이 아닌 put이 날아가게한다.
  frontend/src/index.tsx
  frontend/src/mocks/handlers/checklist.ts
  frontend/src/pages/EditChecklistPage.tsx
Labels: 🔑 FE, 😊 Feature

#544 [FE] 체크리스트 수정페이지에서 방이름이 비어있을때 버그를 해결한다.
  frontend/src/components/NewChecklist/NewRoomInfoForm/useDefaultRoomName.ts
  frontend/src/pages/EditChecklistPage.tsx
  frontend/src/store/createFormStore.ts
  frontend/webpack.config.js
Labels: 🐛 Bug, 🔑 FE

#546 [FE] 디테일페이지의 좋아요버튼 불일치 버그를 해결한다
  frontend/src/components/_common/Like/LikeButton.tsx
Labels: 🐛 Bug, 🔑 FE

#553 [FE] hofix로 버튼 사이즈를 수정한다.
  frontend/src/components/_common/AlertModal/AlertModal.tsx
  frontend/src/components/_common/Button/Button.tsx
  frontend/src/index.tsx
Labels: 🐛 Bug

#554 [BE] 체크리스트 조회시 관리비를 포함한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/response/SelectedRoomResponse.java
Labels: 🐛 Bug, 🔒 BE

#555 [ALL] dev와 main을 병합한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/response/SelectedRoomResponse.java
  frontend/src/index.tsx
Labels: 🔒 BE, 🔑 FE

#559 [FE] hotfix인 자동화 버튼 워딩 수정 및 불필요한 박스를 삭제한다.
  frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/NearTransportation.tsx
Labels: 🐛 Bug, 🔑 FE
