Repository woowacourse-teams/2024-bang-ggood, pull requests merged in 2024-10, with the labels that each got.

#718 [FE] GA를 main에 배포한다.
  frontend/src/routers/GoogleAnalytics.tsx
  frontend/src/routers/router.tsx
Labels: 🔑 FE, 😊 Feature, 🌏 Infra

#720 [FE] 레이아웃이 두개씩 생기는 버그를 수정한다.
  frontend/src/routers/GoogleAnalytics.tsx
Labels: 🐛 Bug, 🔑 FE

#723 [BE] 커스텀 체크리스트 질문 조회 관련 api 구현 방식을 일치시킨다.
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/CustomChecklistQuestion.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
Labels: 🔒 BE, 🔧 Refactor

#725 [BE] Redierect URI를 여러 개 받을 수 있도록 카카오 로그인 구현 방식을 변경한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/CookieProvider.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/request/OauthLoginRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/OauthClient.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/jwt/JwtTokenProperties.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/jwt/JwtTokenProvider.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/oauth/OauthClient.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/oauth/OauthRequestProperties.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
  backend/bang-ggood/src/test/java/com/bang_ggood/AcceptanceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/JwtTokenProviderFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/OauthFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/LoginMockE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/JwtTokenProviderTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/OauthPropertiesTest.java
Labels: 🔒 BE, 😊 Feature, 🔧 Refactor

#728 [FE] 전반적인 페이지 UI에 적절한 시맨틱 태그를 적용한다.
  frontend/src/components/ChecklistCustom/QuestionCardList/QuestionCardList.tsx
  frontend/src/components/ChecklistCustom/QuestionListTemplate/QuestionListTemplate.tsx
  frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
  frontend/src/components/NewChecklist/NewChecklistContent.tsx
  frontend/src/components/_common/Accordion/Accordion.tsx
  frontend/src/components/_common/Modal/Modal.tsx
  frontend/src/components/_common/Tabs/Tabs.tsx
  frontend/src/components/_common/TipBox/TipBox.tsx
  frontend/src/components/_common/layout/Layout.tsx
  frontend/src/components/skeleton/Article/SkArticleList.tsx
  frontend/src/pages/ArticleDetailPage.tsx
  frontend/src/pages/ArticleListPage.tsx
  frontend/src/pages/CategoryChoosePage.tsx
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/LandingPage.tsx
  frontend/src/pages/MyPage.tsx
Labels: 🔑 FE, 😊 Feature, 🎨 UI

#738 [BE] DEV와 DEV-BE 브랜치를 병합한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/CookieProvider.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/request/OauthLoginRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/OauthClient.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/jwt/JwtTokenProperties.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/jwt/JwtTokenProvider.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/oauth/OauthClient.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/oauth/OauthRequestProperties.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/CustomChecklistQuestion.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/AcceptanceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/JwtTokenProviderFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/OauthFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/LoginMockE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/JwtTokenProviderTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/OauthPropertiesTest.java
Labels: 🔒 BE

#741 fix: Redirect Uri 값 저장하는 과정에서 발생하는 에러 해결
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/oauth/OauthRequestProperties.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/OauthPropertiesTest.java
Labels: 🐛 Bug, 🔒 BE

#742 [BE] DEV와 DEV-BE 브랜치를 병합한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/oauth/OauthRequestProperties.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/OauthPropertiesTest.java
Labels: 🐛 Bug, 🔒 BE

#744 [BE] Location URI를 프론트 기준으로 변경한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
Labels: 🐛 Bug, 🔒 BE

#745 [BE] DEV와 DEV-BE를 병합한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
Labels: 🐛 Bug, 🔒 BE

#731 [BE] Lombok을 적용한다.
  backend/bang-ggood/build.gradle
  backend/bang-ggood/src/main/java/com/bang_ggood/article/domain/Article.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Checklist.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/like/domain/ChecklistLike.java
  backend/bang-ggood/src/main/java/com/bang_ggood/like/service/ChecklistLikeManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/like/service/ChecklistLikeService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/maintenance/domain/ChecklistMaintenance.java
  backend/bang-ggood/src/main/java/com/bang_ggood/maintenance/service/ChecklistMaintenanceService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/option/domain/ChecklistOption.java
  backend/bang-ggood/src/main/java/com/bang_ggood/option/service/ChecklistOptionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/ChecklistQuestion.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/CustomChecklistQuestion.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/Question.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/domain/Room.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/service/RoomService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/domain/SubwayStation.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/User.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/service/UserService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/ChecklistQuestionRepositoryTest.java
Labels: 🔒 BE, ⚙ Chore, 😊 Feature

#751 [BE] CORS 설정에 exposedHeader를 추가한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/CorsConfig.java
Labels: 🔒 BE, 🔧 Refactor

#752 [BE] DEV와 DEV-BE를 병합한다.
  backend/bang-ggood/build.gradle
  backend/bang-ggood/src/main/java/com/bang_ggood/article/domain/Article.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/OauthInfoApiResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/Checklist.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/DBInitializer.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/CorsConfig.java
  backend/bang-ggood/src/main/java/com/bang_ggood/like/domain/ChecklistLike.java
  backend/bang-ggood/src/main/java/com/bang_ggood/like/service/ChecklistLikeManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/like/service/ChecklistLikeService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/maintenance/domain/ChecklistMaintenance.java
  backend/bang-ggood/src/main/java/com/bang_ggood/maintenance/service/ChecklistMaintenanceService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/option/domain/ChecklistOption.java
  backend/bang-ggood/src/main/java/com/bang_ggood/option/service/ChecklistOptionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/ChecklistQuestion.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/CustomChecklistQuestion.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/Question.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/domain/Room.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/service/RoomService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/domain/SubwayStation.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/LoginType.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/User.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/service/UserService.java
  backend/bang-ggood/src/main/resources/data.sql
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/ArgumentResolverTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/ChecklistQuestionRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/UserFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/repository/UserRepositoryTest.java
  backend/bang-ggood/src/test/resources/data-test.sql
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE

#734 [FE] 좋아요 낙관적 업데이트 수정하여 API 실패 시 상태 롤백 추가한다.
  frontend/src/components/_common/Like/LikeButton.tsx
  frontend/src/hooks/query/useToggleLikeQuery.ts
  frontend/src/pages/MyPage.tsx
Labels: 🐛 Bug, 🔑 FE, 😊 Feature

#756 [FE] 로그인 처리 및 경로를 변경된 기획에 따라 반영한다.
  frontend/src/apis/user.ts
  frontend/src/components/Landing/FirstSection.tsx
  frontend/src/components/_common/KakaoLogin/KakaoLoginButton.tsx
  frontend/src/components/_common/Modal/LoginModal/LoginModal.tsx
  frontend/src/constants/oAuth.ts
  frontend/src/hooks/query/useAddUserQuery.ts
  frontend/src/hooks/useLogin.ts
  frontend/src/hooks/useMutateChecklist.ts
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/routers/router.tsx
Labels: 🔑 FE, 😊 Feature

#753 [BE] 체크리스트에 지하철을 2개 이상 저장할 수 있게 한다.(작성/조회)
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/request/ChecklistRequestV1.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/SelectedChecklistResponseV1.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/room/dto/response/SelectedRoomResponseV1.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/controller/SubwayStationController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/domain/ChecklistStation.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/dto/request/ChecklistStationRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/dto/response/SubwayStationResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/dto/response/SubwayStationResponses.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/repository/ChecklistStationRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/service/ChecklistStationService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/station/repository/ChecklistRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/station/service/ChecklistStationServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/station/service/SubwayStationServiceTest.java
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE, 😊 Feature

#754 [BE] 토큰 관련 코드를 리팩토링한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AuthRequiredPrincipalArgumentResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/UserPrincipalArgumentResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/CookieResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/cookie/CookieProvider.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/cookie/CookieResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/jwt/JwtTokenProperties.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/jwt/JwtTokenProvider.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/jwt/JwtTokenResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/WebMvcConfig.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
  backend/bang-ggood/src/test/java/com/bang_ggood/AcceptanceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/JwtTokenFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/ArgumentResolverTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/cookie/CookieResolverTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/cookie/LoginMockE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/JwtTokenProviderTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/like/controller/ChecklistLikeE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/controller/QuestionE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/controller/UserE2ETest.java
Labels: 🔒 BE, 🔧 Refactor

#761 [FE] playwright 초기세팅한다.
  .github/workflows/playwright.yml
  frontend/.gitignore
  frontend/jest.config.js
  frontend/package.json
  frontend/playwright.config.ts
  frontend/src/e2e/newChecklist.spec.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: 🔑 FE

#765 [FE] 접근성 개선을 위해 폼의 에러 메세지와 탭으로 이동하는 기능을 추가한다.
  frontend/src/components/_common/Button/Button.tsx
  frontend/src/components/_common/FormField/FormField.tsx
  frontend/src/components/_common/Header/Header.tsx
Labels: 🔑 FE, 🔧 Refactor

#768 [FE] 스토리북의 버그를 고치고, 관련 컴포넌트를 일부 수정한다.
  frontend/.gitignore
  frontend/.storybook/preview.tsx
  frontend/playwright-report/index.html
  frontend/src/apis/checklist.ts
  frontend/src/components/Answer/AnswerIcon.tsx
  frontend/src/components/ChecklistDetail/CheckListAnswer.tsx
  frontend/src/components/ChecklistList/ChecklistPreviewCard.stories.tsx
  frontend/src/components/ChecklistQuestionSelect/ChecklistQuestionSelectTabs.tsx
  frontend/src/components/ChecklistQuestionSelect/QuestionCardList/QuestionCardList.stories.tsx
  frontend/src/components/ChecklistQuestionSelect/QuestionCardList/QuestionCardList.tsx
  frontend/src/components/ChecklistQuestionSelect/QuestionListTemplate/QuestionListTemplate.tsx
  frontend/src/components/ChecklistQuestionSelect/QuestionSelectCard/QuestionSelectCard.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/styled.tsx
  frontend/src/components/NewChecklist/Option/OptionAllSelectBox.tsx
  frontend/src/components/NewChecklist/Option/OptionButton/OptionButton.stories.tsx
  frontend/src/components/_common/Accordion/Accordion.stories.tsx
  frontend/src/components/_common/Accordion/AccordionBody.tsx
  frontend/src/components/_common/Checkbox/Checkbox.stories.tsx
  frontend/src/components/_common/Checkbox/Checkbox.tsx
  frontend/src/components/_common/Dropdown/Dropdown.stories.tsx
  frontend/src/components/_common/FloatingButton/FloatingButton.stories.tsx
  frontend/src/components/_common/FloatingButton/FloatingButton.tsx
  frontend/src/components/_common/Modal/Modal.stories.tsx
  frontend/src/components/_common/RadioGroup/RadioContext.ts
  frontend/src/components/_common/RadioGroup/RadioGroup.stories.tsx
  frontend/src/components/_common/RadioGroup/RadioGroup.tsx
  frontend/src/components/_common/Tabs/Tab.tsx
  frontend/src/components/_common/TipBox/TipBox.stories.tsx
  frontend/src/constants/routePath.ts
  frontend/src/hooks/useChecklistQuestionSelect.ts
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/ChecklistQuestionSelectPage.tsx
  frontend/src/routers/router.tsx
  frontend/src/store/useChecklistQuestionSelectStore.ts
  frontend/src/types/checklist.ts
  frontend/test-results/.last-run.json
Labels: 🐛 Bug, 🔑 FE, 🔧 Refactor, 🎨 UI

#770 [FE] playwright를 CI 설정한다.
  .github/workflows/playwright.yml
  frontend/README.md
  frontend/playwright.config.ts
  frontend/src/e2e/newChecklist.spec.ts
Labels: 🔑 FE, ⚙ Chore, 🌏 Infra, 🧪 Test

#767 [BE] 토큰 확인하는 API를 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AuthRequiredPrincipalArgumentResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/UserPrincipalArgumentResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/cookie/CookieResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/RefreshTokenCheckResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/repository/ChecklistStationRepository.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/cookie/CookieResolverTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
Labels: 🔒 BE, 😊 Feature

#773 [FE] 랜딩 페이지를 클릭으로 섹션을 이동할 수 있게 리팩토링한다.
  frontend/playwright-report/index.html
  frontend/src/components/Landing/FifthSection.tsx
  frontend/src/components/Landing/FirstSection.tsx
  frontend/src/components/Landing/FourthSection.tsx
  frontend/src/components/Landing/SecondSection.tsx
  frontend/src/components/Landing/ThirdSection.tsx
  frontend/src/components/Landing/style.ts
  frontend/src/components/_common/FloatingButton/FloatingButton.tsx
  frontend/src/components/_common/KakaoLogin/KakaoLoginButton.tsx
  frontend/src/hooks/useMoveSection.ts
  frontend/src/pages/LandingPage.tsx
  frontend/src/styles/animation.ts
  frontend/src/styles/theme.ts
Labels: 🔑 FE, 🎨 UI

#780 [BE] 테이블 drop 순서 오류 수정
  backend/bang-ggood/src/main/resources/schema.sql
Labels: 🐛 Bug, 🔒 BE

#774 [BE] 회원가입 기능을 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/request/RegisterRequestV1.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/PasswordEncoder.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/DBInitializer.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/Email.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/Password.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/User.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/dto/UserResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
  backend/bang-ggood/src/main/resources/data.sql
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/ArgumentResolverTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/station/service/ChecklistStationServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/UserFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/controller/UserE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/domain/EmailTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/domain/PasswordTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/repository/UserRepositoryTest.java
  backend/bang-ggood/src/test/resources/data-test.sql
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE

#795 [BE] 로케이션 헤더를 수정한다
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
Labels: 🐛 Bug, 🔒 BE

#783 [FE] 바뀐 포스트 api 의 포맷에 맞게 로직을 수정한다.
  frontend/src/apis/checklist.ts
  frontend/src/apis/url.ts
  frontend/src/components/NewChecklist/AddressModal/RealTimeAddressModal.tsx
  frontend/src/components/_common/Map/AddressMap.tsx
  frontend/src/components/_common/Map/RealTimeMap.tsx
  frontend/src/constants/map.ts
  frontend/src/hooks/useMoveSection.ts
  frontend/src/hooks/useMutateChecklist.ts
  frontend/src/hooks/useRoomInfoNonValidated.ts
  frontend/src/mocks/handlers/subway.ts
  frontend/src/pages/ChecklistDetailPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/store/roomInfoNonValidatedStore.ts
  frontend/src/types/address.ts
  frontend/src/types/checklist.ts
  frontend/src/utils/createKakaoMapElements.ts
Labels: 🔑 FE, 😊 Feature

#793 [FE] 토스트 에러 핸들링 리팩토링 및 시나리오 개편을 진행한다.
  frontend/src/App.tsx
  frontend/src/assets/assets.tsx
  frontend/src/assets/icons/toast/toast-confirm.svg
  frontend/src/assets/icons/toast/toast-error.svg
  frontend/src/components/_common/Toast/Toast.stories.tsx
  frontend/src/components/_common/Toast/Toast.tsx
  frontend/src/components/_common/Toast/ToastContainer.tsx
  frontend/src/hooks/query/useToggleLikeQuery.ts
  frontend/src/hooks/useMutateChecklist.ts
  frontend/src/hooks/useToast.test.ts
  frontend/src/hooks/useToast.ts
  frontend/src/pages/CategoryChoosePage.tsx
  frontend/src/pages/ChecklistQuestionSelectPage.tsx
  frontend/src/store/useToastStore.ts
  frontend/src/types/toast.ts
Labels: 🔑 FE, 😊 Feature

#787 [BE] 토큰 무효화 api를 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
Labels: 🔒 BE, 😊 Feature

#800 [BE] 액세스 토큰 존재 여부를 반환한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/cookie/CookieResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/RefreshTokenCheckResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/dto/response/TokenExistResponse.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
Labels: 🔒 BE, 😊 Feature

#789 [BE] 방끗 자체 에러코드를 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/BangggoodException.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ClientExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/dto/ExceptionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/handler/GlobalExceptionHandler.java
Labels: 🔒 BE, 😊 Feature

#801 [BE] 로그아웃 path를 변경한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
Labels: 🔒 BE, 😊 Feature

#739 [BE] 좋아요 중복 요청 시 정상 상태코드 반환 및 중복 저장을 방지한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/like/controller/ChecklistLikeController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/like/repository/ChecklistLikeRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/like/service/ChecklistLikeService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/like/controller/ChecklistLikeE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/like/service/ChecklistLikeManageServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/like/service/ChecklistLikeServiceTest.java
Labels: 🔒 BE, 😊 Feature

#808 [BE] 회원 탈퇴를 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/repository/UserRepositoryTest.java
Labels: 🔒 BE, 😊 Feature

#782 [FE] 자동 로그인 기능 및 토큰 재발행 로직을 구현한다.
  frontend/playwright-report/index.html
  frontend/src/apis/checklist.ts
  frontend/src/apis/error/ErrorMessage.ts
  frontend/src/apis/error/HttpError.ts
  frontend/src/apis/fetcher.ts
  frontend/src/apis/url.ts
  frontend/src/apis/user.ts
  frontend/src/components/Landing/ThirdSection.tsx
  frontend/src/e2e/newChecklist.spec.ts
  frontend/src/hooks/useAutoLogin.ts
  frontend/src/hooks/useChecklistQuestionSelect.ts
  frontend/src/mocks/fixtures/user.ts
  frontend/src/mocks/handlers/user.ts
  frontend/src/pages/LandingPage.tsx
  frontend/src/types/user.ts
Labels: 🔑 FE, 😊 Feature

#809 [FE] roomInfoStore의 구조변경을 수행한다.
  frontend/.eslintrc.json
  frontend/playwright-report/index.html
  frontend/src/apis/checklist.ts
  frontend/src/apis/fetcher.ts
  frontend/src/components/NewChecklist/MemoModal/MemoModal.tsx
  frontend/src/components/NewChecklist/NewChecklistContent.tsx
  frontend/src/components/NewChecklist/NewChecklistTemplate.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/DepositAndRent.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/IncludedMaintenances.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/MaintenanceFee.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/OccupancyMonth.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RealEstate.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomContractTerm.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomFloor.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomName.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomNameNoDefault.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomSize.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomStructure.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/useDefaultRoomName.ts
  frontend/src/components/NewChecklist/SubmitModalWithSummary/SubmitModalWithSummary.tsx
  frontend/src/components/_common/Subway/SubwayStations.tsx
  frontend/src/hooks/useMutateChecklist.ts
  frontend/src/hooks/useRoomInfoValidated.test.ts
  frontend/src/hooks/useRoomInfoValidated.ts
  frontend/src/mocks/handlers/checklist.ts
  frontend/src/pages/EditChecklistPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/store/checklistRoomInfoStore.test.ts
  frontend/src/store/checklistRoomInfoStore.ts
  frontend/src/store/createFormStore.ts
  frontend/src/store/roomInfoStore.ts
  frontend/src/types/checklist.ts
  frontend/src/types/room.ts
  frontend/src/utils/typeFunctions.ts
  frontend/src/utils/utilityTypes.ts
Labels: 🔑 FE, 😊 Feature, 🔧 Refactor

#815 [FE] 탭 스토어와 체크리스트 스토어 리팩토링을 진행한다.
  frontend/src/apis/fetcher.ts
  frontend/src/components/ChecklistQuestionSelect/ChecklistQuestionSelectTabs.tsx
  frontend/src/components/EditChecklist/ChecklistTab/EditChecklistTab.tsx
  frontend/src/components/NewChecklist/ChecklistContent.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestionAnswers.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestionTemplate.tsx
  frontend/src/components/NewChecklist/ChecklistTab/ChecklistTab.tsx
  frontend/src/components/NewChecklist/ChecklistTab/ChecklistTabFallback.tsx
  frontend/src/components/NewChecklist/ChecklistTab/NewChecklistTab.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomInfoTemplate.tsx
  frontend/src/components/_common/Tabs/TabButton.tsx
  frontend/src/components/_common/Tabs/Tabs.stories.tsx
  frontend/src/components/_common/Tabs/Tabs.tsx
  frontend/src/components/_common/errorBoundary/ChecklistTabFallback.tsx
  frontend/src/constants/tabs.ts
  frontend/src/hooks/useChecklistQuestionAnswer.ts
  frontend/src/hooks/useChecklistTabs.ts
  frontend/src/hooks/useInitialChecklist.ts
  frontend/src/hooks/useTabs.ts
  frontend/src/pages/ChecklistQuestionSelectPage.tsx
  frontend/src/pages/EditChecklistPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/types/tab.ts
Labels: 🔑 FE, 😊 Feature, 🔧 Refactor

#819 [BE] 파라미터 오류 시 에러 메시지를 정상적으로 수정한다
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ClientExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/handler/GlobalExceptionHandler.java
Labels: 🐛 Bug, 🔒 BE

#832 [BE] 없어진 아티클을 복구한다.
  backend/bang-ggood/src/main/resources/data.sql
Labels: 🐛 Bug, 🔒 BE

#817 [FE] 좋아요 필터링 기능을 구현한다.
  frontend/public/index.html
  frontend/src/apis/checklist.ts
  frontend/src/apis/url.ts
  frontend/src/components/ChecklistList/ChecklistListContainer.tsx
  frontend/src/components/ChecklistList/ChecklistListTitle.tsx
  frontend/src/components/_common/FlexBox/FlexBox.tsx
  frontend/src/hooks/query/useGetChecklistListQuery.ts
  frontend/src/hooks/useGetChecklistList.ts
  frontend/src/mocks/handlers/checklist.ts
  frontend/src/pages/ChecklistListPage.tsx
Labels: 🔑 FE

#816 [FE] 일반 회원가입과 로그인을 개발한다.
  frontend/src/apis/error/HttpError.ts
  frontend/src/apis/fetcher.ts
  frontend/src/apis/url.ts
  frontend/src/apis/user.ts
  frontend/src/components/Landing/FirstSection.tsx
  frontend/src/components/Landing/style.ts
  frontend/src/components/_common/Accordion/AccordionContext.tsx
  frontend/src/components/_common/Tabs/TabContext.tsx
  frontend/src/constants/message/errorMessage.ts
  frontend/src/constants/message/httpErrorMessage.ts
  frontend/src/constants/message/validationErrorMessage.ts
  frontend/src/constants/routePath.ts
  frontend/src/hooks/useValidateInput.ts
  frontend/src/mocks/handlers/user.ts
  frontend/src/pages/SignInPage.tsx
  frontend/src/pages/SignUpPage.tsx
  frontend/src/routers/router.tsx
  frontend/src/utils/authValidation.ts
Labels: 🔑 FE, 😊 Feature, 🎨 UI

#839 [BE] 무중단 배포 파일을 업데이트 한다.
  .github/workflows/backend-prod-cd.yml
Labels: 🔒 BE, 😊 Feature

#842 [BE] 질문이 없는 카테고리는 보내지 않도록 수정한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/CategoryRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/CustomChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/QuestionFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/CategoryRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/ChecklistQuestionRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/ChecklistQuestionServiceTest.java
Labels: 🔒 BE, 🔧 Refactor

#848 [BE] 무중단 배포에서 health-check 부분을 추가한다.
  .github/workflows/backend-prod-cd.yml
Labels: 🔒 BE, 🌏 Infra

#850 [BE] 무중단 배포에서 health-check 부분을 추가한다.
  .github/workflows/backend-prod-cd.yml
Labels: 🔒 BE, 🌏 Infra

#836 [FE] 에러 코드 작업 및 메세지 맵핑을 진행한다.
  frontend/src/apis/error/APIError.ts
  frontend/src/apis/error/ErrorMessage.ts
  frontend/src/apis/error/HttpError.ts
  frontend/src/apis/fetcher.ts
  frontend/src/components/NewChecklist/SubmitModalWithSummary/SubmitModalWithSummary.tsx
  frontend/src/components/_common/Accordion/AccordionContext.tsx
  frontend/src/components/_common/Tabs/TabContext.tsx
  frontend/src/components/_common/TipBox/TipBox.tsx
  frontend/src/constants/message/httpErrorMessage.ts
  frontend/src/constants/messages/apiErrorMessage.ts
  frontend/src/constants/messages/errorMessage.ts
  frontend/src/constants/messages/message.ts
  frontend/src/constants/messages/validationErrorMessage.ts
  frontend/src/hooks/query/useToggleLikeQuery.ts
  frontend/src/hooks/useMutateChecklist.ts
  frontend/src/hooks/useValidateInput.ts
  frontend/src/mocks/handlers/checklist.ts
  frontend/src/mocks/handlers/like.ts
  frontend/src/pages/CategoryChoosePage.tsx
  frontend/src/pages/ChecklistQuestionSelectPage.tsx
  frontend/src/pages/ErrorPage.tsx
Labels: 🔑 FE, 😊 Feature

#849 [FE] playwright에 자동 로그인 기능과 탭과 질문 렌더링, 체크리스트 생성과 관련된 e2e 테스트를 추가한다.
  .github/workflows/playwright.yml
  frontend/.gitignore
  frontend/package.json
  frontend/playwright.api.config.ts
  frontend/playwright.mock.config.ts
  frontend/playwright/tests/api/auth.setup.ts
  frontend/playwright/tests/api/postNewChecklist.spec.ts
  frontend/playwright/tests/api/renderTab.spec.ts
  frontend/playwright/tests/constants/constants.ts
  frontend/playwright/tests/mock/postNewChecklist.spec.ts
  frontend/src/components/ChecklistQuestionSelect/QuestionSelectCard/QuestionSelectCard.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/NewChecklist/ChecklistTab/NewChecklistTab.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/OccupancyMonth.tsx
  frontend/src/components/NewChecklist/Option/OptionButton/OptionButton.tsx
  frontend/src/components/_common/Button/Button.tsx
  frontend/src/components/_common/Dropdown/Dropdown.tsx
  frontend/src/components/_common/Map/RealTimeMap.tsx
  frontend/src/components/_common/Modal/FocusTrap/FocusTrap.tsx
  frontend/src/components/_common/Modal/Modal.tsx
  frontend/src/components/_common/Modal/ModalBody.tsx
  frontend/src/components/_common/Modal/ModalHeader.tsx
  frontend/src/components/_common/Tabs/TabButton.tsx
  frontend/src/components/_common/Tabs/Tabs.stories.tsx
  frontend/src/constants/category.ts
  frontend/src/constants/routePath.ts
  frontend/src/constants/tabs.ts
  frontend/src/mocks/fixtures/checklistDetail.ts
  frontend/src/pages/ChecklistDetailPage.tsx
  frontend/src/pages/ChecklistQuestionSelectPage.tsx
  frontend/src/store/useChecklistStore.ts
  frontend/tsconfig.json
  frontend/webpack.common.js
Labels: 🔑 FE, 😊 Feature, 🧪 Test

#851 [FE] roomInfoStore변경을 Nonvalidated에 반영한다.
  frontend/a.ts
  frontend/playwright.api.config.ts
  frontend/playwright/tests/api/postNewChecklist.spec.ts
  frontend/playwright/tests/api/renderTab.spec.ts
  frontend/src/apis/checklist.ts
  frontend/src/components/ChecklistList/ChecklistCard.tsx
  frontend/src/components/NewChecklist/AddressModal/DaumAddressModal.tsx
  frontend/src/components/NewChecklist/AddressModal/RealTimeAddressModal.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/Address.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomName.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/useDefaultRoomName.ts
  frontend/src/hooks/useMutateChecklist.ts
  frontend/src/hooks/useRoomInfoNonValidated.ts
  frontend/src/pages/EditChecklistPage.tsx
  frontend/src/store/roomInfoNonValidatedStore.ts
  frontend/src/store/roomInfoStore.ts
Labels: 🔑 FE, 😊 Feature

#853 [FE] 구글 상단 검색을 위해 OG 태그 및 구글 서치 작업을 진행한다.
  frontend/public/bang-ggood-thumbnail.png
  frontend/public/index.html
  frontend/src/apis/fetcher.ts
Labels: 🔑 FE, 😊 Feature

#858 [BE] 스키마 변경에 따른 무중단 배포를 진행한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/ChecklistQuestion.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/CustomChecklistQuestion.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/Question.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/QuestionEntity.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CustomChecklistQuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/QuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/SelectedQuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/ChecklistQuestionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/HighlightRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/QuestionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/domain/ChecklistQuestionTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/QuestionManageServiceTest.java
Labels: 🔒 BE, 😊 Feature

#856 [BE] 회원가입 시 필요한 로직을 추가한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/repository/UserRepositoryTest.java
Labels: 🔒 BE, 😊 Feature

#814 [FE] 접근성 개선 작업인 모달, 포커스, 스크린리더 개선을 진행한다.
  frontend/.gitignore
  frontend/src/components/ChecklistList/CustomBanner.tsx
  frontend/src/components/ChecklistQuestionSelect/QuestionSelectCard/QuestionSelectCard.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestion.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestionAnswers.tsx
  frontend/src/components/NewChecklist/Option/OptionAllSelectBox.tsx
  frontend/src/components/NewChecklist/Option/OptionButton/OptionButton.tsx
  frontend/src/components/_common/Button/Button.tsx
  frontend/src/components/_common/Checkbox/Checkbox.tsx
  frontend/src/components/_common/Modal/AlertModal/AlertModal.tsx
  frontend/src/components/_common/Tabs/TabButton.tsx
  frontend/src/components/_common/Tabs/Tabs.tsx
  frontend/src/components/_common/TipBox/TipBox.tsx
  frontend/src/hooks/useAutoLogin.ts
  frontend/src/hooks/useChecklistQuestionAnswer.ts
  frontend/src/hooks/useChecklistQuestionSelect.ts
  frontend/src/index.css
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/pages/SignInPage.tsx
  frontend/src/pages/SignUpPage.tsx
  frontend/webpack.dev.js
Labels: 🔑 FE, 😊 Feature

#862 [FE] 사용자 트래킹을 위해 Amplitude 초기 설정 및 MVP 기능 트래킹을 지정한다.
  .github/workflows/playwright.yml
  frontend/a.ts
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/apis/url.ts
  frontend/src/apis/user.ts
  frontend/src/assets/images/og/bang-ggood-thumbnail.png
  frontend/src/components/Landing/FirstSection.tsx
  frontend/src/components/MyPage/LogoutModal.tsx
  frontend/src/components/MyPage/UserFeature.tsx
  frontend/src/components/NewChecklist/ChecklistQuestion/ChecklistQuestionAnswers.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomInfoTemplate.tsx
  frontend/src/components/NewChecklist/Option/OptionButton/OptionButton.tsx
  frontend/src/components/NewChecklist/SubmitModalWithSummary/SubmitModalWithSummary.tsx
  frontend/src/components/_common/KakaoLogin/KakaoLoginButton.tsx
  frontend/src/components/_common/Tabs/TabButton.tsx
  frontend/src/constants/messages/apiErrorMessage.ts
  frontend/src/hooks/useMutateChecklist.ts
  frontend/src/mocks/handlers/user.ts
  frontend/src/pages/ArticleListPage.tsx
  frontend/src/pages/ChecklistDetailPage.tsx
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/NewChecklistPage.tsx
  frontend/src/service/amplitude/AmplitudeInitializer.tsx
  frontend/src/service/amplitude/AmplitudeService.tsx
  frontend/src/service/amplitude/getBrowser.tsx
  frontend/src/service/amplitude/trackEvent.ts
  frontend/src/service/amplitude/useTrackPageView.ts
  frontend/webpack.common.js
  frontend/webpack.prod.js
  frontend/yarn.lock
Labels: 🔑 FE, 😊 Feature, 🌏 Infra

#874 [FE] public assets 에러 로그 및 og 커버 버그, 그리고 센트리 작동 안함 이슈를 해결한다.
  frontend/public/index.html
  frontend/src/apis/fetcher.ts
  frontend/src/pages/LandingPage.tsx
  frontend/src/sentry.ts
  frontend/webpack.common.js
Labels: 🐛 Bug, 🔑 FE

#886 [FE] UT피드백에 의한 편집 페이지 새로고침 로직 문제를 해결한다
  frontend/src/components/NewChecklist/NewRoomInfoForm/useDefaultRoomName.ts
  frontend/src/components/_common/Like/LikeButton.tsx
  frontend/src/components/_common/Modal/Modal.tsx
  frontend/src/routers/GoogleAnalytics.tsx
  frontend/src/routers/router.tsx
  frontend/src/store/roomInfoNonValidatedStore.ts
Labels: 🔑 FE, 🎨 UI

#888 [FE] QA 중 생겨난 작성 후 로그인 모달 워딩 수정 및 일반 로그인 기능을 추가한다.
  frontend/src/components/Landing/FirstSection.tsx
  frontend/src/components/_common/Highlight/HighlightText.tsx
  frontend/src/components/_common/LoginButton/EmailLoginButton.tsx
  frontend/src/components/_common/LoginButton/KakaoLoginButton.tsx
  frontend/src/components/_common/Modal/LoginModal/LoginModal.tsx
  frontend/src/pages/NewChecklistPage.tsx
Labels: 🔑 FE, 😊 Feature

#873 [BE] 스키마 변경에 따른 무중단 배포를 진행한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/DefaultChecklistService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/Category.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/CategoryEntity.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/ChecklistQuestion.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/CustomChecklistQuestion.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/Highlight.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/Question.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/QuestionEntity.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CategoryCustomChecklistQuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CategoryQuestionsResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CustomChecklistQuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/QuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/SelectedCategoryQuestionsResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/SelectedQuestionResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/CategoryRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/ChecklistQuestionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/QuestionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/ChecklistQuestionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/repository/UserRepository.java
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/ChecklistQuestionFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/CustomChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/QuestionFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/domain/QuestionTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/CategoryRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/QuestionRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/ChecklistQuestionServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/QuestionManageServiceTest.java
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE, 😊 Feature

#880 [BE] 체크리스트 조회 시 지하철 역 json 형태를 변경한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/SelectedChecklistResponseV1.java
Labels: 🔒 BE

#885 [BE] 회원 탈퇴 시 토큰을 삭제한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/controller/AuthController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/service/AuthService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/service/AuthServiceTest.java
Labels: 🔒 BE, 😊 Feature

#896 [BE] 체크리스트 목록 조회 시 지하철 json 형태를 변경한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistPreviewResponseV1.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistsPreviewResponseV1.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/dto/response/SubwayStationResponses.java
Labels: 🔒 BE, 😊 Feature

#900 [BE] 체크리스트 좋아요 필터링 버전을 업데이트한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistServiceTest.java
Labels: 🔒 BE, 😊 Feature

#893 [FE] checklist v1 변동사항을 메인 페이지 체크리스트 리스트 컴포넌트에 반영한다.
  frontend/playwright/tests/api/auth.setup.ts
  frontend/playwright/tests/api/postNewChecklist.spec.ts
  frontend/playwright/tests/api/renderTab.spec.ts
  frontend/playwright/tests/mock/postNewChecklist.spec.ts
  frontend/src/apis/checklist.ts
  frontend/src/components/Main/ChecklistPreviewCard.tsx
  frontend/src/components/_common/Subway/SubwayLineIcon/SubwayLineIcon.tsx
  frontend/src/mocks/fixtures/checklistList.ts
  frontend/src/mocks/handlers/checklist.ts
  frontend/src/types/checklist.ts
Labels: 🔑 FE, 😊 Feature

#904 [FE] QA 피드백 이후 체크리스트 디테일 페이지 UI/UX 를 개선한다.
  frontend/src/components/ChecklistDetail/RoomInfoSection.tsx
  frontend/src/components/ChecklistList/ChecklistCard.tsx
  frontend/src/components/_common/Subway/SubwayStations.tsx
  frontend/src/components/_common/layout/Layout.tsx
  frontend/src/utils/formattedUndefined.ts
Labels: 🔑 FE, 😊 Feature

#907 [FE] 좋아요 필터링 버튼을 로그인시에만 표시한다.
  frontend/src/components/ChecklistList/LikeFilterButton.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/query/useAddUserQuery.ts
  frontend/src/hooks/query/useGetIsUserValid.ts
  frontend/src/hooks/query/useLogoutQuery.ts
  frontend/src/hooks/query/useUserQuery.ts
  frontend/src/hooks/useGetChecklistList.ts
  frontend/src/pages/ChecklistListPage.tsx
Labels: 🔑 FE, 😊 Feature

#911 [FE] 편집 페이지에 들어갔을 때, 검증에 어긋나는 입력이 가능해지는 현상 해결한다.
  frontend/playwright.api.config.ts
  frontend/playwright.mock.config.ts
  frontend/src/apis/checklist.ts
Labels: 🐛 Bug, 🔑 FE

#916 [FE] 일반로그인시에 리액트쿼리로 invalidate하고 에러메시지 정상표시안되던 현상을 해결한다.
  frontend/src/apis/fetcher.ts
  frontend/src/apis/url.ts
  frontend/src/apis/user.ts
  frontend/src/hooks/query/useAddUserQuery.ts
  frontend/src/hooks/query/usePostSignInQuery.ts
  frontend/src/pages/SignInPage.tsx
Labels: 🐛 Bug, 🔑 FE, 😊 Feature

#918 [FE] 탭이 종종 랜더링되지 않고 터지는 버그를 수정한다.
  frontend/src/components/ChecklistQuestionSelect/ChecklistQuestionSelectTabs.tsx
  frontend/src/components/ChecklistQuestionSelect/QuestionListTemplate/QuestionListTemplate.tsx
  frontend/src/components/EditChecklist/ChecklistTab/EditChecklistTab.tsx
  frontend/src/components/NewChecklist/ChecklistTab/NewChecklistTab.tsx
  frontend/src/components/_common/errorBoundary/ChecklistTabSuspense.tsx
  frontend/src/components/skeleton/Main/SkChecklistSection.tsx
  frontend/src/components/skeleton/QuestionSelect/SKQuestionSelectList.tsx
  frontend/src/hooks/useInitialChecklist.ts
  frontend/src/store/useChecklistStore.ts
  frontend/src/utils/isSameCategory.ts
Labels: 🐛 Bug, 🔑 FE

#920 [FE] 메인페이지에 주소가없을때 역이름이 선릉역8분으로 뜨던에러를해결한다.
  frontend/src/components/Main/ChecklistPreviewCard.tsx
Labels: 🐛 Bug, 🔑 FE

#923 [FE] 좋아요를 매우 빨리 누를 때 빨리 변하게 한다.
  frontend/src/components/_common/Like/LikeButton.tsx
Labels: 🔑 FE, 😊 Feature

#926 [FE] 나가기 네이게이트 안되는 오류를 수정한다.
  frontend/src/pages/NewChecklistPage.tsx
Labels: 🔑 FE
