Repository woowacourse-teams/2024-bang-ggood, pull requests merged in 2024-12, with the labels that each got.

#1011 [BE] 아티클 생성, 삭제를 어드민만 접근하게 한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AdminPrincipal.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AdminPrincipalArgumentResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/WebMvcConfig.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/User.java
  backend/bang-ggood/src/test/java/com/bang_ggood/AcceptanceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/ArgumentResolverTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/TestController.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/UserFixture.java
Labels: 🔒 BE, 😊 Feature

#1022 [BE] 체크리스트 작성, 수정 API 요청시 중복된 위도, 경도정보를 삭제한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/request/ChecklistRequestV1.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/dto/request/ChecklistStationRequest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
Labels: 🔒 BE, 😊 Feature

#1027 [BE] PROD 서버에서 log 파일이 저장되지 않도록 한다.
  .github/workflows/backend-prod-cd.yml
Labels: 🔒 BE, 🌏 Infra

#1029 [BE] 아티클 리스트가 캐시되지 않도록 한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/global/cache/CacheTest.java
Labels: 🔒 BE, 🔧 Refactor

#1030 [BE] DEV와 DEV-BE를 병합한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/request/ChecklistRequestV1.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/dto/request/ChecklistStationRequest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/global/cache/CacheTest.java
Labels: 🔒 BE

#1031 [BE] 구현사항을 PROD에 배포한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AdminPrincipal.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/config/AdminPrincipalArgumentResolver.java
  backend/bang-ggood/src/main/java/com/bang_ggood/auth/repository/PasswordResetCodeRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/request/ChecklistRequestV1.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/config/WebMvcConfig.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/dto/request/ChecklistStationRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/user/domain/User.java
  backend/bang-ggood/src/test/java/com/bang_ggood/AcceptanceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/ArgumentResolverTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/config/TestController.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/global/cache/CacheTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/user/UserFixture.java
Labels: 🔒 BE

#1034 [BE] sql 파일에 ADMIN 계정을 생성한다.
  backend/bang-ggood/src/main/resources/data.sql
Labels: 🔒 BE, 😊 Feature

#1038 [BE] 지하철 역 응답에 도보 시간 제한을 둔다.
  backend/bang-ggood/src/main/java/com/bang_ggood/station/domain/SubwayStation.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/service/SubwayStationService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/station/service/ChecklistStationServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/station/service/SubwayStationServiceTest.java
Labels: 🔒 BE, 😊 Feature

#1044 [FE] 옥탑일 때 인풋 입력 막기
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomFloor.tsx
Labels: 🐛 Bug, 🔑 FE

#1040 [FE] 회원가입시 예외처리를 하고, 한줄평 글자 1칸초과하는것을 해결한다.
  frontend/package.json
  frontend/src/components/NewChecklist/SubmitModalWithSummary/SubmitModalWithSummary.tsx
  frontend/src/constants/system.ts
  frontend/src/hooks/query/usePostSignInQuery.ts
  frontend/src/hooks/query/usePostSignUpQuery.ts
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/RoomCompareSelectPage.tsx
  frontend/src/pages/SignUpPage.tsx
Labels: 🐛 Bug, 🔑 FE

#1046 [FE] 기존 체크리스트 스토어 스토리지를 localStorage 에서 sessionStorage로 변경한다.
  frontend/src/store/roomInfoNonValidatedStore.ts
  frontend/src/store/roomInfoStore.ts
  frontend/src/store/useChecklistStore.ts
  frontend/src/store/useSelectedOptionStore.ts
Labels: 🔑 FE, 🔧 Refactor

#1049 [FE] 아티클 에디터 열람 조건 처리 버그를 수정한다
  frontend/src/pages/AdminPage.tsx
  frontend/src/store/roomInfoNonValidatedStore.ts
  frontend/src/store/roomInfoStore.ts
  frontend/src/store/useChecklistStore.ts
  frontend/src/store/useSelectedOptionStore.ts
Labels: 🐛 Bug, 🔑 FE

#1060 [FE] 런칭 후 생긴 버그를 수정한다.
  frontend/src/components/NewChecklist/MoveNextButton.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomFloor.tsx
Labels: 🐛 Bug, 🔑 FE

#1061 [FE] 런칭 후 생긴 버그를 수정한다.
  frontend/src/components/NewChecklist/MoveNextButton.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomFloor.tsx
Labels: 🐛 Bug, 🔑 FE

#1065 [BE] 체크리스트 지하철 정보 저장 시 위도, 경도가 NULL 인 경우도 허용한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/service/ChecklistStationService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/RoomFixture.java
Labels: 🔒 BE, 😊 Feature

#1067 [BE] DEV와 DEV-BE를 병합한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/station/service/ChecklistStationService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/room/RoomFixture.java
Labels: 🔒 BE

#1072 [BE] 아티클 수정 기능을 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/domain/Article.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/request/ArticleUpdateRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/ArticleFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/controller/ArticleE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleServiceTest.java
Labels: 🔒 BE, 😊 Feature

#1074 [BE] 사용하지 않는 버전 코드를 제거한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/request/ChecklistRequestV1.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistCompareResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistCompareResponses.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistCompareResponsesV1.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistPreviewResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistPreviewResponseV1.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistsPreviewResponseV1.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/SelectedChecklistResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/SelectedChecklistResponseV1.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CategoryScoreResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CategoryScoreResponseV1.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CategoryScoreResponses.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/response/CategoryScoreResponsesV1.java
  backend/bang-ggood/src/test/java/com/bang_ggood/auth/controller/AuthE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/controller/ChecklistE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
Labels: 🔒 BE, 🔧 Refactor
