Repository woowacourse-teams/2024-bang-ggood, pull requests merged in 2025-01, with the labels that each got.

#1079 [BE] 아티클 조회수 기능을 캐시에 적용한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/Application.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/controller/ArticleController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/domain/Article.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticleResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/repository/ArticleRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleViewService.java
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/main/resources/seoul_stations_241218.csv
  backend/bang-ggood/src/test/java/com/bang_ggood/article/repository/ArticleRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleManageServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/article/service/ArticleViewServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/global/cache/CacheTest.java
  backend/bang-ggood/src/test/resources/schema-test.sql
  backend/bang-ggood/src/test/resources/seoul_stations_241218.csv
Labels: 🔒 BE, 😊 Feature

#1084 [BE] 아티클 수정 시 조회가 안되는 문제를 해결한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/article/service/ArticleService.java
Labels: 🐛 Bug, 🔒 BE

#1081 [FE] 어드민 페이지에 아티클 수정 기능을 추가한다.
  frontend/src/apis/article.ts
  frontend/src/apis/url.ts
  frontend/src/components/Admin/Article/AdminArticleCard.tsx
  frontend/src/components/Admin/Article/AdminArticleListContainer.tsx
  frontend/src/constants/routePath.ts
  frontend/src/hooks/query/usePutArticleQuery.ts
  frontend/src/hooks/useArticleForm.ts
  frontend/src/pages/AdminArticleListPage.tsx
  frontend/src/pages/AdminPage.tsx
  frontend/src/pages/EditArticlePage.tsx
  frontend/src/pages/NewArticlePage.tsx
  frontend/src/routers/router.tsx
Labels: 🔑 FE, 😊 Feature
