Repository woowacourse-teams/2024-bang-ggood, pull requests merged in 2025-04, with the labels that each got.

#1117 [FE] 스토리북 빠진 컴포넌트를 보충한다.
  frontend/.storybook/preview.tsx
  frontend/src/components/ArticleList/ArticleCard.stories.tsx
  frontend/src/components/_common/FaceIcon/FaceIcon.stories.tsx
  frontend/src/components/_common/FlexBox/FlexBox.stories.tsx
  frontend/src/components/_common/FlexBox/FlexBox.tsx
  frontend/src/components/_common/Highlight/HighlightText.stories.tsx
  frontend/src/components/_common/Like/LikeButton.stories.tsx
  frontend/src/components/_common/LoadingIndicator/LoadingIndicator.stories.tsx
  frontend/src/components/_common/LoadingIndicator/LoadingIndicator.tsx
  frontend/src/components/_common/LoginButton/EmailLoginButton.stories.tsx
  frontend/src/components/_common/LoginButton/KakaoLoginButton.stories.tsx
  frontend/src/components/_common/Map/RealTimeMap.tsx
  frontend/src/components/_common/Modal/AlertModal/AlertModal.stories.tsx
  frontend/src/components/_common/Modal/LoginModal/LoginModal.stories.tsx
  frontend/src/components/_common/Subway/SubwayStationItem.stories.tsx
  frontend/src/components/_common/Subway/SubwayStations.stories.tsx
  frontend/src/components/_common/Textarea/Textarea.stories.tsx
  frontend/src/components/_common/TopButton/TopButton.stories.tsx
Labels: 🔑 FE, ⚙ Chore, 🧪 Test

#1126 [BE] 사용자 커스텀 질문 기능을 추가한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/controller/QuestionController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/CustomChecklistQuestion.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/domain/Question.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/dto/request/QuestionCreateRequest.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/CustomChecklistQuestionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/repository/QuestionRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/CustomChecklistQuestionService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/question/service/QuestionService.java
  backend/bang-ggood/src/main/resources/data.sql
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/question/QuestionFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/controller/QuestionE2ETest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/repository/QuestionRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/ChecklistQuestionServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/CustomChecklistQuestionServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/QuestionManageServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/question/service/QuestionServiceTest.java
  backend/bang-ggood/src/test/resources/data-test.sql
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE, 😊 Feature

#1127 [BE] 작성한 체크리스트 링크 공유 기능을 구현한다.
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/controller/ChecklistController.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/domain/ChecklistShare.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/dto/response/ChecklistShareResponse.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/repository/ChecklistShareRepository.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistManageService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/checklist/service/ChecklistShareService.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ClientExceptionCode.java
  backend/bang-ggood/src/main/java/com/bang_ggood/global/exception/ExceptionCode.java
  backend/bang-ggood/src/main/resources/schema.sql
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/ChecklistFixture.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/repository/ChecklistShareRepositoryTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistManageServiceTest.java
  backend/bang-ggood/src/test/java/com/bang_ggood/checklist/service/ChecklistShareServiceTest.java
  backend/bang-ggood/src/test/resources/schema-test.sql
Labels: 🔒 BE, 😊 Feature

#1132 [FE] 새로운 디자인에 다른 공통컴포넌트(제이드파트) 구현
  frontend/.storybook/preview.tsx
  frontend/public/index.html
  frontend/src/assets/fonts/WantedSansStdVariable.ttf
  frontend/src/assets/icons/arrow/arrow-back.svg
  frontend/src/assets/icons/arrow/arrow-down-small.svg
  frontend/src/assets/icons/arrow/arrow-up-small.svg
  frontend/src/assets/icons/common/close.svg
  frontend/src/assets/icons/footer/Article.tsx
  frontend/src/assets/icons/footer/Checklist.tsx
  frontend/src/assets/icons/footer/Home.tsx
  frontend/src/assets/icons/footer/Profile.tsx
  frontend/src/components/_common/Accordion/Accordion.stories.tsx
  frontend/src/components/_common/Accordion/AccordionBody.tsx
  frontend/src/components/_common/Accordion/AccordionHeader.tsx
  frontend/src/components/_common/Dropdown/Dropdown.tsx
  frontend/src/components/_common/FlexBox/FlexBox.tsx
  frontend/src/components/_common/Footer/Footer.stories.tsx
  frontend/src/components/_common/Footer/Footer.tsx
  frontend/src/components/_common/Footer/FooterButton.tsx
  frontend/src/components/_common/FormField/FormField.stories.tsx
  frontend/src/components/_common/FormField/FormField.tsx
  frontend/src/components/_common/Header/Header.stories.tsx
  frontend/src/components/_common/Header/Header.tsx
  frontend/src/components/_common/Input/Input.stories.tsx
  frontend/src/components/_common/Input/Input.tsx
  frontend/src/constants/style.ts
  frontend/src/index.css
  frontend/src/styles/font.ts
  frontend/src/styles/global.ts
  frontend/src/utils/fontStyle.ts
Labels: 🔑 FE, 😊 Feature, 🎨 UI
