Repository woowacourse-teams/2024-bang-ggood, pull requests merged in 2025-06, with the labels that each got.

#1157 [BE] dev 환경에서 users를 FK로 가진 table 먼저 drop하도록 수정한다
  backend/bang-ggood/src/main/resources/schema.sql
Labels: 🔒 BE

#1159 [BE] dev 환경으로 코드를 배포한다
  backend/bang-ggood/src/main/resources/schema.sql
Labels: 🔒 BE

#1149 [FE] 마이페이지 디자인을 수정한다.
  frontend/src/assets/assets.tsx
  frontend/src/assets/icons/arrow/arrow-right.svg
  frontend/src/assets/icons/mascot/3D-bang-bang-icon.png
  frontend/src/components/MyPage/DeleteAccountModal.tsx
  frontend/src/components/MyPage/GuestFeature.tsx
  frontend/src/components/MyPage/GuestProfile.tsx
  frontend/src/components/MyPage/LogoutModal.tsx
  frontend/src/components/MyPage/ProfileSection.tsx
  frontend/src/components/MyPage/UserFeature.tsx
  frontend/src/components/MyPage/UserProfile.tsx
  frontend/src/components/_common/Button/Button.tsx
  frontend/src/components/_common/Header/Header.tsx
  frontend/src/components/_common/Modal/Modal.tsx
  frontend/src/components/_common/Modal/ModalHeader.tsx
  frontend/src/pages/MyPage.tsx
  frontend/src/styles/color.ts
Labels: 🔑 FE, 🎨 UI

#1154 [BE] 아티클 리스트 조회시 썸네일을 포함한다
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticlesResponse.java
Labels: 🔒 BE

#1165 [BE] 개발 환경으로 코드를 배포한다
  backend/bang-ggood/src/main/java/com/bang_ggood/article/dto/response/ArticlesResponse.java
Labels: 🔒 BE

#1167 [FE] 시즌1 리디자인 버전 배포 전 마무리 QA를 진행한다.
  frontend/src/assets/assets.tsx
  frontend/src/assets/icons/mascot/bang-bang-cry-gray-icon.svg
  frontend/src/components/ArticleList/ArticleKeywordSelectionSection.tsx
  frontend/src/components/ArticleList/ArticleListContainer.tsx
  frontend/src/components/ArticleList/ArticleThumbnailCard.tsx
  frontend/src/components/NewChecklist/MemoModal/MemoButton.tsx
  frontend/src/components/NewChecklist/MemoModal/MemoModal.tsx
  frontend/src/components/NewChecklist/NewRoomInfoForm/RoomInfoTemplate.tsx
  frontend/src/components/_common/FloatingButton/FloatingButton.tsx
  frontend/src/components/_common/Textarea/Textarea.tsx
  frontend/src/pages/ArticleListPage.tsx
  frontend/src/pages/MyPage.tsx
Labels: 🐛 Bug, 🔑 FE, ⚙ Chore

#1175 [FE] 메모 작성 버그를 수정한다.
  frontend/src/components/NewChecklist/MemoModal/MemoModal.tsx
  frontend/src/components/_common/Modal/FocusTrap/FocusTrap.tsx
  frontend/src/components/_common/Textarea/Textarea.tsx
Labels: 🐛 Bug, 🔑 FE
