Repository woowacourse-teams/2024-bang-ggood, pull requests merged in 2025-05, with the labels that each got.

#1140 [FE] 리디자인에 따른 체크리스트 리스트 페이지 레이아웃을 재구성한다.
  frontend/src/components/ChecklistList/ChecklistCard.tsx
  frontend/src/components/ChecklistList/CustomBanner.tsx
  frontend/src/components/ChecklistList/CustomBannerSection.tsx
  frontend/src/components/ChecklistList/LikeFilterButton.tsx
  frontend/src/components/_common/Button/Button.tsx
  frontend/src/components/_common/FloatingButton/FloatingButton.tsx
  frontend/src/components/_common/layout/Layout.tsx
  frontend/src/pages/ChecklistListPage.tsx
Labels: 🔑 FE, 😊 Feature, 🎨 UI

#1138 [FE] 옵션 아이콘 및 방 비교 페이지 css 수정한다.
  frontend/src/assets/icons/faceIcon/face-icon-bad.svg
  frontend/src/assets/icons/faceIcon/face-icon.good.svg
  frontend/src/assets/icons/faceIcon/face-icon.none.svg
  frontend/src/assets/icons/faceIcon/face-icon.soso.svg
  frontend/src/assets/icons/option/airconditioner-filled.svg
  frontend/src/assets/icons/option/airconditioner-unfilled.svg
  frontend/src/assets/icons/option/bed-filled.svg
  frontend/src/assets/icons/option/bed-unfilled.svg
  frontend/src/assets/icons/option/closet-filled.svg
  frontend/src/assets/icons/option/closet-unfilled.svg
  frontend/src/assets/icons/option/desk-filled.svg
  frontend/src/assets/icons/option/desk-unfilled.svg
  frontend/src/assets/icons/option/electronic-stove-filled.svg
  frontend/src/assets/icons/option/electronic-stove-unfilled.svg
  frontend/src/assets/icons/option/elevator-filled.svg
  frontend/src/assets/icons/option/elevator-unfilled.svg
  frontend/src/assets/icons/option/microwave-filled.svg
  frontend/src/assets/icons/option/microwave-unfilled.svg
  frontend/src/assets/icons/option/refrigerator-filled.svg
  frontend/src/assets/icons/option/refrigerator-unfilled.svg
  frontend/src/assets/icons/option/shoesrack-filled.svg
  frontend/src/assets/icons/option/shoesrack-unfilled.svg
  frontend/src/assets/icons/option/sink-filled.svg
  frontend/src/assets/icons/option/sink-unfilled.svg
  frontend/src/assets/icons/option/washingmachine-filled.svg
  frontend/src/assets/icons/option/washingmachine-unfilled.svg
  frontend/src/components/NewChecklist/Option/OptionButton/OptionButton.tsx
  frontend/src/components/NewChecklist/Option/OptionList.tsx
  frontend/src/components/RoomCompare/CategoryDetailModal.tsx
  frontend/src/components/RoomCompare/CategoryScore.tsx
  frontend/src/components/RoomCompare/CompareCard.tsx
  frontend/src/components/RoomCompare/CompareCardItem.tsx
  frontend/src/components/RoomCompare/OptionDetailModal.tsx
  frontend/src/components/RoomCompare/RoomCompareContent.tsx
  frontend/src/components/_common/Modal/Modal.tsx
  frontend/src/pages/RoomComparePage.tsx
Labels: 🔑 FE, 🎨 UI

#1144 [FE] 방 비교페이지의 모달데이터를 prefetch한다
  frontend/src/App.tsx
  frontend/src/components/RoomCompare/RoomCompareContent.tsx
  frontend/src/hooks/query/useGetRoomCategoryDetail.ts
Labels: 🔑 FE

#1142 [FE] 리디자인에 따라 로그인 페이지를 구성한다.
  frontend/src/assets/assets.tsx
  frontend/src/assets/icons/arrow/arrow-down-small.svg
  frontend/src/components/ChecklistList/CustomBannerSection.tsx
  frontend/src/components/Landing/FirstSection.tsx
  frontend/src/components/ResetPassword/EnterVerificationCodeStep.tsx
  frontend/src/components/ResetPassword/ResetPasswordStep.tsx
  frontend/src/components/ResetPassword/SendVerificationEmailStep.tsx
  frontend/src/components/ResetPassword/style.ts
  frontend/src/components/_common/Button/Button.tsx
  frontend/src/components/_common/FlexBox/FlexBox.tsx
  frontend/src/components/_common/FormField/FormField.tsx
  frontend/src/components/_common/Input/Input.tsx
  frontend/src/components/_common/LoginButton/EmailLoginButton.tsx
  frontend/src/components/_common/LoginButton/KakaoLoginButton.tsx
  frontend/src/pages/ChecklistListPage.tsx
  frontend/src/pages/SignInPage.tsx
Labels: 🔑 FE, 🎨 UI
